### ISSUE TITLE
Config codon table for the whole genome

### ISSUE THREAD

**Issue by pcingola** [pcingola/SnpEff#112]
Some genomes having thousands of contigs need alternative codon tables.
Adding every single chromosome is a mess.
We need a "genome-wide" codon table configuration option:

    T.thermophila.codon_table = .....  # Genome wide codon table
    T.thermophila.chrNNNN.codon_table = .... # Chromosome specific codon table (overrides genom-wide)

Chromosome specific codon tables should override genome-wide option.

**Comment by pcingola** [comment]
Done

**Comment by rob123king** [comment]
So how would you do this if fasta is not named with chr but starts with different sequence identifiers. could you do below?
#bart
bart.genome : bart
	bart.*.codonTable : Bacterial_and_Plant_Plastid
