### ISSUE TITLE
Vcf does not match _genes.txt summary file

### ISSUE THREAD

**Issue by moorembioinfo** [pcingola/SnpEff#119]
Hi!

I was wondering whether you could help with an issue I'm having. I have noticed that the snpEff vcf file output from the software does not match the _genes.txt summary file. 

My vcf file has 140 high impact mutations while the summary file has 156. Those 16 extra in the summary file are not at all present in the vcf file. 

An example gene, which is not present in the vcf is:

#GeneName	GeneId	TranscriptId	BioType	variants_impact_HIGH	variants_impact_LOW	variants_impact_MODERATE	variants_impact_MODIFIER	variants_effect_CODON_CHANGE_PLUS_CODON_DELETION	variants_effect_CODON_CHANGE_PLUS_CODON_INSERTION	variants_effect_CODON_DELETION	variants_effect_CODON_INSERTION	variants_effect_DOWNSTREAM	variants_effect_FRAME_SHIFT	variants_effect_FRAME_SHIFT+START_LOST	variants_effect_FRAME_SHIFT+STOP_GAINED	variants_effect_FRAME_SHIFT+STOP_LOST	variants_effect_NON_SYNONYMOUS_CODING	variants_effect_NON_SYNONYMOUS_START	variants_effect_START_LOST	variants_effect_START_LOST+CODON_DELETION	variants_effect_STOP_GAINED	variants_effect_STOP_GAINED+CODON_CHANGE_PLUS_CODON_INSERTION	variants_effect_STOP_GAINED+CODON_INSERTION	variants_effect_STOP_LOST	variants_effect_STOP_LOST+CODON_DELETION	variants_effect_SYNONYMOUS_CODING	variants_effect_SYNONYMOUS_START	variants_effect_SYNONYMOUS_STOP	variants_effect_UPSTREAM	bases_affected_DOWNSTREAM	total_score_DOWNSTREAM	length_DOWNSTREAM	bases_affected_EXON	total_score_EXON	length_EXON	bases_affected_TRANSCRIPT	total_score_TRANSCRIPT	length_TRANSCRIPT	bases_affected_UPSTREAM	total_score_UPSTREAM	length_UPSTREAM
pvdD	PA2399	NP_251089.1		9	5	9	72	0	1	2	0	36	9	0	0	0	6	0	0	0	0	0	0	0	0	5	0	0	36	36	0	5000	23	0	7347	0	0	0	36	0	5000

Thanks in advance for any help with this! In the vcf file there is no mutation in this gene but perhaps snpEff does something more sophisticated and predicts the impact of mutations upstream?

**Comment by pcingola** [comment]
Hi,
  Please keep in mind that one mutation can affect more than one 
transcript, thus it may count multiple times.
  If you provide a sample input VCF file and the command line 
you are using, I can try to reproduce the issue and provide a more 
detailed explanation (or a bug-fix if necessary).

**Comment by moorembioinfo** [comment]
Hi sorry for the massively slow reply and thanks for your reply! It's clear now that the difference between the genes.txt and vcf file is those which are upstream (not actually within the gene). 

Is there any way to extract the reference positions of these variants from snpEff?

**Comment by pcingola** [comment]
I'm not sure if I understand what you mean by "Is there any way to extract the reference positions of these variants from snpEff?", but may be the information in the HGVS notation can be useful.
If you show me a concrete example, may be I can help you better...

**Comment by pcingola** [comment]
I guess you should filter by "upstream" or "downstream"
