### ISSUE TITLE
transcript support level flags 

### ISSUE THREAD

**Issue by gpcr** [pcingola/SnpEff#121]
is there a way to add ensembl TSL flags with every transcript in the ANN field;
or specify TSL flag filter to annotate only transcripts which pass this filter (say filtering out TSL 4 or 5 flagged transcripts) 
thanks always for your support, happy holidays

**Comment by pcingola** [comment]
You can use command line option '-maxTSL':

-maxTSL <TSL_number>         : Only use transcripts having Transcript Support Level lower than <TSL_number>.

**Comment by gpcr** [comment]
if i use  -maxTSL 3  i am not getting any transcript annotated 

# WARNING! : No protein coding transcripts found.                                                                                                                                             
#-----------------------------------------------                                                                                                                                              
                                                                                                                                                                                              
00:00:29        Predicting variants                                                                                                                                                           
00:00:29        Running multi-threaded mode (numThreads=32).                                                                                                                                  
00:00:29        Creating sequences from exon information '1'                                                                                                                                  
00:00:29        Building sequence tree for chromosome '1'                                                                                                                                     
00:00:29        Building sequence tree for genome sequences                                                                                                                                   
00:00:29        Done.                                                 
....

For example: 
without -maxTSL option
T|stop_gained|HIGH|ISG15|ENSG00000187608|transcript|ENST00000379389|protein_coding|2/2|c.163C>T|p.Gln55*|314/711|163/498|55/165||,T|sequence_feature|LOW|ISG15|ENSG00000187608|domain:Ubiquitin-like_1|ENST00000379389|protein_coding|2/2|c.163C>T||||||,T|upstream_gene_variant|MODIFIER|RP11-54O7.11|ENSG00000224969|transcript|ENST00000458555|antisense||n.-950G>A|||||950|

with -maxTSL :
T|intragenic_variant|MODIFIER|ISG15|ENSG00000187608|gene_variant|ENSG00000187608|||n.949523C>T||||||


TSL value for ENST00000379389 is 1

what might be the issue? thanks for your support
