### ISSUE TITLE
SnpEff Closest not denoting blank fields

### ISSUE THREAD

**Issue by summerela** [pcingola/SnpEff#122]
Hi Pablo-

I'm using SnpeEff Closest to annotate intergenic regions and ran across a bug when trying to parse the output. 

I ran this command (with actual file names of files in standard vcf format): 
java -Xmx16g -jar snpeff_jar -t -v GRCh37.75 vcf_file > out_file

My output looks like this: 

![image](https://cloud.githubusercontent.com/assets/9097886/12591713/06bffb06-c41e-11e5-9a1b-e3e9ac37a1f6.png)

According to your documentation, there should be four uniform fields:
"Distance (bases), exons Id, transcript Id, gene name"

However, not only do I have additional undocumented fields in my output, I am also finding blanks that are not marked with any kind of place-holder, making the output impossible to parse. 

For example, the following row: 
8   87103686    .   G   A   .   .   CLOSEST=0|Intron,intron_1_ALTTENATIVE_PROMOMOTER-SKIPPED,ENST00000523635,protein_coding,ATP6V0D2,protein_coding|Intron,intron_3_SKIPPED-ALTTENATIVE_5SS,ENST00000521564,protein_coding,ATP6V0D2,protein_coding|Upstream,ENST00000517981,processed_transcript,PSKH2,protein_coding   .   .

Notice that a field is missing in the last piped section: 

Upstream,ENST00000517981,processed_transcript,PSKH2,protein_coding

In order to parse this programatically, it needs some sort of placeholder for the missing field (see extra comma below): 

Upstream,ENST00000517981,,processed_transcript,PSKH2,protein_coding

So in addition to indicating that a field is empty, could you also please point me to some documentation on what the extra fields are and perhaps why many of them are duplicated? 

![image](https://cloud.githubusercontent.com/assets/9097886/12591740/219b3210-c41e-11e5-8e10-07caea9e67f8.png)

Thanks!

**Comment by pcingola** [comment]
Hi @summerela 
   Sorry for the long delay answering this question.
The comma separated list after the pipe sign is not intended to have a fixed 
number of element. I agree that the format is rather whimsical and the 
documentation is lacking.

I made an to improve the format for easier parsing (this is complicated by 
the amount of information I'm trying to squeze in). In my development 
version now the output looks like this:

    CLOSEST = distance | type_chain_1 | type_chain_2 | ... | type_chain_N

Each "type_chain" is a comma delimited list of fields that look look 
like "type[:optional_info]*" (the asterisk indicates that there can be 
zero or more "optional_info" separated by colon.

The optional info is different for each type (and may not appear 
if the information is missing):

    Gene : gene_ID : gene_biotype
    Transcript : transcript_ID : transcript_biotype
    Exon : exon_rank : number_of_exons_in_transcript : exon_splice_type
    Intron: intron_rank : number_of_introns_in_transcript : intron_splice_type
    Upstream [: no optional info]
    Downstream [: no optional info]

I'm not sure if this helps or makes the problem even worse...
Any thoughts?

**Comment by pcingola** [comment]
Closing old issues.
