### ISSUE TITLE
Pseudomonas aeruginosa LESB58 database

### ISSUE THREAD

**Issue by moorembioinfo** [pcingola/SnpEff#123]
Hi, 

I've noticed that with snpEff 4.1. the database for Pseudomonas aeruginosa LESB58 (Pseudomonas_aeruginosa_LESB58_uid59275) incorrectly annotates mutations within the gene gltR (according to the LESB58 annotation ) as gapA.

This wasn't the case with earlier distributions. I'm not sure if there are problems with any other genes, there aren't within my samples. 

Thanks in advance!

**Comment by pcingola** [comment]
Can you send some more details, as well as an example input file and the 
command line you are using? I'll try to replicate the error condition.

**Comment by moorembioinfo** [comment]
Hi! Sorry I've been away from this data on other projects. 

There isn't an error rather that in LESB58 (I'm using snpEff database (Pseudomonas_aeruginosa_LESB58_uid59275), the gene gltR or PLES_18761is situated from reference position 2018487 to 2019215. 

This is the resulting snpEff vcf at a position within that range however:

NC_011770	2018583	.	CGCAGCGTCTCGCGG	C	2778.97	.	AC=1;AF=1.00;AN=1;DP=63;FS=0.000;MLEAC=1;MLEAF=1.00;MQ=60.34;MQ0=0;QD=30.91;SOR=0.859;EFF=UPSTREAM(MODIFIER||3186||gapA|protein_coding|CODING|YP_002439477.1|)	GT:AD:DP:GQ:PL	1:0,63:63:99:2818,0

Thanks in advance for any help with this! This is a mutation I expected to be within gltR but I'm concerned there may be other disagreements between the gene coordinates (Pseudomonas.com and elsewhere) and Pseudomonas_aeruginosa_LESB58_uid59275

**Comment by moorembioinfo** [comment]
java -jar ~/snpEff.jar eff -i vcf -o gatk -s stats -c ~/snpEff.config -v Pseudomonas_aeruginosa_LESB58_uid59275 <vcffile> > output

Was the full command, I can't provide a sample vcf unfortunately but there isn't an error in running anyway.

Thanks!

**Comment by pcingola** [comment]
Closing old issues.
