### ISSUE TITLE
Snpeff error on GATK-3.4-46 vcf with spanning deletions.

### ISSUE THREAD

**Issue by mmterpstra** [pcingola/SnpEff#140]
As seen on this poorly documented/formatted forum post:
http://gatkforums.broadinstitute.org/gatk/discussion/5997/haplotypercaller-gvcf-unkown-iub-code-for-snp

If you use the workflow with gvcfs the combineGvcfs tools reports SNVs with spanning deletions like:

```
1 6272137 rs709208 A G,* 1817.65 PASS
```

The alternate `*` in seen as invalid and snpeff fails on:
```
 java.lang.RuntimeException: java.lang.RuntimeException: WARNING: Unkown IUB code for SNP '*'
```

In GATK-3.4-0 the original annotation of this variant was written down by `<*.DEL>` instead of `*` and doesn't produce this error. I think this is due to the fact SnpEff does not support this part of the 4.2 vcf spec:

>the `*' allele is reserved to indicate that the allele is missing due to a upstream deletion. 

[source: vcf spec 4.2 page 4](http://samtools.github.io/hts-specs/VCFv4.2.pdf)

Can you add support for spanning deletions in SnpEff consistent with the vcf 4.2 spec? Or did you fix this in another older version/issue?

**Comment by pcingola** [comment]
Fixed.

    $ cat zzzz.vcf 
    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
    1	6272137	.	A	G,*	.	.	.

    $ java -jar snpEff.jar hg19 zzzz.vcf | tee zzzz.ann.vcf
    ...
    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NSD303-17-H1-SS2.AHY22LBGXX
    1	6272137	.	A	G,*	.	.	ANN=G|intron_variant|MODIFIER|RNF207|RNF207|transcript|NM_207396.2|protein_coding|13/17|c.1296+24A>G||||||

Will release soon.

**Comment by mmterpstra** [comment]
Thanks!
Op 6 jun. 2016 6:41 PM schreef "Pablo Cingolani" <notifications@github.com>:
