### ISSUE TITLE
Deletion in splice site flagged as LOF

### ISSUE THREAD

**Issue by jjfarrell** [pcingola/SnpEff#145]
We have found a few splice site deletions flagged as LOF which are not really LOF. This occurs when the nucleotides that shift over are the same as the deleted base pairs.  Could the context of the splice site deletion be taken into account when flagging LOF in splice sites?

**Comment by pcingola** [comment]
Closing old issues.

**Comment by jjfarrell** [comment]
Was this issue ever resolved or just closed?

Loftee deals with this situation with this approach....

Variants that are "rescued" by nearby, in-frame splice sites (max_scan_distance determines distance from original splice site where rescue splice sites can occur; default = 15 bp)
