### ISSUE TITLE
about snpsift's interval function

### ISSUE THREAD

**Issue by mortunco** [pcingola/SnpEff#147]
Hi,

This question is not related to any bug. I just wanted to know that if I can get a number of variants found with the given interval in a log file or etc.

I need this information because I wrote a python script that uses vcftools to overlap the mutations in the vcfs and bed file intervals. Vcftools produce a log file which states like x number of mutations in total mutation number found. I just wanted to ask how can I get this info in snpsift ?

Best,

Tunc.

**Comment by pcingola** [comment]
Closing old issues.
