### ISSUE TITLE
Collection of wishes and potential issues

### ISSUE THREAD

**Issue by mjafin** [pcingola/SnpEff#149]
Hi @pcingola, 
Here's a collection of issues discussed with @zhongwulai
1. Indels near ends of exons on the intronic side can be incorrectly classified as splice regions variants if in repeat region (I hope I got this right)
2. Instead of requiring a list of all (alternative) transcripts, enable replacement of just a few (like BRCA1, ESR1) without having to maintain a list of all
3. If possible include exon numbers in fusions (like FGFR3 exons 1 through to 18 + TACC3 exons 11 through 16 or similar)
4. In fusions name genes in 5' to 3' order instead of alphabetic
5. Something about last bp / exon edge mutations (Zhongwu to give more details)

**Comment by pcingola** [comment]
Closing old issues.
