### ISSUE TITLE
SnpEff len analysis NullPointerException Error

### ISSUE THREAD

**Issue by suimye** [pcingola/SnpEff#151]
Hi.
When I am running SnpEff with "len" option, I get the following error messages.

> java -Xmx4g -jar ~/tool/snpEff/snpEff.jar len -r 100 GRCh37.75
> java.lang.NullPointerException
>        at >ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdLen.run(SnpEffCmdLen.java:159)
>        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:978)
>        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:136)

To test the other conditions, I changed memory size range from 10g to 1g. At the memory range over 3g, I got the similar error code as java.lang.NullPointerException. On the other hand, at the range of 2g to 1g, I got the OutOfMemoryError.

> -bash-4.1$ java -Xmx2g -jar ~/tool/snpEff/snpEff.jar len -r 100 GRCh37.75
> java.lang.OutOfMemoryError: Java heap space
>        at ca.mcgill.mcb.pcingola.interval.Intron.<init>(Intron.java:35)
>        at ca.mcgill.mcb.pcingola.interval.Transcript.introns(Transcript.java:1174)
>        at >ca.mcgill.mcb.pcingola.interval.Transcript.createSpliceSites(Transcript.java:655)
>        at ca.mcgill.mcb.pcingola.interval.Genes.createSpliceSites(Genes.java:147)
>        at >ca.mcgill.mcb.pcingola.snpEffect.SnpEffectPredictor.createGenomicRegions(SnpEffectPredi>ctor.java:205)
>        at >ca.mcgill.mcb.pcingola.snpEffect.SnpEffectPredictor.buildForest(SnpEffectPredictor.java>:165)
>        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.loadDb(SnpEff.java:451)
>        at >ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdLen.run(SnpEffCmdLen.java:156)
>        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:978)
>        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:136)

I wondered about 32bit condition in JAVA. I also tried -d64 option in similar command. But I could not resolve this problem. On the other hand, the other SnpEff analyses such as "annotate, -cancer" were successfully done.Thus, this problem was only occurred in "len" analysis.

If you have any suggestion for this error, please reply to me.

My software environment is..
###### 

SnpEff version SnpEff 4.2 (build 2015-12-05)
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

distribution
CentOS release 6.7 (Final)
memory 16GB

**Comment by kpboh** [comment]
I have the same problem. Error showed up irrespective of which genome I selected.

**Comment by pcingola** [comment]
Closing old issues.
