### ISSUE TITLE
Protein interaction sites with SYN variants: Impact should be LOW

### ISSUE THREAD

**Issue by pcingola** [pcingola/SnpEff#155]
Email from user:

Are variants annotated as protein_protein_contact only because they reside in a region predicted to be a binding site?
My thinking is that if the variant (ex. rs56317545) is synonymous but resides within a binding site, it need not have a HIGH impact necessarily. Would you agree with this logic? If so, should I only designate protein_protein_contact + missense (or stop, etc) as HIGH?

**Comment by lajoimat** [comment]
I totally agree.

Moreover, I think that for any given variant,  "structural_interaction_variant" and similarly predicted annotations should be reported *after* the "missense_variant" annotation.

**Comment by pcingola** [comment]
Closing old issues.

**Comment by AlesMaver** [comment]
I would just like to add that the structural_interaction_variant annotation still causes some confusion in our use of snpEff. Generally, these predictions produce multiple effects with various UniProt identifiers and they are automatically classified as HIGH, although after inspection usually impact of these variants is closer to the MODERATE or LOW classes. Is there a plan or a possibility to optionally disable structural_interaction_variant annotation from the snpEff outputs?
