### ISSUE TITLE
SnpSift vcfCheck print dots on STDERR

### ISSUE THREAD

**Issue by mmokrejs** [pcingola/SnpEff#159]
Hi Pablo,
  I wanted to check my VCF files for consistency. I call SnpSift-4.3g vcfCheck in a loop over all VCF files but was surprised I had to see plenty of dots printed on my STDERR. I worked around it by redirecting STDOUT and STDERR into separate files and by "grep -v "...." *.STDERR ...but is that really needed?

  I think printing a progress values on STDERR is not very much useful. I propose to only output results on STDOUT if some VCF file is broken, ideally in some format which could be eventually easily parseable by awk, etc. Notably, the broken filename should be accessible.

**Comment by pcingola** [comment]
Closing old issues.
