### ISSUE TITLE
Cannot build SnpEff

### ISSUE THREAD

**Issue by emreatbina** [pcingola/SnpEff#160]
I get the following error when I try to build SnpEff with Maven.

[ERROR] Failed to execute goal on project SnpEff: Could not resolve dependencies for project org.snpeff:SnpEff:jar:4.3: The following artifacts could not be resolved: org.biojava:biojava3-core:jar:3.0.7, org.biojava:biojava3-structure:jar:3.0.7: Could not find artifact org.biojava:biojava3-core:jar:3.0.7

I looked at all the repositories listed in the pom and I was not able to find this jar in any of them.

**Comment by pcingola** [comment]
The JARs are at 'SnpEff/lib' directory and you have to install them manually using a maven command like this one:

   mvn install:install-file -Dfile=antlr-4.5.1-complete.jar -DgroupId=org.antlr -DartifactId=antlr -Dversion=4.5.1 -Dpackaging=jar

**Comment by pcingola** [comment]
I think this should solve the issue. Feel free to re-open otherwise.
