### ISSUE TITLE
Error connecting to sourceforge to download database

### ISSUE THREAD

**Issue by mken418** [pcingola/SnpEff#161]
Hello, 

- I executed the database option to locate databases for Glycine_max.
- I used the database: gmax1.09v8

$ java -jar snpEff.jar gmax1.09v8 Sample_PI574_486.1.raw.g.vcf
I then get the error:
ERROR while connecting to http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_gmax1.09v8.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.

I searched on sourceforge for this database and it does not exist, however, "snpEff_v4_3_gmax1.09v8.zip" does exist in the v4_2 directory. 

Th other gmax in the database is gmax1.09, which also gives me the same error and is located in the v4_2 directory on sourceforge. 

I'm working on creating my own directory for Glycine max because I can't seem to figure out how to get around this issue.

**Comment by pcingola** [comment]
Seems to work OK for me:

```
$ java -jar snpEff.jar download -v Glycine_max
00:00:00	SnpEff version SnpEff 4.3k (build 2017-03-29 17:16), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'Glycine_max'
00:00:00	Reading config file: /home/pcingola/workspace/SnpEff/snpEff.config
00:00:00	done
00:00:00	Downloading database for 'Glycine_max'
00:00:00	Connecting to http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_ENSEMBL_BFMPP_32_152.zip
00:00:01	Following redirect: https://iweb.dl.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_ENSEMBL_BFMPP_32_152.zip
00:00:02	Local file name: '/tmp/snpEff_v4_3_ENSEMBL_BFMPP_32_152.zip'
...................
```
