### ISSUE TITLE
Is SnpEff applicable for HIV virus

### ISSUE THREAD

**Issue by FaneeChen** [pcingola/SnpEff#163]
HIV is different in structure from other retroviruses. It is composed of two copies of positive single-stranded RNA . So ,is  SnpEff applicable for such  positive single-stranded RNA ?

**Comment by pcingola** [comment]
Some researchers used SnpEff for HIV before.

**Comment by FaneeChen** [comment]
Thank you very much

**Comment by Lei-GitHub** [comment]
> Some researchers used SnpEff for HIV before.

Hi, Is there HIV datebase available in the databases? I did not get it by java -jar /data/software/snpEff/snpEff.jar databases  | grep -i HIV. Should I build the database for HIV? Thank you very much

**Comment by pcingola** [comment]
Please open another issue instead of using closed ones.
Do you know the GenBank ID?  (e.g. AF033819.3)

**Comment by Lei-GitHub** [comment]
Hi Pablo,
Thank you very much for your email. I created my new question. Yes, the
gene bank ID is  K03455.1 and refseq is  NC_001802.1. Thank you very much.

*Lei Xu  *Ph.D.

National Institute of Health

Phone:  2407795397

Fax: 301-402-3241

Email: ***@***.***
