### ISSUE TITLE
Annotation vardict vcf problem on insertion 

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [pcingola/SnpEff#164]
I have annotate some vardict vcf from  vcf obtained from paired analysis.
I have many rows are not annotated in particular the insertions. You can see here:

``
`'chr12', '7080212', '.', 'T', 'GC', '214.0', 'PASS', 'STATUS=Germline;SAMPLE=411_tumor_412_normal;TYPE=Complex;SHIFT3=0;MSI=0;MSILEN=0;SSF=0.56099;SOR=0.96889;LSEQ=AAACAAGATCGGAGGCCGTA;RSEQ=TTATTGTGGTGCTGGAAGGG', 'GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM', '1/1:104:93:23,70:1,2:3,93:0.8942:2,2:25.3:1:32.9:1:1:1.51447:60:186:0.9394:0.1827:0.9', '1/1:107:96:34,62:1,1:2,96:0.8972:2,2:25.5:1:32.5:1:1:1.81163:60:192:0.932:0.1121:0.9', '411_tumor_412_normal.12.vardict.vcf'`
chr18', '21123533', '.', 'TCTT', 'CTTTA', '57.0', 'PASS', 'STATUS=StrongLOH;SAMPLE=411_tumor_412_normal;TYPE=Complex;SHIFT3=0;MSI=2.000;MSILEN=1;SSF=0.16247;SOR=0;LSEQ=CCCTTGAAGACGTTCATCTC;RSEQ=AAAAAAAAAAAAAAAAAATT', 'GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM', '0/0:90:0:0,0:30,59:89,0:0:2,0:21:1:29:1:1:0:60.1:3.238:1:0:0.4', '0/1:158:4:0,4:56,97:153,4:0.0253:2,0:9.8:1:28.6:1:0.29762:0:60:3:0.0259:0.019:1', '411_tumor_412_normal.18.vardict.vcf'
``
The command that I use is this:

`java -jar ~/snpEff eff  -v -c ~/illumina/software/snpEff.config -o vcf -i vcf  -stats *.html hg19  *.vcf > 411.snpeff.vcf`

**Comment by pcingola** [comment]
Tha is not in propper VCF. It should have no quotes around each field.
Your file is corrupted, you need to recover the original VCF.
