### ISSUE TITLE
Prolem on parse vardict ouput

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [pcingola/SnpEff#165]
I have this error any suggestion?

`
~/jdk1.8.0_121/bin/java -jar /illumina/software/PROG/snpEff/snpEff.jar  eff -v -c  /illumina/software/PROG/snpEff/snpEff.config  -o vcf -i vcf -lof  -stats 415.snpefff.html hg19 /illumina/runs/FASTQ/Analisi_15novembre2016/Prova3/ALIGN/413/rawVardict/413_tumor_414_normal.Y.vardict.vcf.MERGED.vcf  > 413.snpeff.vcf
> 00:00:00.000	Reading configuration file '/illumina/software/PROG/snpEff/snpEff.config'. Genome: 'hg19'
> 00:00:00.264	done
> 00:00:00.265	Reading database for genome version 'hg19' from file '/illumina/software/PROG/snpEff/./data/hg19/snpEffectPredictor.bin' (this might take a while)
> 00:00:09.352	done
> 00:00:09.373	Building interval forest
> 00:00:23.319	done.
> 00:00:23.320	Genome stats :
> # Genome name                : 'Homo_sapiens (USCS)'
> # Genome version             : 'hg19'

> 00:00:30.647	Predicting variants
> VcfFileIterator.parseVcfLine(121):	Fatal error reading file '/illumina/runs/FASTQ/Analisi_15novembre2016/Prova3/ALIGN/413/rawVardict/413_tumor_414_normal.Y.vardict.vcf.MERGED.vcf' (line: 56):
> chr10 93098 . C T 30 v3;p8 STATUS=StrongSomatic;SAMPLE=413_tumor_414_normal;TYPE=SNV;SHIFT3=0;MSI=2.000;MSILEN=1;SSF=0.26716;SOR=Inf;LSEQ=CAGGTCGTTCATGTTGCTCT;RSEQ=GGCCTCGGTGAATTCCATCT GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM 0/1:100:2:2,0:95,3:98,2:0.02:1,0:7:1:30.5:1:1:0:40:4:0.0204:0:1 0/0:93:0:0,0:92,0:92,0:0:1,0:26.4:1:33.3:1:1:0:40:45:1:0:0.1
> java.lang.RuntimeException: java.lang.RuntimeException: Impropper VCF entry: Not enough fields (missing tab separators?).
> chr10 93098 . C T 30 v3;p8 STATUS=StrongSomatic;SAMPLE=413_tumor_414_normal;TYPE=SNV;SHIFT3=0;MSI=2.000;MSILEN=1;SSF=0.26716;SOR=Inf;LSEQ=CAGGTCGTTCATGTTGCTCT;RSEQ=GGCCTCGGTGAATTCCATCT GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM 0/1:100:2:2,0:95,3:98,2:0.02:1,0:7:1:30.5:1:1:0:40:4:0.0204:0:1 0/0:93:0:0,0:92,0:92,0:0:1,0:26.4:1:33.3:1:1:0:40:45:1:0:0.1
> 	at ca.mcgill.mcb.pcingola.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:122)

`

**Comment by pcingola** [comment]
The error says "not enough fields (missing tab separators?)" which points to a corrupted VCF file. 
Make sure the file is a proper VCF (often this type of errors are due to someone doing something stupid, like editing VCF files using Word).
