### ISSUE TITLE
add CODON change in ANN fields 

### ISSUE THREAD

**Issue by gpcr** [pcingola/SnpEff#166]
Request to add CODON change in ANN fields 

HGVS_C (alias HGVS_DNA, **CODON**): Variant in HGVS (DNA) notation

ANN:
G|missense_variant|MODERATE|OR4F5|ENSG00000186092|transcript|**ENST00000335137.3**|protein_coding|1/1|c.421A>G|p.Thr141Ala|421/918|421/918|141/305||	

EFF:
missense_variant(MODERATE|MISSENSE|**Aca/Gca**|p.Thr141Ala/c.421A>G|305|OR4F5|protein_coding|CODING|**ENST00000335137**|1|G)

Thanks,

**Comment by pcingola** [comment]
This was discussed several times with the other teams developing the format and it was decided that HGVS notation was much more useful than codon change information.

**Comment by gpcr** [comment]
May be as a saperate field as in EFF ?

**Comment by pcingola** [comment]
Closing old issues.
