### ISSUE TITLE
'transcript' not seen as a valid sequence ontology term

### ISSUE THREAD

**Issue by davidhoover** [pcingola/SnpEff#167]
When running SnpSift, I ran into this error:

“Exception in thread “main” java.lang.RuntimeException: Cannot parse EffectType ‘transcript’

I pinned down the error to the second term of an annotation block:

ANN=G|........,G|transcript|MODIFIER|TMEM240|ENSG00000205090|transcript|ENST00000425828|protein_coding||c.-9-2_-7delGGCCC||||||; .......

If I substitute 'transcript' in the second field to something else (e.g. gene_variant), SnpSift has no problems.

The VCF input was annotated using SnpEff:

java -jar $SNPEFF_JAR -c $SNPEFF_HOME/snpEff.config -v -canon -no-intergenic -no INTRAGENIC -no-downstream -no-upstream -no-utr -no PROTEIN_STRUCTURAL_INTERACTION_LOCUS -no NEXT_PROT -noStats GRCh37.75 ../test.vcf

**Comment by pcingola** [comment]
Closing old issues.
