### ISSUE TITLE
Optionally output only summarized effect prediction for large structural variants. 

### ISSUE THREAD

**Issue by NeillGibson** [pcingola/SnpEff#168]
Dear @pcingola ,

We use SnpEff to annotate structural variant VCF files. 

For large putative structural variants of a few million bases the VCF ANN field becomes very large. 
This breaks downstream applications that we use for storing and querying the VCF file.

Would it be possible to add optional functionality to SnpEff that large structural variants only get a summarized effect prediction. For example only the list of genes hit. 

Or if the summarized output would brake the specification of the VCF ANN field mabye output `ANN=`. for large structural variants?

For example a  command line switch: `java -jar snpEff.jar ann -max_sv_size 1000000`

Thank you.

**Comment by pcingola** [comment]
Closing old issues.
