### ISSUE TITLE
snpSift 4.3m extract fields (regardless of arguments) returns only ANN[*].ALLELES or all fields in info column from snpEff 4.3 .vcf output

### ISSUE THREAD

**Issue by naterobinett** [pcingola/SnpEff#169]
#regardless of how I set up the argument (and I have tried everything conceivable), extract fields (snpSift 4.3m) only gives me 1) the alleles or 2) all the information for all the "|" delimited fields.
#command:
 
**java -Xmx4g -jar /home/SOFTWARE/SNPEFF/snpEff/SnpSift.jar extractFields -v /home/nrobinett/Projects/SLI_2013_MT_Por_only/9.dn_ds/SLI_metatrans_ass1.dd.mc.rg.HC.SF.vcf CHROM POS REF ALT "ANN[*].ALLELE:" > /home/nrobinett/Projects/SLI_2013_MT_Por_only/13.dn_ds/out1.TAB**

#returns what it is supposed to (tab delim. with annotated allele in the last column).
#if I run the following command:

**java -Xmx4g -jar /home/SOFTWARE/SNPEFF/snpEff/SnpSift.jar extractFields -v /home/nrobinett/Projects/SLI_2013_MT_Por_only/9.dn_ds/SLI_metatrans_ass1.dd.mc.rg.HC.SF.vcf CHROM POS REF ALT "ANN[*].ALLELE:" "ANN[*].EFFECT" "ANN[*].IMPACT" "ANN[*].HGVS_P" > /home/nrobinett/Projects/SLI_2013_MT_Por_only/13.dn_ds/out2.TAB**

#returns the above results with EVERYTHING else in the info field. It is behaving like there is a problem. #parsing at the "|". The part of the .VCF that is likely appropriate is shown below:

**##SnpEffVersion="4.3m (build 2017-05-05 18:41), by Pablo Cingolani"
##SnpEffCmd="SnpEff  MT_Por_n1_met /home/nrobinett/ORF_prediction_MT_Por_n1/SLI_metatrans_ass1.dd.mc.rg.HC.vcf "
##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">
##INFO=<ID=LOF,Number=.,Type=String,Description="Predicted loss of function effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
##INFO=<ID=NMD,Number=.,Type=String,Description="Predicted nonsense mediated decay effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	FM3.3AB	FM3.5AB	FM5.1AB	FM5.2AB	FM5.2DE	MC.5DE	MI.1AB	MT.3AB	MT.5AB	SS.1AB	SS.2AB	SS.3AB	SS.4AB	ST.1AB	ST.2AB	ST.3AB	ST.4AB	VM.2AB	VM.3AB	VM.3DE	VM.4D
c5_g1_i1	167	.	G	A	63.35	.	AC=2;AF=0.500;AN=4;BaseQRankSum=-0.431;ClippingRankSum=0.000;DP=3;ExcessHet=0.7918;FS=0.000;MLEAC=2;MLEAF=0.500;MQ=42.00;MQRankSum=0.000;QD=31.68;ReadPosRankSum=0.000;SOR=2.225;ANN=A|missense_variant|MODERATE|CDS_c5_g1_i1_2_436|GENE_CDS_c5_g1_i1_2_436|transcript|TRANSCRIPT_CDS_c5_g1_i1_2_436|protein_coding|1/1|c.269C>T|p.Ala90Val|270/435|269/434|90/143||WARNING_TRANSCRIPT_INCOMPLETE,A|upstream_gene_variant|MODIFIER|START_CODON_c5_g1_i1_2_4|GENE_START_CODON_c5_g1_i1_2_4|transcript|TRANSCRIPT_START_CODON_c5_g1_i1_2_4|protein_coding||c.-163C>T|||||163|WARNING_TRANSCRIPT_NO_START_CODON,A|downstream_gene_variant|MODIFIER|STOP_CODON_c5_g1_i1_437_439|GENE_STOP_CODON_c5_g1_i1_437_439|transcript|TRANSCRIPT_STOP_CODON_c5_g1_i1_437_439|protein_coding||c.*270C>T|||||270|WARNING_TRANSCRIPT_NO_START_CODON	GT:AD:DP:GQ:PL	./.	./.	./.	./.	1/1:0,2:2:6:89,6,0	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:1,0:1:3:0,3,46
c5_g1_i1	226	.	A	G	60.17	.**	

#is this 1) a known or real problem, 2) attribute of original haplotypecaller generated .vcf file, or 3) did I make a mistake when I ran the commands?
thanks,
Nate

**Comment by naterobinett** [comment]
formatting of github changed the text I entered. I entered: "ANN[*].ALLELE:" not  "ANN[].ALLELE:".

**Comment by naterobinett** [comment]
...I have also used the -s flag with many different delimiter types and it does not seem to affect the output at all.

**Comment by pcingola** [comment]
You are entering an incorrect sub-field name.
The sub-field name is "ALLELE" but you've entered "ALLELE:" (trailing colon)
When the sub-field name is entered correctly, the behaviour is as expected:

```
$ java -jar SnpSift.jar extractFields z.ann.vcf "ANN[*].ALLELE" "ANN[*].EFFECT" "ANN[*].IMPACT" "ANN[*].HGVS_P" 
ANN[*].ALLELE	ANN[*].EFFECT	ANN[*].IMPACT	ANN[*].HGVS_P
T	T	upstream_gene_variant	intron_variant	MODIFIER	MODIFIER	
T	T	T	frameshift_variant	structural_interaction_variant	structural_interaction_variant	HIGH	HIGH	HIGH	p.Lys228fs
```

If you add an incorrect trailing colon, the whole 'ANN' field is reported instead.
So the program works OK when the command line is entered correctly.
I'm puzzled on why it is not showing you an error message when you entered an incorrect sub-sield name. I'll take a look at it.

**Comment by pcingola** [comment]
Actually, it does show an error message:

```
$ java -jar SnpSift.jar extractFields z.ann.vcf "ANN[*].ALLELE:" 
line 1:13 no viable alternative at input '[*].ALLELE:'   <--- ERROR MESSAGE AT CHAR 13

ANN[*].ALLELE:
T|upstream_gene_variant|MODIFIER|EWSR1|EWSR1|transcript|NM_013986.3|protein_coding||c.-3118delA|||||2790|,T|intron_variant|MODIFIER|RHBDD3|RHBDD3|transcript|NM_001329536.1|protein_coding|3/6|c.148+260delT||||||
T|frameshift_variant|HIGH|NF2|NF2|transcript|NM_000268.3|protein_coding|8/16|c.683delA|p.Lys228fs|1126/6029|683/1788|228/595||INFO_REALIGN_3_PRIME,T|structural_interaction_variant|HIGH|NF2|NF2|interaction|1H4R:A_227-A_270:NM_000268.3|protein_coding|8/16|c.679delA||||||,T|structural_interaction_variant|HIGH|NF2|NF2|interaction|1H4R:B_227-B_270:NM_000268.3|protein_coding|8/16|c.679delA||||||
```
After the error message is shown, it recovers from whatever is correctly parsed in the expression. In this case is 'ANN[*]', thus it shows the whole ANN sub-fields.

Closing the issue, feel free to re-open if you want.

**Comment by naterobinett** [comment]
Thanks for getting back to me. I was puzzled by the :. it was included in an example so I included it. 

I will try to find that example.

thanks again,
