### ISSUE TITLE
Duplication symbolic call <DUP:TANDEM> <DUP> annotation woes

### ISSUE THREAD

**Issue by rysunder** [pcingola/SnpEff#171]
The following variant is incorrectly annotated.

- Manta Variant:
4   106196456   MantaDUP:TANDEM:1:207:207:1:3:0 T   \<DUP:TANDEM>    .   PASS    AF=0.109;END=106196652;SVLEN=196;SVTYPE=DUP;set=manta   PR:SR   1168,199:4321,475

- Annotation:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	11732872551_2011120_hus_submission
4	106196456	MantaDUP:TANDEM:1:207:207:1:3:0	T	\<DUP:TANDEM>	.	PASS	AF=0.109;END=106196652;SVLEN=196;SVTYPE=DUP;set=manta;EFF=intron_variant(MODIFIER|||n.318+58891_318+59086dup||TET2-AS1||NON_CODING|NR_126420.1|2|\<DUP:TANDEM>),intragenic_variant(MODIFIER|||n.||TET2||CODING|||\<DUP:TANDEM>)	PR:SR	1168,199:4321,475

- Command:
java -jar ~/SnpEff/snpEff/snpEff.jar eff -noStats -formatEff -hgvs -t hg19 duplication_testing.vcf

![screen shot 2017-06-05 at 11 01 46 am](https://cloud.githubusercontent.com/assets/17150925/26794529/3666515a-49df-11e7-84e9-15c1fac6bfc0.png)

The variant 100% overlaps an exon for transcript NM_001127208.2 (NM_001127208.2:c.4789_4985dup) as seen in the figure above.  The software appears to be mishandling the symbolic call "\<DUP:TANDEM>".

The most concerning issue is that the variant is 100% inside the exon for transcript NM_001127208.2, but the antisense RNA for transcript NR_126420.1 is prioritized.  TET2 is annotated, but without a transcript being associated with it.  

Additional Questions:  
	1.  What does the annotation contain a gene annotation (TET2) instead of a transcript annotation?  What does the gene annotation mean?
	2.  How does the software handle the symbolic calls "\<DUP>" and "\<DUP:TANDEM>"?

**Comment by pcingola** [comment]
Closing old issues.
