### ISSUE TITLE
Question: SnpEff spliceAnalysis

### ISSUE THREAD

**Issue by matthdsm** [pcingola/SnpEff#173]
Hi,

I'm interested in the experimental spliceAnalysis feature of SnpEff. Would it be possible to give a short summary of the output of this tool?
- Does this add annotations to the `<ANN>` field?
- Which fields does this add, and what do they mean?
- Is there a timeframe in which this feature could be considered 'production ready'

Thanks a lot!
M

**Comment by pcingola** [comment]
This analysis was created for a specific project but was discontinued long time ago.
