### ISSUE TITLE
SnpEff Error: Unkown IUB code for SNP '*'

### ISSUE THREAD

**Issue by TincySimon** [pcingola/SnpEff#174]
Hi,
According to your post 'Snpeff error on GATK-3.4-46 vcf with spanning deletions: issue #140 , the error related to the deletion code was fixed.
However, I recently ran the SnpEff on my GATK haplotypecaller GVcf file and I got the same error.
I couldn't understand exaclty how you fixed it. Could you help me figure it out?
-Tincy

**Comment by RamRS** [comment]
+1 - facing the exact same error.

**Comment by pcingola** [comment]
The problem was solved on June 2016, please update your version.
If you think this is still an issue, please send further information to replicate the error condition, here are some tip on how to correctly report a bug: http://snpeff.sourceforge.net/about.html#help
