### ISSUE TITLE
Possible regression for <INV> annotations in v4.3

### ISSUE THREAD

**Issue by brendanofallon** [pcingola/SnpEff#175]
When annotating a variant with the symbolic ALT <INV>, things appeared to work correctly in v4.2, but the same variant when annotated in 4.3p yields seemingly truncated output, as follows:

Input VCF:

    ##fileformat=VCFv4.1
    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
    18	48575723	.	C	<INV>	.	.	END=48575964`

SnpEff 4.2 output:

    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
    18	48575723	.	C	<INV>	.	.	END=48575964;ANN=<INV>|intron_variant|MODIFIER|SMAD4|SMAD4|transcript|NM_005359.5.1|protein_coding|4/11|c.454+29delCins<IAA>||||||,<INV>|intron_variant|MODIFIER|SMAD4|SMAD4|transcript|NM_005359.5.1|protein_coding|4/11|c.454+29delCins<ICA>||||||,<INV>|intron_variant|MODIFIER|SMAD4|SMAD4|transcript|NM_005359.5.1|protein_coding|4/11|c.454+29delCins<IGA>||||||,<INV>|intron_variant|MODIFIER|SMAD4|SMAD4|transcript|NM_005359.5.1|protein_coding|4/11|c.454+29delCins<ITA>||||||...
(I've truncated the output a little here for clarity)

SnpEff 4.3 output:

    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
    18	48575723	.	C	<INV>	.	.	END=48575964;ANN=<INV>|intragenic_variant|MODIFIER|SMAD4|SMAD4|gene_variant|SMAD4|||n.||||||
This seems a little broken and inconsistent - should there at least be a list of transcripts and their effects? Also the n. field isn't populated. 

Both are using the hg19 data.

**Comment by pcingola** [comment]
Closing old issues.
