### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by arthurmelobio** [pcingola/SnpEff#177]
Hi snpEff Team,

I have tried to functionally annotate SNPs between two close related wild wheat genomes. Trying to build my own database through the GFF file, I got the following error message:

`Error reading file '/home/arthur/Bioinfo_Softwares/snpEff/./data/Zavitan4B/genes.gff'
java.lang.StringIndexOutOfBoundsException: String index out of range: -2327
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:353)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.createSnpEffPredictor(SnpEffCmdBuild.java:118)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:362)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)`

The command line I'm using is:
`java -jar -Xmx4g snpEff.jar build -gff3 Zavitan4B`

and for sure I previously create the own directory on snpEff/data; moved the GFF (genes.gff) and FASTA (sequence.fa) within that and appropriatelly changed the snpEff.config.

Could you please help me to understand this error and fix it?

Thank you.

**Comment by Secretloong** [comment]
Me too. I found the same error. 

Then I found there is always an error by all the version 4.3 and 4.2. It seems new version could not identify the home-made GFF file very well. New snpEff always identified all genes as one gene, and reported "String index out of range" with so many contigs. But the version 4.1 worked well.

the gene identification error like below:
version 4.1l, it works well
`        Reading genes       :   Total: 0 Genes added.
        Reading transcripts :   Adding gene     ID: 'Gene_Noni_R000001' name: 'Gene_Noni_R000001'       Gene_C6974214:2-205
WARNING: Cannot find gene 'Gene_Noni_R000001'. Created gene 'Gene_Noni_R000001' for transcript 'Noni_R000001'. File '/hwfssz1/ST_DIVERSITY/F16ZQSB1SY2933/USER/fangqi/11
        Adding transcript :     ID: 'Noni_R000001'      Transcript_C6974214:2-205
        Adding gene     ID: 'Gene_Noni_R000002' name: 'Gene_Noni_R000002'       Gene_C6990220:1-216
WARNING: Cannot find gene 'Gene_Noni_R000002'. Created gene 'Gene_Noni_R000002' for transcript 'Noni_R000002'. File '/hwfssz1/ST_DIVERSITY/F16ZQSB1SY2933/USER/fangqi/11
        Adding transcript :     ID: 'Noni_R000002'      Transcript_C6990220:1-216
        Adding gene     ID: 'Gene_Noni_R000003' name: 'Gene_Noni_R000003'       Gene_C7007160:1-228
WARNING: Cannot find gene 'Gene_Noni_R000003'. Created gene 'Gene_Noni_R000003' for transcript 'Noni_R000003'. File '/hwfssz1/ST_DIVERSITY/F16ZQSB1SY2933/USER/fangqi/11
        Adding transcript :     ID: 'Noni_R000003'      Transcript_C7007160:1-228`

version 4.3(all), it would add all transcripts to the first scaffold or contig, then report "String index out of range" error
`        Adding gene     ID: 'null'      name: 'Noni_R000001'    Gene_C6974214:2-205
        Adding transcript :     ID: 'Noni_R000001'      Transcript_C6974214:2-205
        Adding transcript :     ID: 'Noni_R000002'      Transcript_C6974214:1-216
        Adding transcript :     ID: 'Noni_R000003'      Transcript_C6974214:1-228`

**Comment by pcingola** [comment]
Closing old issues.
