### ISSUE TITLE
pileup input no more?

### ISSUE THREAD

**Issue by devonorourke** [pcingola/SnpEff#185]
Hello Pablo (and team),
Thank you for maintaining such a wonderful SNP annotation program! I frequently use snpEff and SnpSift programs to manipulate .vcf files without issue, however I have a unique circumstance in which I'm required to use a .pileup file format for an unrelated analysis outside of your program (ie. I can't convert the pileup to .vcf and proceed as normal).  
I'd like to be able to use snpEff to annotate a .pileup file and noticed that the input argument `-i [format]` in the current version (4.3t) of snpEff no longer accepts the .pileup format, just .vcf and .bed files. I downloaded version 4.0, as according to the [older manual](http://snpeff.sourceforge.net/SnpEff_manual.version_4_0.html), that version would accept .pileup files. However, this generates an error message stating that my input format isn't recognized.  
For example:
```
java -jar /path.to.my/snpEff.jar eff -i pileup -o vcf -noStats Myoluc2.0.76 rsMYLU.pileup > rsMYLU.pileup.ann.vcf

Error        :	Unknown input file format 'PILEUP'
Command line :	SnpEff  -i pileup -o vcf -noStats Myoluc2.0.76 rsMYLU.pileup 

snpEff version SnpEff 4.0e (build 2014-09-13), by Pablo Cingolani
Usage: snpEff [eff] [options] genome_version [input_file]
variants_file                   : Default is STDIN

Options:
-chr <string>                   : Prepend 'string' to chromosome name (e.g. 'chr1' instead of '1'). Only on TXT output.
-classic                        : Use old style annotaions instead of Sequence Ontology and Hgvs.
-download                       : Download reference genome if not available. Default: true
-i <format>                     : Input format [ vcf, txt, pileup, bed ]. Default: VCF.
...{and more info}...
```
It [looks like](http://snpeff.sourceforge.net/features.html) pileup formats were accepted as far back as v1.9, the help menu in v4.0 seems to appear that pileup formats are accepted, so I'm not clear what else I could be doing wrong. It appears that pileup formats are still accepted in v.4.3t's [underlying java code](https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/SnpEff.java), but just not listed in the help menu?  

For what it's worth, I generated my pileup file using **samtools v1.6**; here's the command:
```
samtools mpileup \
--fasta-ref /path.to.my/mylu.fa \
--bam-list /path.to.my/rsMYLU_bamlist.txt \
--redo-BAQ --adjust-MQ 50 --min-MQ 20 --min-BQ 20 --ignore-overlaps \
--positions commonSites.txt > rsMYLU.pileup
```

And two more bits of information:
1) I've used that .pileup file to do further things outside of **snpEff** and things work fine; in other words, the .pileup file itself appears to be containing information encoded as expected.
2) As a sanity check, I did ultimately create a .vcf file using that same pileup pipeline, just adding in a `bcftools call` argument, then ran **snpEff** on that resulting. vcf file - and of course things worked fine!

So the two questions in a nutshell:
1) are .pileup formats still accepted in v4.3t, or just earlier versions (and if so, which ones work?)
2) is there something wrong with the argument I'm passing to the program that should be changed?

Thanks very much!

**Comment by pcingola** [comment]
Hi,
  Pileup is not a proper format for variants, the standard is to use VCF instead. Since it is not considered a good practice to use pileup for variant input files, the support has been removed.
  As you mentioned, you can easily use bcftools to create a VCF from pileup.
   Yours

    Pablo
