### ISSUE TITLE
dbNSFP read only error

### ISSUE THREAD

**Issue by davidhanna** [pcingola/SnpEff#186]
Hi,

We're using a read only file system for our references to prevent mucking around.  It looks like the SnpSift dbnsfp annotation creates a data_types file adjacent to the tabix indexed dbNSFP file when it can't find the file, which is fine behavior.  However, even when the file is present, it attempts to recreate the file, which on a RO volume results in this error:

2017-11-29T01:10:17.547Z Caused by: java.io.FileNotFoundException: /references/dbNSFP.txt.gz.data_types (Read-only file system)

Would it be possible to not write out this file, or alternatively, to give a warning when it wants to recreate the file but is unable?

Thanks,
David

**Comment by pcingola** [comment]
I'll take a look at it.

In the mean time: The dbNSFP.txt.gz.data_type file should only need to be written when
it is older than the main dbNSFP file. You can take a look at the timestamps.
If you think the file is OK you might use the 'touch' command to update the
timestamp (provided the file system is mounted as R/W somewhere).

**Comment by pcingola** [comment]
Closing old issues.
