### ISSUE TITLE
modified residue in intron?

### ISSUE THREAD

**Issue by dwaggott** [pcingola/SnpEff#192]
I'm trying to interpret the following variant. It looks like a modified residue but according to the transcript on ucsc it looks pretty deep in an intron on all transcripts. Any ideas on how I can dig into if this is real vs a database fluke?
   
```
  1  11
     2  18426354
     3  C
     4  CAAAAAAAAAAA
     5  .
     6  sequence_feature
     7  MODERATE
     8  LDHA
     9  modified-residue:phosphoserine
    10  20
    11  CAAAAAAAAAAA|sequence_feature|MODERATE|LDHA|ENSG00000134333|modified-residue:phosphoserine|ENST00000540430|protein_coding||c.798-642_798-641insAAAAAAAAAAA||||||
```

**Comment by pcingola** [comment]
You say you looked into UCSC, but the annotation shows ENSG00000134333, which is an ENSEMBL reference genome (you should probably look into ESNBL, instead of UCSC).

**Comment by melnel000** [comment]
I have the same issue with two intronic variants with ANN.IMPACT=MODERATE which have been annotated on RefSeq canonical transcripts as "modified-residue:phosphoserine" and "cross-link:Glycyl_lysine_isopeptide_(Lys-Gly)_(interchain_with_G-Cter_in_ubiquitin)" for the ANN.FEATURE. Is this a known bug?

**Comment by pcingola** [comment]
Closing old issues.

**Comment by misrak** [comment]
> CAAAAAAAAAAA

![image](https://user-images.githubusercontent.com/13136697/144387187-794d9f3f-37ce-431d-bcb4-c619e5af1ebe.png)


As you can see the variant is not in the coding part of the Ensembl transcript: ENST00000540430. Should we again filter for variants whose ANN[*].FEATURE == 'transcript' for coding variants?
