### ISSUE TITLE
Typo in downstream comment

### ISSUE THREAD

**Issue by acesnik** [pcingola/SnpEff#194]
Thanks for the great commenting throughout! Random typo: "no" should be "not" here, https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/interval/Downstream.java#L36

**Comment by acesnik** [comment]
"Is" to "Are" in https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/interval/Gene.java#L262

**Comment by acesnik** [comment]
"form" to "from" https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/vcf/VcfEntry.java#L211

**Comment by acesnik** [comment]
"genotpye" to "genotype" https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/vcf/VcfGenotype.java#L259

**Comment by acesnik** [comment]
`PedigreeEnrty` to `PedigreeEntry` in the file and filename https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/vcf/PedigreeEnrty.java

**Comment by pcingola** [comment]
Closing old issues.
