### ISSUE TITLE
chrM annotation error

### ISSUE THREAD

**Issue by jjfarrell** [pcingola/SnpEff#195]
When annotating a hg38 vcf, the chrM records are getting the following error: (ERROR_CHROMOSOME_NOT_FOUND).

 Is snpEff expecting a different contig name instead of chrM?  Any suggestions?

`chrM    15317   rs2853507       G       A       1792681.41      .       AC=22;AF=4.569e-03;AN=4815;BaseQRankSum=1.30;ClippingRankSum=0.00;DP=9092972;FS=0.000;MLEAC=22;MLEAF=4.569e-03;MQ=60.00;MQRankSum=0.00;QD=33.69;ReadPosRankSum=-1.650e01;SOR=0.674;ANN=A||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND;
`

**Comment by pkMyt1** [comment]
Look in your reference index file.  More than likely it is chrMT.  I have run into this.  Human is chrMT and mouse is chrM

**Comment by jjfarrell** [comment]
The GRCh38 reference uses chrM.  The snpEff program seems to be expecting something else.

 more GRCh38_full_analysis_set_plus_decoy_hla.fa.fai
chr1    248956422       112     70      71
chr2    242193529       252513167       70      71
chr3    198295559       498166716       70      71
chr4    190214555       699295181       70      71
chr5    181538259       892227221       70      71
chr6    170805979       1076358996      70      71
chr7    159345973       1249605173      70      71
chr8    145138636       1411227630      70      71
chr9    138394717       1558439788      70      71
chr10   133797422       1698811686      70      71
chr11   135086622       1834520613      70      71
chr12   133275309       1971537157      70      71
chr13   114364328       2106716512      70      71
chr14   107043718       2222714743      70      71
chr15   101991189       2331287770      70      71
chr16   90338345        2434736088      70      71
chr17   83257441        2526365093      70      71
chr18   80373285        2610812039      70      71
chr19   58617616        2692333639      70      71
chr20   64444167        2751788762      70      71
chr21   46709983        2817153685      70      71
chr22   50818468        2864531079      70      71
chrX    156040895       2916075638      70      71
chrY    57227415        3074345836      70      71
**chrM    16569   3132390908      70      71**

**Comment by pkMyt1** [comment]
You can edit that index file.  Changing chrM to chrMT should solve it.

**Comment by jjfarrell** [comment]
How?  
The snpEff GRCh38.86 database downloaded does not appear to include mitochondria bin file. It needs to be rebuilt. Probably resulted from a mismatch between chrM and MT among the files used to create the dictionary.

rw-r--r-- 1 farrell casa  1.7M Feb 18 15:50 sequence.Y.bin
-rw-r--r-- 1 farrell casa   17M Feb 18 15:50 sequence.X.bin
-rw-r--r-- 1 farrell casa  117K Feb 18 15:50 sequence.bin
-rw-r--r-- 1 farrell casa   17M Feb 18 15:50 sequence.9.bin
-rw-r--r-- 1 farrell casa   22M Feb 18 15:50 sequence.8.bin
-rw-r--r-- 1 farrell casa   25M Feb 18 15:50 sequence.7.bin
-rw-r--r-- 1 farrell casa   23M Feb 18 15:50 sequence.6.bin
-rw-r--r-- 1 farrell casa   26M Feb 18 15:50 sequence.5.bin
-rw-r--r-- 1 farrell casa   26M Feb 18 15:50 sequence.4.bin
-rw-r--r-- 1 farrell casa   33M Feb 18 15:50 sequence.3.bin
-rw-r--r-- 1 farrell casa   37M Feb 18 15:50 sequence.2.bin
-rw-r--r-- 1 farrell casa  6.2M Feb 18 15:50 sequence.22.bin
-rw-r--r-- 1 farrell casa  5.5M Feb 18 15:50 sequence.21.bin
-rw-r--r-- 1 farrell casa  9.0M Feb 18 15:50 sequence.20.bin
-rw-r--r-- 1 farrell casa   36M Feb 18 15:50 sequence.1.bin
-rw-r--r-- 1 farrell casa   10M Feb 18 15:50 sequence.19.bin
-rw-r--r-- 1 farrell casa   11M Feb 18 15:50 sequence.18.bin
-rw-r--r-- 1 farrell casa   15M Feb 18 15:50 sequence.17.bin
-rw-r--r-- 1 farrell casa   14M Feb 18 15:50 sequence.16.bin
-rw-r--r-- 1 farrell casa   16M Feb 18 15:50 sequence.15.bin
-rw-r--r-- 1 farrell casa   15M Feb 18 15:50 sequence.14.bin
-rw-r--r-- 1 farrell casa   12M Feb 18 15:50 sequence.13.bin
-rw-r--r-- 1 farrell casa   22M Feb 18 15:50 sequence.12.bin
-rw-r--r-- 1 farrell casa   21M Feb 18 15:50 sequence.11.bin
-rw-r--r-- 1 farrell casa   20M Feb 18 15:50 sequence.10.bin

**Comment by pkMyt1** [comment]
I need to dig through my notes.  My GRCh38  fai file looks like this.  I remember having to use a text editor to change the M to MT.  I may have also removed the "chr" from each.

1	248956422	56	60	61
10	133797422	253105810	60	61
11	135086622	389133248	60	61
12	133275309	526471372	60	61
13	114364328	661967995	60	61
14	107043718	778238454	60	61
15	101991189	887066292	60	61
16	90338345	990757392	60	61
17	83257441	1082601434	60	61
18	80373285	1167246557	60	61
19	58617616	1248959454	60	61
2	242193529	1308554087	60	61
20	64444167	1554784232	60	61
21	46709983	1620302526	60	61
22	50818468	1667791066	60	61
3	198295559	1719456565	60	61
4	190214555	1921057106	60	61
5	181538259	2114441960	60	61
6	170805979	2299005913	60	61
7	159345973	2472658715	60	61
8	145138636	2634660511	60	61
9	138394717	2782218181	60	61
MT	16569	2922919531	60	61
X	156040895	2922936433	60	61
Y	57227415	3081578071	60	61

**Comment by marina-manrique** [comment]
In this line I've been having also issues annotating `chrM` variants with SnpEff. I am using `snpeff-4.3T` and the database version `GRCh37.p13.RefSeq`

and I'm getting `ERROR_OUT_OF_CHROMOSOME_RANGE` errors, even though the variant position is within chromosome length range

```bash 
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Sample
chrM    240     .       C       T       72815.03        VQSRTrancheSNP99.95to100.00     AC=2;AF=1.00;AN=2;BaseQRankSum=4.72;DP=2459;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.00;MQRankSum=0.00;QD=34.12;ReadPosRankSum=2.35;SOR=0.128;VQSLOD=-3.161e+03;culprit=DP;ANN=T||MODIFIER|||||||||||||ERROR_OUT_OF_CHROMOSOME_RANGE  GT:AD:DP:GQ:PL  1/1:2,2132:2134:99:72829,6399,0
```

any ideas of how could I fix this?

**Comment by pcingola** [comment]
Closing old issues.
