### ISSUE TITLE
Fail to print 1/10000 variants using snpeff annotate on gnomAD database

### ISSUE THREAD

**Issue by borisevichdi** [pcingola/SnpEff#198]
Running snpEff against gnomAD vcfs, I encountered rare problem with several particular variants (about 1 out of each 10 000).

To reproduce:
Code crashes on line:
https://github.com/pcingola/SnpEff/blob/da076a9031e71f7d68764930f78e20793fe5b011/src/main/java/org/snpeff/vcf/VcfEntry.java#L634
with NullPointerException during processing of specific position, f.ex.:
`chr10: 46550598 C>T`
from gnomAD GRCh38 vcf
`ftp://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype/gnomad.exomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz`

As a result, this variant from initial vcf file is totally skipped. To clarify, it is not just printed un-annotated, but it is completely missing from output vcf file (f.ex. in my case I have 5004 variants in input file and 5002 in output).

All failing variants, interestingly enough, are cases that have 3 different alt alleles in gnomad database.

Full log:
[tmp.txt](https://github.com/pcingola/SnpEff/files/1810562/tmp.txt)

**Comment by pcingola** [comment]
I'm taking a look at this. Thank you for the heads up!

**Comment by pcingola** [comment]
Could you share the input file and the full command line you are using? I haven't been able to replicate the error condition.

**Comment by borisevichdi** [comment]
Command is:
```
java -jar SnpSift.jar annotate -noId -tabix -info AF -name gnomad. gnomad.exomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz tmp.vcf > tmp2.vcf
```

Input/output vcf files are:
[vcf.zip](https://github.com/pcingola/SnpEff/files/1826366/vcf.zip)
I removed header from files, and they have technically malformed header right now, but the error is present if the header is correct.

Database file is available by the link above.

Java version:
```
java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

OS version (RHEL 7.4 server):
```
uname -a
Linux hulk 3.10.0-693.1.1.el7.x86_64 #1 SMP Thu Aug 3 08:15:31 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pcingola** [comment]
Closing old issues.
