### ISSUE TITLE
Use snpeff database from designated locations

### ISSUE THREAD

**Issue by xiaolicbs** [pcingola/SnpEff#199]
I am wondering if there's an option to specify path to snpeff database when running annotation (rather than reading from default directory structure from the jar of snpeff). When many people are using the same jar for analysis, reading from the default directory structure might lead to many people to modify same file, including config, fasta and gff files. This will cause some analyses to be unreproducible.

**Comment by pcingola** [comment]
By default, SnpEff uses your home directory, so this shouldn't be a major issue:
Here is the relevant snpEff.config part:

```
#---
# Databases are stored here
# E.g.: Information for 'hg19' is stored in data.dir/hg19/
#
# You can use tilde ('~') as first character to refer to your home directory. 
# Also, a non-absolute path will be relative to config's file dir
# 
#---
data.dir = ./data/
```

Alternatively, you can use different config files with `-c` command line option.
Finally, there is a generic `-configOption`, here is the relevant line from the help page:
```
Generic options:
	-c , -config                 : Specify config file
	-configOption name=value     : Override a config file option
```
