### ISSUE TITLE
Exporting AA and HGVS together

### ISSUE THREAD

**Issue by yarongolan** [pcingola/SnpEff#203]
When using SnpEff, we found that we would like to have both the HGVS and AA provided in the annotation. At the moment, you can only choose one or the other. However, there are many cases in which, especially in systems used by multiple users, each may want to see different information - some may be interested in AA and some in HGVS, but with a consistent pipeline, it's easier if both are exported at the same time.

**Comment by pcingola** [comment]
Closing old issues.
