### ISSUE TITLE
Multiple genes separated by either "&" or "-"

### ISSUE THREAD

**Issue by garrettjstevens** [pcingola/SnpEff#204]
Hello there,

I was wondering why sometimes multiple genes are separated by "&" and sometimes by "-". For example, this is for GRCh37 chrom 22, pos 23412532, ref TGGCGGCGGGCGGCGGGCGGCG, alt T:
```
T|bidirectional_gene_fusion|HIGH|GNAZ&RTDR1|ENSG00000128266&ENSG00000100218|gene_variant|ENSG00000100218|||n.23412553_23412533delCGCCGCCCGCCGCCCGCCGCC||||||
```
Genes GNAZ and RTDR1 are separated by "&"

And this is for GRCh37 chrom 22, pos 16293170, ref GC, alt G:
```
G|intergenic_region|MODIFIER|POTEH-MED15P7|ENSG00000198062-ENSG00000234381|intergenic_region|ENSG00000198062-ENSG00000234381|||n.16293171delC||||||
```
Genes POTEH and MED15P7 are separated by "-"

It seems to make more sense to use "&" to separate genes because "-" can occur in the gene name, which can result in some ambiguous outputs (i.e. whether the "-" is part of the gene name or is indicating that it is between two genes).

Thanks!

**Comment by pcingola** [comment]
Closing old issues.
