### ISSUE TITLE
Different exons at same chromosome position

### ISSUE THREAD

**Issue by chaozhongyinxiang** [pcingola/SnpEff#207]
Hello, we encounter the following situation using SnpEff to annotate variants:

Two variants, the first one an indel, the second one a SNV, called at the same position, but they are annotated with different exons: exon 3 vs 9 (see bold). We checked out database file, these two exons are not overlapping with each other. In this case, they should both be within exon 3.

2	47601106	.	TG	CA	16955.5	.	AC=0,2;AD=0,348,426;AF=1.0;AN=2;DP=775;SR=0.76,0.72;set=FB;ANN=CA|missense_variant|MODERATE|EPCAM|EPCAM|transcript|NM_002354.2|protein_coding|**9/9**|c.344_345delTGinsCA|p.Met115Thr|702/1718|344/945|115/314||	GT:AF:DP	1/1:1.0:775
2	47601106	.	TG	CG	16955.5	.	AC=0,2;AD=0,348,426;AF=1.0;AN=2;DP=775;SR=0.76,0.72;set=FB;ANN=CG|missense_variant|MODERATE|EPCAM|EPCAM|transcript|NM_002354.2|protein_coding|**3/9**|c.344T>C|p.Met115Thr|702/1718|344/945|115/314||	GT:AF:DP	1/1:1.0:775

Thanks a lot!

Chao

**Comment by pcingola** [comment]
Closing old issues.
