### ISSUE TITLE
databate build with custom GTF?

### ISSUE THREAD

**Issue by Seb-Leb** [pcingola/SnpEff#211]
I am trying to build a new snpEff database using the top level DNA fasta from Ensembl (83) and a custom annotation gtf file in which I include extra CDSs, other than the reference ones (see attached file for the first 1k lines).
Can I even do this?
When I run the whole gtf it stays stuck at the splicing characterization step 1. When I run only the top 1000 lines, it completes with 100% error and results in the db dump I've also included here.
I'd appreciate any nudge in the right direction.
Thanks!

[test_snpEff_db.zip](https://github.com/pcingola/SnpEff/files/2236096/test_snpEff_db.zip)

**Comment by acesnik** [comment]
I have done this successfully in the past. (I'm not on the development team, just another user here.)

It looks like your GTF file isn't sorted, so you might want to sort it and try again.

You also might want to post the command you're using to build the database.

Best,

AC

**Comment by Seb-Leb** [comment]
thank you for answering! that was a great tip, I didn't think of sorting the GTF..
it still takes a very long time at the exon splicing characterization step but I've successfully generated a db for chr 12 in a few minutes. There are a lot of warnings but at least I have something to work with now. Did you have many warnings when you did it? Did you include more than one start & stop codon per transcript?
thanks again.

**Comment by pcingola** [comment]
Closing old issues.
