### ISSUE TITLE
ann -fastaProt - question symbol

### ISSUE THREAD

**Issue by ArtemPankin** [pcingola/SnpEff#215]
Hello,

Some of the amino acid sequences extracted using "ann -fastaProt" option contain question (?) marks even in the reference sequence. I could find anywhere how to interprete those and will appreciate any hints.

Thank you
Artem

**Comment by acesnik** [comment]
Hi there, another user here.

The question mark is used when the codon isn't in the codon table. See here: https://github.com/pcingola/SnpEff/blob/87976d2c63fc2590408cc40f41b96818079324b9/src/main/java/org/snpeff/codons/CodonTable.java#L101 

I see it a lot when there are frameshifts.


Cheers,

AC

**Comment by acesnik** [comment]
Also, many reference gene models have some weird annotations in there. I've seen quite a few coding sequence annotations that end in partial codons (i.e. dividing the CDS length by 3 leaves a remainder).

**Comment by ArtemPankin** [comment]
Anthony thanks for the hints. I found that the reference genome has "N"s at these positions.

**Comment by pcingola** [comment]
Closing old issues.
