### ISSUE TITLE
Annotations of multi allelics

### ISSUE THREAD

**Issue by sachalau** [pcingola/SnpEff#216]
Hello,

I am currently using annovar to annotate my vcf but I am willing to change to snpEff, in particular because of its ability to annotate multi sample vcf. However, I would like to discuss its behaviour with multi allelics. Currently it does something like this : 

```
##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">
1	934476	.	T	A,G ANN=A|missense_variant|MODERATE|24149|24149|transcript|NM_001142467|
protein_coding|3/3|c.707A>T|p.Gln236Leu|906/1038|707/744|236/247||,G|missense_variant|MODERATE|24149|24149|transcript|NM_001142467|pro
tein_coding|3/3|c.707A>C|p.Gln236Pro|906/1038|707/744|236/247||,A|missense_variant|MODERATE|24149|24149|transcript|NM_021170|protein_c
oding|4/4|c.629A>T|p.Gln210Leu|828/962|629/666|210/221||,G|missense_variant|MODERATE|24149|24149|transcript|NM_021170|protein_coding|4
/4|c.629A>C|p.Gln210Pro|828/962|629/666|210/221||
```

where you can have any number of entry for ANN (number=.) as each annotation of each transcript is encoded as a separate entry. However, this becomes inconvinient when you try to extract a single sample from this multi sample big vcf. Ideally, one would like that the only annotation to be carried ove would be the one corresponding to the allele of the sample. This would require the annotation to look something like this:

```
##INFO=<ID=ANN,Number=**A**,Type=String,Description="Functional annotations: 'Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">
1	934476	.	T	A,G ANN=missense_variant|MODERATE|24149|24149|transcript|NM_001142467|
protein_coding|3/3|c.707A>T|p.Gln236Leu|906/1038|707/744|236/247||**&**|missense_variant|MODERATE|24149|24149|transcript|NM_021170|protein_c
oding|4/4|c.629A>T|p.Gln210Leu|828/962|629/666|210/221||,missense_variant|MODERATE|24149|24149|transcript|NM_001142467|pro
tein_coding|3/3|c.707A>C|p.Gln236Pro|906/1038|707/744|236/247||**&**|missense_variant|MODERATE|24149|24149|transcript|NM_021170|protein_coding|4
/4|c.629A>C|p.Gln210Pro|828/962|629/666|210/221||
```

The number of ANN entries would be limited to the number of alleles, and the annotation corresponding to each transcript would be all encoded in the same entry and separated by a symbol to be determined (I chose **&**, but I think it is used in other field of your annotation, it could be **|&|** instead). That way I think the ANN field would be a better fit to the VCF format in general.

I could write a quick and dirty script to modify the annotation that is given out by snpEff to fit my needs, however this is usually a bad idea. Thus I was wondering,

- if you had already considered using this kind of  annotation instead of the current one and if yes, why did you discard it ?
- if you would be interested that I open a PR from your repo and that I start working on this change ? At the end the user would get an additional option to chose this new annotation style if he wishes.

Tell me what you think,

**Comment by pcingola** [comment]
Closing old issues.
