### ISSUE TITLE
error when annotate inserting variations

### ISSUE THREAD

**Issue by MayZhang314159** [pcingola/SnpEff#217]
I use annotate a vcf which is custom database. I found for insert mutation, I cann't get right annotation.
java -jar snpEff.jar -dataDir /data/bioxFlow/annox/snpEff/data/ -geneId -canon -v GRCh37.p13.RefSeq -interval /data2/test_snp/snpeff/civic.vcf /data2/test_snp/snpeff/civic.vcf -stats /data2/test_snp/civic.snpeff_summary.html -csvStats /data2/test_snp/civic.csv> /data2/test_snp/civic_snpEff.vcf

input:
##fileformat=VCFv4.2
##assembly=grch37
##SOURCE_CIVIC=20180508
##INFO=<ID=CIVIC_ID,Number=.,Type=String,Description="Identifier for evidence item of clinical biomarker in CIViC database">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
2	29445271	.	G	GCGT	.	PASS	CIVIC_ID=EID444,EID1347,EID1349,EID1348
database (civic.vcf) :
##fileformat=VCFv4.2
##assembly=grch37
##SOURCE_CIVIC=20180508
##INFO=<ID=CIVIC_ID,Number=.,Type=String,Description="Identifier for evidence item of clinical biomarker in CIViC database">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
2	29445271	CM128668	G	GCGT	.	PASS	CIVIC_ID=EID444,EID1347,EID1349,EID1348

result:
2	29445271	CM128668	G	GCGT	.	PASS	CIVIC_ID=EID444,EID1347,EID1349,EID1348;ANN=GCGT|conservative_inframe_insertion&splice_region_variant|MODERATE|ALK|ALK|transcript|NM_004304.4|protein_coding|22/29|c.3451_3453dupACG|p.Thr1151dup|4405/6265|3453/4863|1151/1620||

There is no custom annotation. I thought the result should be like this:
2	29445271	.	G	GCGT	.	PASS	CIVIC_ID=EID444,EID1347,EID1349,EID1348;ANN=GCGT|conservative_inframe_insertion&splice_region_variant|MODERATE|ALK|ALK|transcript|NM_004304.4|protein_coding|22/29|c.3451_3453dupACG|p.Thr1151dup|4405/6265|3453/4863|1151/1620||,
GCGT|custom|MODIFIER|||CUSTOM&civic|CM128668|||n.29445271GCGT>T||||||

look forward to your reply

**Comment by pcingola** [comment]
Closing old issues.
