### ISSUE TITLE
No mitochondrion chromosome found

### ISSUE THREAD

**Issue by sr-c** [pcingola/SnpEff#220]
Hello,

When I tried to building snpEff database for a new genome,  I got: 

> WARNING                    : No mitochondrion chromosome found

But I am concerned about the SNPs in the mitochondrion. 

Should I add the mitochondrion chromosome into the reference genome sequence? If so, how could I define the mitochondrion chromosome in the GTF/GFF files ?

**Comment by meixilin** [comment]
Hi, 

Did you fix this issue before? I am having the same issue and from the debugging log, snpEff is reading the transcript and everything well. 

Thanks a lot!

**Comment by pcingola** [comment]
Closing old issues.

**Comment by swiddison** [comment]
I have found a solution which is to prefix the contig name with MT. The warning then goes away.
