### ISSUE TITLE
represent ribosomal slippage in gtf

### ISSUE THREAD

**Issue by Jane2010** [pcingola/SnpEff#225]
A issue I am having is regarding those transcripts with ribosomal slippage. It seems that the SnpEff is not considering the slippage when annotating “protein_effect”, which would affect the calls for “so_terms” and “locus_effect”. 

Here are some examples:

1. An example with +1 frameshift is NM_004152.3. Here is the sequence around the slippage:

TCC[T]GAT  -  where T is skipped in translation, and after translating “TCC”, the next codon is “GAT”. 

If slippage is not considered, “TGA” would be considered a stop codon, and that is what SnpEff gives. For example, the variant 
NM_004152.3:c.205T>A gets the protein_effect, "p.Ter69Argext*?, and So term: stop_loss.

2. NM_001172437.2 has a -1 frameshift at c.1447, resulting the p.396 becoming an K, instead of N, and all the subsequently AAs shift accordingly. 
For the variant NM_001172437.2:c.2324G>A, the protein_effect is p.Arg775His. This is consistent with the case where no -1 frameshift occurred. 
In fact, any variants overlapping and after c.1447 would have the wrong protein effect. 

I attached the genes.gtf and protein.fa I use for building the database, and the vcf for the two examples. 
[slippage.zip](https://github.com/pcingola/SnpEff/files/2846185/slippage.zip)

Could you advice the right way to represent such ribosomal slippage in the gtf?

**Comment by pcingola** [comment]
Use the GenBank format instead.
You can use the `./scripts/buildDbNcbi.sh` script to download and build:

```
cd ~/snpEff
./scripts/buildDbNcbi.sh NM_004152.3
```
