### ISSUE TITLE
SnpEff build unable to read protein sequence

### ISSUE THREAD

**Issue by arupgsh** [pcingola/SnpEff#226]
While building a SnpEff database using NCBI Genebank file the tool is unable to read the protein sequence details mentioned in the file.

Command line:
`bash ./scripts/buildDbNcbi.sh NC_012920.1`

Output:

> Downloading genome NC_012920.1
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 69919    0 69919    0     0  29390      0 --:--:--  0:00:02 --:--:-- 29377
> 00:00:00	SnpEff version SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
> 00:00:00	Command: 'build'
> 00:00:00	Building database for 'NC_012920.1'
> 00:00:00	Reading configuration file 'snpEff.config'. Genome: 'NC_012920.1'
> 00:00:00	Reading config file: /Toolbox/snpEff/snpEff.config
> 00:00:00	done
> Chromosome: 'NC_012920'	length: 16569
> 
> 	Create exons from CDS (if needed): .............
> 	Exons created for 13 transcripts.
> 
> 	Deleting redundant exons (if needed): 
> 		Total transcripts with deleted exons: 0
> 
> 	Collapsing zero length introns (if needed): 
> 		Total collapsed transcripts: 0
> 		Adding genomic sequences to exons: 	Done (13 sequences added, 0 ignored).
> 
> 	Adjusting transcripts: 
> 	Adjusting genes: 
> 	Adjusting chromosomes lengths: 
> 	Ranking exons: 
> 	Create UTRs from CDS (if needed): 
> 	Remove empty chromosomes: 
> 
> 	Marking as 'coding' from CDS information: 
> 	Done: 0 transcripts marked
> 00:00:00	Caracterizing exons by splicing (stage 1) : 
> 	
> 00:00:00	Caracterizing exons by splicing (stage 2) : 
> 	00:00:00	done.
> 00:00:00	[Optional] Rare amino acid annotations
> 00:00:00	Done.
> 00:00:00	Protein check file: '/Toolbox/snpEff/./data/NC_012920.1/genes.gbk'
> 
> 00:00:00	Checking database using protein sequences
> 00:00:00	Comparing Proteins...
> 	Labels:
> 		'+' : OK
> 		'.' : Missing
> 		'*' : Error
> 	*************
> 
> 	Protein check:	NC_012920.1	OK: 0	Not found: 0	Errors: 13	Error percentage: 100.0%
> 00:00:00	Saving database
> 00:00:00	[Optional] Reading regulation elements: GFF
> 00:00:00	Warning: Cannot read optional regulation file '/Toolbox/snpEff/./data/NC_012920.1/regulation.gff', nothing done.
> 00:00:00	[Optional] Reading regulation elements: BED 
> 00:00:00	Cannot find optional regulation dir '/Toolbox/snpEff/./data/NC_012920.1/regulation.bed/', nothing done.
> 00:00:00	[Optional] Reading motifs: GFF
> 00:00:00	Warning: Cannot open PWMs file /Toolbox/snpEff/./data/NC_012920.1/pwms.bin. Nothing done
> 00:00:00	Done
> 00:00:00	Logging
> 00:00:01	Checking for updates...
> 00:00:02	Done.
>

**Comment by pcingola** [comment]
Closing old issues.

**Comment by yirenheihei** [comment]
I have the same question,how can i solve this ?

**Comment by pcingola** [comment]
Please open a new issue with specific details on what is not working for you.
