### ISSUE TITLE
wrong protein_effect for variants in the same codon as a reference disagree position

### ISSUE THREAD

**Issue by Jane2010** [pcingola/SnpEff#227]
genomic build: GRCh37
variant in question:
12|121437384|C|A

snpeff returns the correct hgvs_c = NM_000545.5:c.1722C>A

Yet because there is a nearby base that is different between the transcript and the genomic sequence, it returns the wrong protein_effect:

At c.1770, the genomic sequence, it is an A, whereas in NM_000545.5, it is a G. 

The codon spans from 1720-1772. So the ref-disagree position is the first base in the codon, whereas the variant is the third base. The correct p. should use the transcript base, G, thus the original codon is GGC, and the variant codon is GGA, both coding for Glycine. So hgvs_p should be NP_000536.5:p.Gly574=. snpeff returns “protein_effect”: “p.Ser574Arg”, apparently using the genomic 1720 base.

**Comment by pcingola** [comment]
Closing old issues.
