### ISSUE TITLE
Annotate the release 20130502 data from 1000 genomes project

### ISSUE THREAD

**Issue by NamLQ** [pcingola/SnpEff#228]
Hello,

I downloaded the 1KG data from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/. Then I used snpEff to annotate the variants from the data with two reference genomes GRCh37 and hg19. Here are the two statistics files:

[Results from GRCh37.75 reference genome](https://www.dropbox.com/s/ogt2vzrgi38xc3e/WG_GRCh37.75.html?dl=0)

[Results from hg19 reference genome](https://www.dropbox.com/s/5rjtbahpzd63fsk/WG_hg19.html?dl=0)

As you can see, the "Number of effects by type and region" parts are very different.

Could you tell me which reference genome should I used? 

I made Google search and found out this interesting post: https://www.biostars.org/p/335605/. In that link, the author used the file downloaded from http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz as the reference genome. Should I use that file to build the reference database for the annotation?

Thank you very much!

**Comment by pcingola** [comment]
Closing old issues.
