### ISSUE TITLE
 WARNING_TRANSCRIPT_NO_START_CODON occurring for gene with start codon?

### ISSUE THREAD

**Issue by katiesaund** [pcingola/SnpEff#231]
Certain variants are labeled with "WARNING_TRANSCRIPT_NO_START_CODON" even though the gene in the .gbf starts with a start codon. Any idea why this error message is occurring? 

Warning: 
`gi|126697566|ref|NC_009089.1| 4012	.	T	C	222.0	PASS_filter2	AC1=2;AF1=1;DP=149;DP4=0,0,79,53;FQ=-281.989;MQ=60;MQ0F=0;MQSB=1;SGB=-0.693147;VDB=0.13574;ANN=C|synonymous_variant|LOW|recF|CD630_00040|transcript|CD630_00040|protein_coding|1/1|c.984T>C|p.Asn328Asn|984/1116|984/1116|328/371||WARNING_TRANSCRIPT_NO_START_CODON	GT:PL	1/1:255,255,0`

Original gene file used to make database: 

`gene            3029..4144
                     /gene="recF"
                     /locus_tag="CD630_00040"
     CDS             3029..4144
                     /gene="recF"
                     /locus_tag="CD630_00040"
                     /old_locus_tag="CD0004"
                     /codon_start=1
                     /transl_table=11
                     /product="DNA replication and repair protein RecF"
                     /protein_id="CAJ66818.1"
                     /db_xref="EnsemblGenomes-Gn:CD630_00040"
                     /db_xref="EnsemblGenomes-Tr:CAJ66818"
                     /db_xref="GOA:Q18C86"
                     /db_xref="InterPro:IPR001238"
                     /db_xref="InterPro:IPR003395"
                     /db_xref="InterPro:IPR018078"
                     /db_xref="InterPro:IPR027417"
                     /translation="MKLKSLQLVNFRNYKKLHLEFNGKVNLLVGKNGQGKTNIVESIY
                     MLSFGKSFRTNKDKEMVRFNSENLYIGGSFSKYNKYSLIELIIGKDKKGIRINKVPLQ
                     KIQELLGNLNVVIFSPEDLRLVKEGPKERRAFIDKEISQIIPKYYKYLTNYNKTLSQR
                     SRVLKNIHVDEALLDVYDDTLAKYGSYIYILRRDFIKKIANISENMHMNLTNGVERLS
                     IRYKNQINITDEDTIDTVYNKFLAKLSSNRPNDIESKTTRYGIHKDDLNIFINDLDAR
                     LFGSQGQQRTASISLKLSEIELIKNEVEEYPVLILDDVFSELDEARQKLLVNNLSNVQ
                     MFITSAEVSHKKIFDEKNVTIFNIENGDVISIENGGN"
     misc_feature    3116..3139
                     /gene="recF"
                     /locus_tag="CD630_00040"
                     /note="PS00017 ATP/GTP-binding site motif A (P-loop)."
     misc_feature    3359..3436
                     /gene="recF"
                     /locus_tag="CD630_00040"
                     /note="PS00617 RecF protein signature 1."
     misc_feature    3953..4006
                     /gene="recF"
                     /locus_tag="CD630_00040"
                     /note="PS00618 RecF protein signature 2."`

Any insight would be appreciated, Thanks!

**Comment by pcingola** [comment]
Closing old issues.
