### ISSUE TITLE
SnpEFF with whole genome multisample vcf file

### ISSUE THREAD

**Issue by Fazulur** [pcingola/SnpEff#232]
Dear Team,

SnpEff is running very slow with large vcf which has more than 5000 samples & size of vcf file is around 3TB. I used -t & -noStats options while running snpeff. Still it is very slow.
Here is the command

java -XX:+UseParallelGC -XX:ParallelGCThreads=32 -Xmx128g -Djava.io.tmpdir=tmp -jar $SNPEFFHOME/snpEff.jar -v -t -noStats -c $SNPEFFHOME/snpEff.config GRCh38.86 test.vcf.gz | gzip -c > test-snpeff.vcf.gz

Is there any way I can submit snpeff in parallel to execute nodes instead of running in one machine. 

Please suggest me how can I proceed further with large vcf files.

Thanks In Advance
Fazulur Rehaman

**Comment by pcingola** [comment]
Closing old issues.
