### ISSUE TITLE
protein_protein_contact not annotated with AA change

### ISSUE THREAD

**Issue by etabari** [pcingola/SnpEff#233]
I have cases where a missense AA change gets lost because it's reported protein_protein_contact.

Example: 
`GRCh38, chr17:7673803, c.817C>T, p.R273C` [See in Cosmic](https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=10659) 

gets annotated to 
`ANN=A|protein_protein_contact|HIGH|TP53|ENSG00000141510|interaction|ENST00000269305:2AC0_A:133_273|protein_coding|8/11|c.817C>T||||||`

**Comment by pcingola** [comment]
Closing old issues.

**Comment by pcingola** [comment]
Closing old issues.

**Comment by pcingola** [comment]
Closing old issues.
