### ISSUE TITLE
Compound substitution not correctly annotated in HGVS.P

### ISSUE THREAD

**Issue by CarlosMackintosh** [pcingola/SnpEff#234]
Hi,

When annotating compound substitutions spanning several codons, the HGVS.c is correctly annotated by snpEff but not the HGVS.p. This is an example record of what I get:

Example variant as appears in the vcf (coding it here as "chr | start | ref | alt"):
```
chr4 | 55593604 | GGAA | GTCC 
```

snpEff HGVS annotation ("gene | transcript_id | HGVS.c | HGVS.p"):
```
KIT | NM_000222.2 | c.1671_1673delGAAinsTCC | p.TrpLys557CysPro
```
Correct HGVS.p annotation would be (checked with LUMC's Mutalyzer):
```
p.Trp557_Lys558delinsCysPro
```

I am seeing this in several other instances of compound substitutions in a vcf with common hotspots in cancer. I am using the latest release of snpEff.

Thank you in advance

**Comment by pcingola** [comment]
Closing old issues.

**Comment by schorlton** [comment]
Thanks for the great tool. Could I suggest prioritizing/revisiting this? It is a major issue for parsing variant changes with external tools, and following HGVS standard would greatly help.

There are at least 3 independent tickets filed for this same issue:
- https://github.com/pcingola/SnpEff/issues/435
- https://github.com/pcingola/SnpEff/issues/234
- https://github.com/pcingola/SnpEff/issues/371

Thanks for your consideration!
