### ISSUE TITLE
Where can we download the latest version of SnpEff

### ISSUE THREAD

**Issue by dulunar** [pcingola/SnpEff#235]
I am using version 4.3;

But when I use it, I get a message from it as follow:
java -jar snpEff.jar GRCh37.75 test.vcf > test_snpeff_grch37.vcf

NEW VERSION!
        There is a new SnpEff version available:
                Version: 4.4
                Release date: 2019-01-26
                Download URL: http://sourceforge.net/projects/snpeff/files/snpEff_latest_core.zip

But I downloaded this version from the URL, I found that the version still is SnpEff version SnpEff 4.3t (build 2017-11-24 10:18), same with I used.

So where can I download the latest version? Thanks.

**Comment by rlblad** [comment]
Same problem here!

**Comment by splaisan** [comment]
idem here

**Comment by pcingola** [comment]
Solved long time ago.

https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip

Please reopen if this is still not working for you.

**Comment by splaisan** [comment]
Thanks Pablo, now worked with

```
java -jar ./snpEff.jar -version
SnpEff	5.0	2020-08-09
```
