### ISSUE TITLE
Get the rs ids using Chromosome coordinates

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [pcingola/SnpEff#246]
Hello

I have: 
CHR START END Effect_Allele Ref_Allele 

I want: 
CHR START END Effect_Allele Ref_Allele rs_ID

Thanks in advance
M

**Comment by pcingola** [comment]
You can use SnpSift and annotate using dbSnp for that.

Please take a look at the _"SnpSift annotate"_ documentation, it's the first example:
   https://pcingola.github.io/SnpEff/SnpSift.html#annotate
