### ISSUE TITLE
GRCh38 database for snpEff 4.5covid19

### ISSUE THREAD

**Issue by spz1st** [pcingola/SnpEff#247]
I installed snpEff 4.5covid19 and downloaded snpEff_v4_5covid19_core.zip.  According to the config file snpEff.config in the zip file, the GRCh38 database for this version of snpEff is GRCh38.99.  But when I tried to run snpEff or download the database, I got the following error message.

    00:00:00        ERROR while connecting to 
    http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_GRCh38.99.zip
    java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
    ...

If I specified a different database, say GRCh38.86, I'd get the following error message.

    java.lang.RuntimeException: Property: 'GRCh38.86.genome' not found
    ...

**Comment by pcingola** [comment]
Please try SnpEff 5.0, it should solve the problem.

https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip

Closing the issue, please reopen if the problem persists in SnpEff v5.0
