### ISSUE TITLE
snpEff annotated vcf file shows no ANN field post analysis

### ISSUE THREAD

**Issue by rtyb91** [pcingola/SnpEff#249]
I am annotating a list of variants from the canine whole genome sequencings post filtering to retrieve significant candidate genes via SnpEff against the **CanFam3.1.99** database.

I ran the command 
` java -Xmx12g -jar snpEff.jar CanFam3.1.99 homo.vcf > homo.ann.vcf `

I am currently using  SnpEff 5.0

I will attach my vcf file as a reference
[Homo.vcf.zip](https://github.com/pcingola/SnpEff/files/5139520/Homo.vcf.zip)

The analysis actually produced a vcd file as well as the results of SnpEff with the genes and their effects, but without the chromosome number attached with them. It would be impossible for us to find out which variant to send for Sanger sequencing without the chromosome number intact. On top of that the annotated vcd did not have an ANN field either. 
[snpEff_genes.txt](https://github.com/pcingola/SnpEff/files/5139529/snpEff_genes.txt)

Is there something I missed in my command which resulted in the absence of the ANN field?

Many thanks.

**Comment by pcingola** [comment]
The detailed results for each variant are in the VCF file.
The `genes.txt` is just a summary, as such not suitable for what I understand you want to do. Please use the VCF file instead.
