### ISSUE TITLE
Running SnpSift error. dbNSFP4.1a.txt.gz

### ISSUE THREAD

**Issue by dietmarfdz** [pcingola/SnpEff#253]
Following your workflow to annotate a vcf with the dbNSFPdatabase I download the file dbNSFP4.1a.txt.gz (also the tbi) from your link. 

When running the command to annotate:

```bash
java -jar SnpSift.jar dbnsfp -v -db ~/software/snpeff/snpEff_latest_core_sep2020/snpEff/data/ dbNSFP4.1a.txt.gz Giab_100cut.vcf > Giab_100_snpsift.vcf
```
I obtain the following:
```
00:00:00	SnpSift version 5.0 (build 2020-08-09 21:24), by Pablo Cingolani
00:00:00	Command: 'dbnsfp'
00:00:00	Reading configuration file 'snpEff.config'
00:00:00	done
00:00:00	Annotating:	Input file : 'Giab_100cut.vcf'	Database file : '.../dbNSFP4.1a.txt.gz'
00:00:00	Loading data types from file '.../dbNSFP4.1a.txt.gz.data_types'
00:00:00	Data types cache file '.../dbNSFP4.1a.txt.gz.data_types' not found
00:00:00	Guessing data types for file '.../dbNSFP4.1a.txt.gz'
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Error: Invalid header line!
	Line:	1	65565	A	C	M	L	.	1	65565	1	55428	1	OR4F5 ....
...
at org.snpsift.SnpSiftCmdDbNsfp.annotate(SnpSiftCmdDbNsfp.java:135)
	at org.snpsift.SnpSiftCmdDbNsfp.run(SnpSiftCmdDbNsfp.java:532)
	at org.snpsift.SnpSiftCmdDbNsfp.run(SnpSiftCmdDbNsfp.java:511)
	at org.snpsift.SnpSift.run(SnpSift.java:588)
	at org.snpsift.SnpSift.main(SnpSift.java:76)

```
There is no header line in this version dbNSFP4.1a.txt.gz

I downloaded the version 2.9 and the file has a header but it seems that in version 4.1.a it has been omitted and therefore the software is complaining. Do we know if the header is somewhere else?

**Comment by pcingola** [comment]
Fixed, it should work OK now. You should re-download the latest dbNSFP file, apologies for the inconvenience.

**Comment by ISonets** [comment]
Greetings! Not the same error, but strongly related to this database. I am neither able to download this file directly via link you provided in the manual (connection refused after ~4gb downloading, ```wget -c``` and other methods (such as curl) do not solve the problem) nor downloading the database automatically when trying to annotate (according to the manual, "Note that the first time you run the command, it will attempt to download the dbNSFP database"). It just doesn't work. I tried to specify that I need to download( so I typed either ```download=true``` or  ```-download true``` , as also specifying genome version in a similar manner(```-g=hg38``` or ```-g hg38```). None of them seem to work. Please help! Thanks in advance!
