### ISSUE TITLE
Running SnpEff on MacOS using Anaconda

### ISSUE THREAD

**Issue by Suuusj** [pcingola/SnpEff#256]
Hi all,

I am kinda new to this field, so my apologies in advance. 

I am trying to run SnpEff on my Mac using Anaconda. I think I managed to install the package (conda install -c bioconda snpeff), now I try to run the tool which is where I am stuck.

What would be the command line code that should be used to run the tool, and which input does it require? Only a VCF file? 

I expect it to be something like; 
snpeff - input.vcf -output.vcf ?

Thanks in advance for helping out

Suzanne

**Comment by pcingola** [comment]
There are plenty of examples and guidance in the documentation:
  https://pcingola.github.io/SnpEff/ss_introduction/

Also there is a specific "examples" section in SnpEff's website:
  https://pcingola.github.io/SnpEff/examples/
