### ISSUE TITLE
SNPEff database for SARS-CoV-2

### ISSUE THREAD

**Issue by rdeborja** [pcingola/SnpEff#264]
Can you add genome MN908947.3 on the list of available genomes for SARS-CoV-2?  A number of us are using the ARTIC reference genome (https://github.com/artic-network/artic-ncov2019/blob/master/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta) which uses "MN908947.3" instead of "NC_045512.2".

**Comment by pcingola** [comment]
You can quickly add it by running the `buildDbNcbi.sh` script (in `snpEff/scripts` directory):

```
$ ./scripts/buildDbNcbi.sh MN908947.3
Downloading genome MN908947.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56807    0 56807    0     0   179k      0 --:--:-- --:--:-- --:--:--  178k
00:00:00	SnpEff version SnpEff 5.0b (build 2020-10-16 14:33), by Pablo Cingolani
00:00:00	Command: 'build'
00:00:00	Building database for 'MN908947.3'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'MN908947.3'
00:00:00	Reading config file: /Users/kqrw311/workspace/SnpEff/config/snpEff.config
00:00:00	done
Chromosome: 'MN908947.3'	length: 29903

	Create exons from CDS (if needed): ...........
	Exons created for 10 transcripts.

	Deleting redundant exons (if needed):
		Total transcripts with deleted exons: 0

	Collapsing zero length introns (if needed):
		Total collapsed transcripts: 0
		Adding genomic sequences to exons: 	Done (11 sequences added, 0 ignored).

	Adjusting transcripts:
	Adjusting genes:
	Adjusting chromosomes lengths:
	Ranking exons:
	Create UTRs from CDS (if needed):
	Remove empty chromosomes:

	Marking as 'coding' from CDS information:
	Done: 0 transcripts marked
00:00:00	Caracterizing exons by splicing (stage 1) :

00:00:00	Caracterizing exons by splicing (stage 2) :
	00:00:00	done.
00:00:00	[Optional] Rare amino acid annotations
00:00:00	Warning: Cannot read optional protein sequence file '/Users/kqrw311/workspace/SnpEff/config/./data/MN908947.3/protein.fa', nothing done.
00:00:00	Protein check file: '/Users/kqrw311/workspace/SnpEff/config/./data/MN908947.3/genes.gbk'

00:00:00	Checking database using protein sequences
00:00:00	Comparing Proteins...
	Labels:
		'+' : OK
		'.' : Missing
		'*' : Error
	++++++++++

	Protein check:	MN908947.3	OK: 10	Not found: 0	Errors: 0	Error percentage: 0.0%
00:00:00	Saving database
00:00:00	[Optional] Reading regulation elements: GFF
00:00:00	Warning: Cannot read optional regulation file '/Users/kqrw311/workspace/SnpEff/config/./data/MN908947.3/regulation.gff', nothing done.
00:00:00	[Optional] Reading regulation elements: BED
00:00:00	Cannot find optional regulation dir '/Users/kqrw311/workspace/SnpEff/config/./data/MN908947.3/regulation.bed/', nothing done.
00:00:00	[Optional] Reading motifs: GFF
00:00:00	Warning: Cannot open PWMs file /Users/kqrw311/workspace/SnpEff/config/./data/MN908947.3/pwms.bin. Nothing done
00:00:00	Done
00:00:00	Logging
00:00:01	Checking for updates...
00:00:02	Done.
```

**Comment by rdeborja** [comment]
Just noticed that the database was added, closing issue.

**Comment by rdeborja** [comment]
Previously database 'MN908947.3' was made available with snpEff upon request, however several colleagues have encountered issues recently.  I used a fresh account and encountered a problem where the database is listed in the snpEff.config file, but the database was not available for use:

```
$ snpEff MN908947.3 POS-twist4-10-2-20201125-run-48-v3_S102.pass.vcf.gz
00:00:00	ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_MN908947.3.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
```

**Comment by rdeborja** [comment]
@pcingola is it still possible to add MN908947.3 as a downloadable reference?  We've started using SNPEff as a standard for annotating our SARS-CoV-2 variants.  While the build suggestion you made works, when users of `ncov-tools` attempt to update the conda package, several errors appear and requires an uninstall and re-install of the package followed by a manual build of the reference again.

**Comment by pcingola** [comment]
Sorry to ask, I'm not an expert on this: Isn't NC_045512.2 a more complete version of MN908947?
I think it's because NC_045512.2 has the "mature peptides" annotations missing in MN908947.3

From NC_045512.2 Genbank's file:
```
COMMENT     REVIEWED REFSEQ: This record has been curated by NCBI staff. The
            reference sequence is identical to MN908947.
 ...
```

I don't mind adding MN908947.3 if it's an improvement in some way, but it seems to be a less annotated GenBank file to the exact same genome.
Let me know what you think.

**Comment by rdeborja** [comment]
No apologies necessary as I’m no expert either.  The ARTIC protocol (https://artic.network/ncov-2019) uses MN908947.3 as it’s reference and basis for primer design which all of Canada is currently using.  The results in us adopting MN908947.3 for all our sequencing analysis.

**Comment by pcingola** [comment]
Done:
- Created database for MN908947.3
- Upload the database
- Updated snpEff.config
- Updated main SnpEff package

If you use the latest SnpEff [distribution](https://datasetsnpeff.blob.core.windows.net/dataset/versions/snpEff_latest_core.zip?sv=2019-10-10&st=2020-09-01T00%3A00%3A00Z&se=2050-09-01T00%3A00%3A00Z&si=prod&sr=c&sig=isafOa9tGnYBAvsXFUMDGMTbsG2z%2FShaihzp7JE5dHw%3D), you can download the database using a standard `download` command:

```
$ java -jar snpEff.jar download -v MN908947.3
00:00:00	SnpEff version SnpEff 5.0d (build 2021-01-28 11:39), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'MN908947.3'
...
00:00:01	Donwload finished. Total 11139 bytes.
...
00:00:02	Done.
```

Enjoy!
