### ISSUE TITLE
cannot download protocols.zip

### ISSUE THREAD

**Issue by dorks81** [pcingola/SnpEff#270]
Hi,

I would like to work through your examples but I am unable to retrieve the protocols.zip file. Below is my terminal output for the curl command. I would appreciate your help with retrieving the protocols.zip file.

Cheers,

curl -v -L https://snpeff.blob.core.windows.net/files/protocols.zip
*   Trying 20.150.39.132...
* TCP_NODELAY set
* Connected to snpeff.blob.core.windows.net (20.150.39.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.blob.core.windows.net
*  start date: Nov 15 00:00:00 2020 GMT
*  expire date: Nov 15 00:00:00 2021 GMT
*  subjectAltName: host "snpeff.blob.core.windows.net" matched cert's "*.blob.core.windows.net"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft RSA TLS CA 02
*  SSL certificate verify ok.
> GET /files/protocols.zip HTTP/1.1
> Host: snpeff.blob.core.windows.net
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 The specified resource does not exist.
< Content-Length: 223
< Content-Type: application/xml
< Server: Blob Service Version 1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: 166ddc81-c01e-001a-089e-bd0b43000000
< Date: Wed, 18 Nov 2020 11:35:28 GMT
< 
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:166ddc81-c01e-001a-089e-bd0b43000000
* Connection #0 to host snpeff.blob.core.windows.net left intact

**Comment by SteampunkIslande** [comment]
Hello ! I'm having the exact same issue right now, I think the file doesn't exist anymore...
