### ISSUE TITLE
Spelling in the output snpEff dump txt file

### ISSUE THREAD

**Issue by meixilin** [pcingola/SnpEff#271]
Hi, 

I have a small suggestion regarding the `dump` option (e.g. `java -Xmx4g -jar snpEff.jar dump -v -txt GRCh37.70 > GRCh37.70.txt`). The output txt header is like this: 

```
chr	start	end	strand	type	id	geneName	geneId	numberOfTranscripts	canonicalTranscriptLength	transcriptId	cdsLength	numerOfExons	exonRank	exonSpliceType
```

Maybe the  `numerOfExons` should be `numberOfExons`? 

Thank you again for creating this software!

**Comment by pcingola** [comment]
Thank you for the heads up! Fixed
