### ISSUE TITLE
ERROR_CHROMOSOME_NOT_FOUND      12

### ISSUE THREAD

**Issue by AroobAlhumaidy** [pcingola/SnpEff#273]
Hello, 
I am using SnpEff to annotate SARS-CoV2 samples, the input is sample.vcf, reference used for mapping and variant calling is NC_045512.2

#First i downloaded the reference: java -jar snpEff.jar download NC_045512.2 
$ java -jar snpEff.jar download NC_045512.2

#Second i run the annotation code: 
java -jar PATH/snpEff.jar -c PATH/snpEff.config -v NC_045512.2  sample.vcf > OUTPUT_4.EFF.vcf  

the output I got is: 
00:00:00        SnpEff version SnpEff 5.0 (build 2020-10-04 16:02), by Pablo Cingolani
00:00:00        Command: 'ann'
00:00:00        Reading configuration file '/mnt/e/Bioinformatics/tools/snpeff/snpEff/snpEff.config'. Genome: 'NC_045512.2'
00:00:00        Reading config file: /mnt/e/Bioinformatics/tools/snpeff/snpEff/snpEff.config
00:00:00        done
00:00:00        Reading database for genome version 'NC_045512.2' from file '/mnt/e/Bioinformatics/tools/snpeff/snpEff/./data/NC_045512.2/snpEffectPredictor.bin' (this might take a while)
00:00:00        done
00:00:00        Loading Motifs and PWMs
00:00:00        Building interval forest
00:00:00        done.
00:00:00        Genome stats :
#-----------------------------------------------
# Genome name                : 'COVID19 Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1'
# Genome version             : 'NC_045512.2'
# Genome ID                  : 'NC_045512.2[0]'
# Has protein coding info    : true
# Has Tr. Support Level info : true
# Genes                      : 11
# Protein coding genes       : 11
#-----------------------------------------------
# Transcripts                : 38
# Avg. transcripts per gene  : 3.45
# TSL transcripts            : 0
#-----------------------------------------------
# Checked transcripts        : 
#               AA sequences :     12 ( 31.58% )
#              DNA sequences :      0 ( 0.00% )
#-----------------------------------------------
# Protein coding transcripts : 38
#              Length errors :      0 ( 0.00% )
#  STOP codons in CDS errors :      0 ( 0.00% )
#         START codon errors :     24 ( 63.16% )
#        STOP codon warnings :     26 ( 68.42% )
#              UTR sequences :      0 ( 0.00% )
#               Total Errors :     24 ( 63.16% )
# WARNING                    : No protein coding transcript has UTR
#-----------------------------------------------
# Cds                        : 40
# Exons                      : 40
# Exons with sequence        : 40
# Exons without sequence     : 0
# Avg. exons per transcript  : 1.05
#-----------------------------------------------
# Number of chromosomes      : 1
# Chromosomes                : Format 'chromo_name size codon_table'
#               'NC_045512.2'   29903   Standard
#-----------------------------------------------

00:00:00        Predicting variants

ERRORS: Some errors were detected
Error type      Number of errors
ERROR_CHROMOSOME_NOT_FOUND      12

00:00:00        Creating summary file: snpEff_summary.html
00:00:00        Creating genes file: snpEff_genes.txt
00:00:00        done.
00:00:00        Logging
00:00:01        Checking for updates...
00:00:04        Done.

what do you this is the issue? 

Thanks 
[snpEff_genes.txt](https://github.com/pcingola/SnpEff/files/5588678/snpEff_genes.txt)

**Comment by pcingola** [comment]
This link explains the issue and how to solve it:

https://github.com/pcingola/SnpEff/wiki/ERROR_CHROMOSOME_NOT_FOUND
