### ISSUE TITLE
Please consider tagging version v4_5covid19

### ISSUE THREAD

**Issue by pgrt** [pcingola/SnpEff#274]
Hi,

I am working on the Debian packaging of SnpEff, inside Debian Med team.

On your website, I saw you had a special release for Covid19, with label v4_5covid19.
Would you mind tagging it in Github, provided that you find it fit for release? As our release watching system follows tags, we could consistently get and package it, which would be great for our users and other projects.

To be more precise: last tagged version includes akka, which is not packaged in Debian, and I saw you dropped it out recently. We would thus be interested in packaging a recent release, without akka.

Thanks a lot for your consideration,
Pierre Gruet

**Comment by pcingola** [comment]
SnpEff v5.0 includes all the SARS genomes.
You should download the latest version from SnpEff's download link (see web page here: https://pcingola.github.io/SnpEff/)

I'm also trying to drop akka, I've just never had time to do it.
