### ISSUE TITLE
No white-space, semi-colons, or equals-signs are permitted in INFO field values

### ISSUE THREAD

**Issue by puva** [pcingola/SnpEff#279]
Dear SnpEff developer,
when annotating a VCF with ID from dbSNP153 several variants are removed from the output file.
- Number of SNP in.vcf: 1715464
- Number of SNP out.vcf: 1650186

`SnpSift annotate -id dbSNP153.vcf.gz in.vcf > out.vcf `

`java.lang.RuntimeException: No white-space, semi-colons, or equals-signs are permitted in INFO field values. Name:"CLNHGVS" Value:"NC_000001.11:g.114716123=,NC_000001.11:g.114716123C>A,NC_000001.11:g.114716123C>G,NC_000001.11:g.114716123C>T"
	at org.snpeff.vcf.VcfEntry.addInfo(VcfEntry.java:263)
	at org.snpsift.annotate.AnnotateVcfDb.annotateInfo(AnnotateVcfDb.java:161)
	at org.snpsift.annotate.AnnotateVcfDb.annotate(AnnotateVcfDb.java:105)
	at org.snpsift.SnpSiftCmdAnnotate.annotate(SnpSiftCmdAnnotate.java:128)
	at org.snpsift.SnpSiftCmdAnnotate.annotate(SnpSiftCmdAnnotate.java:90)
	at org.snpsift.SnpSiftCmdAnnotate.run(SnpSiftCmdAnnotate.java:410)
	at org.snpsift.SnpSiftCmdAnnotate.run(SnpSiftCmdAnnotate.java:397)
	at org.snpsift.SnpSift.run(SnpSift.java:588)
	at org.snpsift.SnpSift.main(SnpSift.java:76)
...
`
dbSNP was downloaded from https://ftp.ncbi.nih.gov/snp/redesign/latest_release/VCF/GCF_000001405.38.gz

**Comment by pcingola** [comment]
Apologies, but I haven't been able to reproduce the error.

Could you please provide:
1. The full SnpSift command line
2. Attach an example of the input VCF file. No need to attach the whole VCF file, just a few lines that cause the error condition should be enough.

**Comment by pcingola** [comment]
Please reopen when you can provide information

**Comment by puva** [comment]
Sorry for the late reply.
Here is the command line, using snpsift 4.3.1t (bioconda)
`SnpSift annotate -id dbSNP153_small.vcf test.small.vcf > bug.vcf`
The error message is:
```
java.lang.RuntimeException: No white-space, semi-colons, or equals-signs are permitted in INFO field values. Name:"CLNHGVS" Value:"NC_000001.11:g.930248=,NC_000001.11:g.930248G>A"
	at org.snpeff.vcf.VcfEntry.addInfo(VcfEntry.java:263)
	at org.snpsift.annotate.AnnotateVcfDb.annotateInfo(AnnotateVcfDb.java:161)
	at org.snpsift.annotate.AnnotateVcfDb.annotate(AnnotateVcfDb.java:105)
	at org.snpsift.SnpSiftCmdAnnotate.annotate(SnpSiftCmdAnnotate.java:128)
	at org.snpsift.SnpSiftCmdAnnotate.annotate(SnpSiftCmdAnnotate.java:90)
	at org.snpsift.SnpSiftCmdAnnotate.run(SnpSiftCmdAnnotate.java:410)
	at org.snpsift.SnpSiftCmdAnnotate.run(SnpSiftCmdAnnotate.java:397)
	at org.snpsift.SnpSift.run(SnpSift.java:588)
	at org.snpsift.SnpSift.main(SnpSift.java:76)
```
[Here](https://github.com/pcingola/SnpEff/files/5996596/bug.tar.gz) is the file to reproduce the error. Includes:
- dbSNP153_small.vcf: a subset of dbSNP153
- test.small.vcf: 3 variants (the first w/o entry in dbSNP, the second causing the bug, the third present in dbSNP)
- bug.vcf: 2 variants: the second variant has disappeared, the first and third are annotated/not annotated as expected

**Comment by puva** [comment]
> Please reopen when you can provide information

@pcingola I didn't find how to reopen this closed issue. Should I open a new one and reference this?

**Comment by pcingola** [comment]
I've looked into this and it is OK for SnpEff to throw the error because the input VCF file is invalid.

As the error message says, your  VCF file is corrupted due to illegal characters in the INFO field value:
```
$ grep 930248 dbSNP153_small.vcf | cut -f 8 | tr ';' '\n' | grep ^CLNHGVS
CLNHGVS=NC_000001.11:g.930248=,NC_000001.11:g.930248G>A
#                                                           ^ The equal sign is an illegal character in an INFO field 
```
This clearly has an equal sign (`=`) in the INFO field value, which is illegal.

Please take a look at the VCF specification, page 5, definition of an INFO field:

    https://samtools.github.io/hts-specs/VCFv4.2.pdf

> INFO - additional information: (String, **no whitespace, semicolons, or equals-signs permitted; commas** are
> permitted only as delimiters for lists of values) INFO fields are encoded as a semicolon-separated series of short
> keys with optional values in the format: <key>=<data>[,data]. If no keys are present, the missing value must
> be used. Arbitrary keys are permitted, although the following sub-fields are reserved (albeit optional):

So the error message is correct. You need to fix the input VCF file.

I'll try to make SnpEff/SnpSift emit a warning instead of an error in future versions (honestly, I'm not sure if allowing people to shoot themselves in the foot is a good idea).

**Comment by pcingola** [comment]
Try version 5.0e, it should solve the issue (I've just released it a minute ago):
```
$ grep -v "^#" test.small.vcf| wc -l
       3
(snpEff) /Users/kqrw311/snpEff/bug$ grep -v "^#" bug.vcf| wc -l
       3
```
The number variant of lines is the same in both files

The output:
```
(snpEff) /Users/kqrw311/snpEff/bug$ tail -n 3 bug.vcf
chr1	930181	.	G	T	673.11	PASS	BaseQRankSum=-0.189;DP=3454;ExcessHet=3.0103;FS=2.131;InbreedingCoeff=-0.0053;MQ=60;MQRankSum=0;QD=9.9;ReadPosRankSum=-2.264;SOR=1.047;VQSLOD=19.94;culprit=MQRankSum;AF=0.005319;MLEAC=1;MLEAF=0.005319;AN=188;AC=1;Cases_ALL=0,0,0;Controls_ALL=0,1,1;CC_TREND_ALL=4.283e-01;CC_GENO_ALL=NaN;CC_ALL_ALL=6.170e-01;CC_DOM_ALL=6.170e-01;CC_REC_ALL=1.000e+00
chr1	930248	rs41285790	G	A	21857.6	PASS	BaseQRankSum=-1;DB;DP=5501;ExcessHet=3.0519;FS=4.396;InbreedingCoeff=-0.0096;MQ=60;MQRankSum=0;QD=11.15;ReadPosRankSum=0;SOR=0.41;VQSLOD=29.55;culprit=ReadPosRankSum;AF=0.0388;MLEAC=1;MLEAF=0.007246;AN=772;AC=11;Cases_ALL=1,4,6;Controls_ALL=0,5,5;CC_TREND_ALL=5.242e-01;CC_GENO_ALL=5.324e-01;CC_ALL_ALL=3.481e-01;CC_DOM_ALL=4.774e-01;CC_REC_ALL=4.430e-01;CLNACC=.,RCV000971841.1;CLNDISDB=.,MedGen:CN517202;CLNDN=.,not_provided;CLNHGVS=NC_000001.11:g.930248=,NC_000001.11:g.930248G>A;CLNORIGIN=.,1;CLNREVSTAT=.,single;CLNSIG=.,3;FREQ=1000Genomes:0.9972,0.002796|ALSPAC:0.9948,0.005189|Estonian:0.9993,0.0006696|ExAC:0.9938,0.006218|GnomAD:0.9973,0.002675|GnomAD_exomes:0.9964,0.003583|GoESP:0.9965,0.003465|GoNL:0.993,0.007014|MGP:0.9869,0.01311|PAGE_STUDY:0.997,0.003026|Qatari:0.9907,0.009259|SGDP_PRJ:0.5,0.5|TOPMED:0.9962,0.003847|TWINSUK:0.9968,0.003236|dbGaP_PopFreq:0.9938,0.006183;GENEINFO=SAMD11:148398;GNO;NSM;RS=41285790;SSR=0;VC=SNV;dbSNPBuildID=127
chr1	930314	rs9988179	C	T	2430.11	PASS	BaseQRankSum=0.365;DB;DP=3614;ExcessHet=3.0103;FS=1.07;InbreedingCoeff=-0.0053;MQ=60;MQRankSum=0;POSITIVE_TRAIN_SITE;QD=11.74;ReadPosRankSum=-0.916;SOR=0.643;VQSLOD=22.52;culprit=MQRankSum;AF=0.005319;MLEAC=1;MLEAF=0.005319;AN=188;AC=1;Cases_ALL=0,0,0;Controls_ALL=0,1,1;CC_TREND_ALL=4.283e-01;CC_GENO_ALL=NaN;CC_ALL_ALL=6.170e-01;CC_DOM_ALL=6.170e-01;CC_REC_ALL=1.000e+00;COMMON;FREQ=1000Genomes:0.9475,.,0.05252|ALSPAC:0.999,.,0.001038|Estonian:0.9951,.,0.004911|ExAC:0.9619,.,0.0381|GnomAD_exomes:0.9711,.,0.02893|GoESP:0.9927,.,0.007318|KOREAN:0.858,.,0.142|MGP:0.9963,.,0.003745|NorthernSweden:0.9933,.,0.006667|PAGE_STUDY:0.9419,.,0.05809|Qatari:0.9907,.,0.009259|SGDP_PRJ:0.4153,.,0.5847|Siberian:0.5,.,0.5|TOPMED:0.9771,.,0.02286|TWINSUK:0.9995,.,0.0005394|Vietnamese:0.9049,.,0.09508|dbGaP_PopFreq:0.9935,.,0.006468;GENEINFO=SAMD11:148398;GNO;NSM;RS=9988179;SSR=0;VC=SNV;dbSNPBuildID=119
```

**Comment by puva** [comment]
Great, thank you. It looks fine now.
I've just tested on a large VCF:
2481447 input variants
2481447 output variants
