### ISSUE TITLE
Download option a bit buggy

### ISSUE THREAD

**Issue by marrip** [pcingola/SnpEff#287]
Hey,

I am new to SnpEff and not sure what this is causing. I experience some problems when downloading a database via the `download` option. I am running:

```
java -jar snpEff.jar download GRCh38.99
```

The problem is I do not get any output, error messages or anything so I cannot really attach that here. It just starts and nothing really happens. I checked if any files were downloaded and found a new folder in data with the name of the database containing some `bin` files. But after a number of them were downloaded it kind of stops I think (as I said I do not get any kind of error or other output). I tried this on a Mac with `openjdk 12.0.2` and `SnpEff 5.0c`. I also tried in a ubuntu docker container with `openjdk 11.0.9.1` and the same version of SnpEff. Another thing I experienced was that the download did not even start when my workdir was not the unzipped `snpeff` directory. Is it only possible to download databases to the `snpeff`? If yes, maybe you could provide an option to download it to the workdir or an indicated path instead? I finally downloaded the database using `wget` - maybe this could be in the docs as well if it isn't yet?

Greetings from Sweden, Martin

**Comment by pcingola** [comment]
Try using the verbose command-line option `-v` to see more messages:
```
java -jar snpEff.jar download -v GRCh38.99
```

Also, I've updated the proxy capabilities in the latest version SnpEff 5.0d. If your network requires a proxy, then upgrading to this version might help.

If you have the ZIP database downloaded by `wget`, then it's just a matter of unzipping it to the right place. For instance in this case, the "*.bin" files should be `snpEff/data/GRCh38.99` (assuming  `snpEff` is the directory where you installed SnpEff and have the default `data` path in `snpEff.config`)

**Comment by pcingola** [comment]
Closing, feel free to reopen.
