### ISSUE TITLE
SnpEff running too long (>3 weeks, still running) for the "build" command

### ISSUE THREAD

**Issue by catxujian1984** [pcingola/SnpEff#291]
I tried to build a database using my own genome (1.4Gb) and gff files, but it has been running for 3 weeks with no sign to stop.
May I ask for your suggestions, and thanks so much for your effort on developing the software.

**Comment by catxujian1984** [comment]
I tried snpEff4.1 with the command "-t“, and the run finished in a short time. But no bin file was generated.
Besides, I noticed the database for common carp already existed in the default database list, but it did not work for my vcf files. May I ask about the genome information used for generating carp database~

**Comment by pcingola** [comment]
SnpEff runs within minutes. Something is wrong, probably with your data, but as you did not share any information it's impossible to guess.

Here are some guidelines on how to ask for help and the minimal
information needed for an initial assessment of the issue:

   https://pcingola.github.io/SnpEff/about/#asking-for-help

**Comment by catxujian1984** [comment]
Sorry for the incompleteness of my question.
I tried Version4.1 and it worked well.


Thanks so much.


Best wishes,
Jian Xu






发件人："Pablo Cingolani" <notifications@github.com>
发送日期：2021-01-28 19:10:54
收件人：pcingola/SnpEff <SnpEff@noreply.github.com>
抄送人：catxujian1984 <xuj@cafs.ac.cn>,Author <author@noreply.github.com>
主题：Re: [pcingola/SnpEff] SnpEff running too long (>3 weeks, still running) for the "build" command (#291)


Closing due to missing minimal information. Please feel free to reopen.
