### ISSUE TITLE
Add harmonizome in SnpSift geneSet documentation

### ISSUE THREAD

**Issue by dridk** [pcingola/SnpEff#293]
[Harmonizome](https://maayanlab.cloud/Harmonizome/resource/Human+Phenotype+Ontology) is a good plateform to download GMT file from differents ontology. I suggest to add a reference to SnpSift GeneSets documentation. 

For instance, for HPO, https://maayanlab.cloud/Harmonizome/dataset/HPO+Gene-Disease+Associations , the GMT file is downloadable from gene set library

**Comment by pcingola** [comment]
I'll take a look at your suggestion. Thank you.
