### ISSUE TITLE
Build database without protein sequence or CDS information

### ISSUE THREAD

**Issue by Gayathri142** [pcingola/SnpEff#295]
We're using SnpEff for predicting the distribution of variants using a VCF from a SNP calling pipeline. We're building a new database using our internal reference genome and gtf. However, we do not have protein/CDS information.

After running SnpEff ann, we get a 'no protein coding transcripts found' warning - which is expected as did not provide that information. My question is, how does SnpEff predict the different class and impact of variants in the absence of a protein/CDS file? Does it take into account the standard codon table and then make predictions?

Thank you for your help and I look forward to your reply.
Gayathri

**Comment by pcingola** [comment]
The GTF has the gene / transcript coordinates. That's enough for SnpEff to build the database.
The protein and cds fasta files are just used for checking (many times there are errors in the GTF files).
