### ISSUE TITLE
Please consider adding copyright notice and license file in the source

### ISSUE THREAD

**Issue by pgrt** [pcingola/SnpEff#296]
Hi,

In Debian we are very much willing to package SnpEff, as many other wanted software depend on it.

Yet, the last release (v4.3t) is missing copyright header in all .java files and also a file at the root with the license. This proper copyrighting would ensure the feasibility of the packaging from our side.

Could you maybe please consider a v4.3u release identical to v4.3t with copyright headers and a license file at the root? That would also be useful for the current development tree and for the upcoming other releases.

If I can help with this, please just say.

In any case, warm thanks for considering my issue,
Best,
Pierre

**Comment by pcingola** [comment]
Added license file at root

https://github.com/pcingola/SnpEff/blob/master/LICENSE.md

I'll make sure the file it is bundled in the download package from 5.0 onwards and referenced in the documentation.

**Comment by pgrt** [comment]
Thanks a lot!

Cheers,
Pierre
