### ISSUE TITLE
Annotated as a different gene?

### ISSUE THREAD

**Issue by bhywong** [pcingola/SnpEff#299]
Hi,

Not sure if I have done anything wrong...I used snpeff to annotate the vcf but found that it gives me different gene names than what it supposed to be.

e.g. ch2 174341924 should be Gnas but it annotates as Gm20721
chr5 150557026 should be Brca2 but was annotated as Gm42529

Hugo_Symbol | Entrez_Gene_Id | Center | NCBI_Build | Chromosome | Start_Position | End_Position 
Gm20721 | ENSMUSG00000090625 | IMB | GRCm38 | 2 | 174341924 | 174341924 
Gm42529 | ENSMUSG00000106764 | IMB | GRCm38 | 5 | 150557026 | 150557026

The data I have is mouse DNA aligned to GRCm38.p6 and the for annotation I used: 

```
-jar ${snpeff} ann -v \
-stats sample.snpeff.html GRCm38.99 \
sample.vcf > sample.snpeff.vcf
```

**Comment by pcingola** [comment]
SnpEff annotates all transcripts and genes affected by a variant.

For instance, a variant at chr2: 174341924 affects both Gm20721 and Gnas:

http://nov2020.archive.ensembl.org/Mus_musculus/Gene/Summary?db=core;g=ENSMUSG00000090625;r=2:174330319-174346712;t=ENSMUST00000168292

so SnpEff would provide both annotations.

I hope this clarifies.
Closing the issue, feel free to reopen.
