### ISSUE TITLE
what happens when SnpEff is run with -o gatk?

### ISSUE THREAD

**Issue by lassancejm** [pcingola/SnpEff#301]
Hi, 

My understanding is that when snpEff is used with `-o gatk`, snpEff only reports the effect having the highest impact, something based on what the GATK team implemented. 

My question is how is this ranking/filtering implemented in snpEff? Is there a way to filter an annotated vcf produced using the default settings to mimic this behavior after the annotation is done? I am asking because using the gatk-like output not only means that the highest impact is reported, but also EFF fields contain less info. Having access to the full set of snpEff 'ANN' fields could be very useful.

Thanks, 

JM

**Comment by pcingola** [comment]
Using `-o gatk` means that SnpEff will ONLY output one effect per variant (and reduced information in the EFF field).

If you want to have all annotated effects, just drop the `-o gatk` option and use the default SnpEff's behavior (which is not compatible with GATK's pipeline). Obviously, the two behaviors are mutually exclusive.

If you want it both ways, you can simply:
- Annotate twice (run SnpEff twice) and end up with two annotated VCF files with different "flavors" of annotations.
- Re-annotate the VCF file once you finish processing with GATK (i.e. run SnpEff again after you processed with GATK).

I hope this helps.
