### ISSUE TITLE
bug? pseudogenes get lumped into a single gene_id 

### ISSUE THREAD

**Issue by lassancejm** [pcingola/SnpEff#302]
Hi, 

I am using snpEff (version SnpEff 5.0c (build 2020-11-25 14:23) with a custom gff. 

Things are working well with protein coding genes, but I noticed a weird behavior with pseudogenes. Basically, all entries seem to be associated with the first pseudogene entry in the annotation file. 

Here is an output produced using SnpSift Command: `java -jar SnpSift.jar extractFields {annotated_vcf} CHROM POS REF ALT 'ANN[*].GENE' 'ANN[*].GENEID' "ANN[*].BIOTYPE" "ANN[*].CDS_LEN" 'ANN[*].EFFECT' "ANN[*].HGVS_P" -s ',' -e 'NA' `

```
CHROM | POS | REF | ALT | ANN....GENE | ANN....GENEID | ANN....BIOTYPE | ANN....CDS_LEN | ANN....EFFECT | ANN....HGVS_P
chr1 | 481842 | G | A | Vmn2r_chr1_500 | APOLLO_000001 | protein_coding | -1 | 3_prime_UTR_variant | NA
chr1 | 481842 | G | A | APOLLO_000004 | null | NA | -1 | intragenic_variant | NA
```

The presence of `null` as gene_id caught my attention. I then realised that gene `APOLLO_000004` does not actually overlap that position 481842. 

These are the lines corresponding to that gene in the gff:

```
chr1	APOLLO	pseudogene	1139215	1140019	.	+	.	ID=APOLLO_000004;Name=Vmn1r_chr1_1139ps;transcript_id=APOLLO_000004-R1;transcript_class=pseudogene;gene_biotype=pseudogene;biotype=pseudogene
chr1	APOLLO	pseudogenic_transcript	1139215	1140019	.	+	.	ID=APOLLO_000004-R1;Name=Vmn1r_chr1_1139ps;Parent=APOLLO_000004;feature=APOLLO_000004
chr1	APOLLO	pseudogenic_exon	1139215	1140019	.	+	.	ID=exon:APOLLO_000004-R1:00000850;Name=8c2d43cf-16ea-4d1a-a2e0-cd00223e6e97;Parent=APOLLO_000004-R1;feature=APOLLO_000004
```

However, in the snpeff database, the gene spans the entire chromosome. 

```
grep 'APOLLO_000004' db_dump.txt | head

1	0	191578179	-1	Gene	null	APOLLO_000004	null	3387	0
```

Any idea what may be going on here? 

Thanks for your help (and a super useful tool!)

**Comment by pcingola** [comment]
GFF files are notorious for how many errors they usually have. GTF are usually a better option.
Did you use a "cds.fa" or "protein.fa" during the build process? If so, the errors have higher chances of being reported.

If you share the dataset and command line used to create the database, I might be able to take a look at it (no warranties, as it is usually very time-consuming to debug GFF files).

**Comment by lassancejm** [comment]
you are right, it was probably some weird format issue in the GFF: following your message, I re-built the database using the corresponding annotation in GTF, re-ran the annotation, et voilà, problem gone as far as I can tell. So, I learnt the lesson and will stick to GTF next time.  

About "protein.fa", do the headers have to follow any particular format or include specifics (like gene_id)?

**Comment by pcingola** [comment]
Both `protein.fa` and `cds.fa` should have the transcript ID in the header (just the transcript ID and nothing else).

I'm glad to hear this is working, I'll close the issue.
