### ISSUE TITLE
the distance between the upstream and downstream with utr

### ISSUE THREAD

**Issue by XK4959** [pcingola/SnpEff#303]
Hello
how many bp between the upstream and downstream with utr under the default parameters?
Looking forward to your reply.
Xinlong

**Comment by pcingola** [comment]
I think this is described in the documentation:
   https://pcingola.github.io/SnpEff/se_inputoutput/#effect-prediction-details
Default is 5K, but you can change it

**Comment by XK4959** [comment]
Thank you very much
