### ISSUE TITLE
Incorrect annotation of variants over exon/intron boundary

### ISSUE THREAD

**Issue by Andy-B-123** [pcingola/SnpEff#305]
Hi, thank you for all your work on SnpEff! I am coming up with a consistent error with 'splice_acceptor_variant' and 'splice_donor_variant's being called incorrectly in my samples. I've had a look through the issues and can't seem to find anything similar reported earlier. 

I have made a custom database for Helicoverpa armigera from the published genome using the .fasta and .gtf file from [NCBI](https://www.ncbi.nlm.nih.gov/assembly/GCF_002156985.1/). I am using Freebayes to generate my VCFs and this produces MNP variants. When an MNP variant is over an exon/intron junction SnpEff identifies it as a HIGH impact splice acceptor/donor variant even if the the actual sequence doesn't change in the variant.

Example 1:
AG retained in this variant.

`NW_018395390.1  108751  .       CAGT    TAGC    1202.35 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=39;CIGAR=1X2M1X;DP=40;DPB=40.5;DPRA=0;EPP=3.51141;EPPR=0;GTI=0;LEN=4;MEANALT=2;MQM=40.9231;MQMR=0;NS=1;NUMALT=1;ODDS=58.6707;PAIRED=1;PAIREDR=0;PAO=2;PQA=74;PQR=0;PRO=0;QA=1424;QR=0;RO=0;RPL=22;RPP=4.40227;RPPR=0;RPR=17;RUN=1;SAF=20;SAP=3.06598;SAR=19;SRF=0;SRP=0;SRR=0;TYPE=complex;technology.ILLUMINA=1;ANN=TAGC|splice_acceptor_variant&splice_region_variant&synonymous_variant&intron_variant|HIGH|LOC110370844|LOC110370844|transcript|XM_021326834.1|protein_coding|9/13|c.1119-3_1119delCAGTinsTAGC|p.374||1119/2292|373/763||      GT:DP:AD:RO:QR:AO:QA    1/1:40:0,39:0:0:39:1424`

Example image on IGV:
![image](https://user-images.githubusercontent.com/35752341/112263886-1cd2fc80-8cc4-11eb-850c-9beeae74c9cf.png)

Example 2:
Similar case, again the actual bases at the splice site don't change as the variant bases are actually much before the splice site. Here in the Ref, TAA (bold) is replaced by ACTG (bold). This doesn't disrupt the splicing but SnpEff is flagging this as a HIGH impact splice donor variant.
Ref:  TAAAAAAA**TAA**AGTAC        
Alt:  TAAAAAAA**ACTG**AGTAC       

`NW_018395390.1  234893  .       TAAAAAAATAAAGTAC        TAAAAAAAACTGAGTAC       323.972 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=24;CIGAR=1M1I7M3X5M;DP=24;DPB=25.5;DPRA=0;EPP=3.37221;EPPR=0;GTI=0;LEN=17;MEANALT=1;MQM=19.2917;MQMR=0;NS=1;NUMALT=1;ODDS=37.8762;PAIRED=0.958333;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=463;QR=0;RO=0;RPL=13;RPP=3.37221;RPPR=0;RPR=11;RUN=1;SAF=16;SAP=8.80089;SAR=8;SRF=0;SRP=0;SRR=0;TYPE=complex;technology.ILLUMINA=1;ANN=ACTGAGTAC|splice_donor_variant&splice_region_variant&intron_variant|HIGH|LOC110383841|LOC110383841|transcript|XM_021344762.1|protein_coding|8/8|c.1830+1_1830+8delGTACTTTAinsGTACTCAGT||||||,ACTGAGTAC|downstream_gene_variant|MODIFIER|LOC110383858|LOC110383858|transcript|XM_021344801.1|protein_coding||c.*404_*411delTAAAGTACinsACTGAGTAC|||||284|,ACTGAGTAC|downstream_gene_variant|MODIFIER|LOC110383867|LOC110383867|transcript|XM_021344813.1|protein_coding||c.*5239_*5246delGTACTTTAinsGTACTCAGT|||||5004|;LOF=(LOC110383841|LOC110383841|1|1.00) GT:DP:AD:RO:QR:AO:QA    1/1:24:0,24:0:0:24:463
`
Image:
![image](https://user-images.githubusercontent.com/35752341/112264415-f95c8180-8cc4-11eb-9c67-4a9ee8c68843.png)

Is this behaviour maybe because of the way that freebayes outputs variant calls? I'm not sure why but freebayes calls often include some of the references bases when it does it's haplotyping. Any thoughts on how to adjust the parameters to try and address this? I'd prefer not to exclude annotating splice sites as sometimes they are affected! I'm happy to share a sample VCF and database if needed.
Thank you!

**Comment by bioflower** [comment]
Hi, did you solve this problem? I am having the same issue. Thanks.
