### ISSUE TITLE
Download dbNSFP files from SnpEff's site: versions?

### ISSUE THREAD

**Issue by valleema** [pcingola/SnpEff#307]
Hello,

The files you offer, that are hosted here:
```
https://snpeff.blob.core.windows.net/databases/dbs/GRCh37/dbNSFP_4.1a/*
https://snpeff.blob.core.windows.net/databases/dbs/GRCh38/dbNSFP_4.1a/*
```
Is there a way to know if they are up-to-date with the last bug-fixed version in the official website:
> UPDATE (March 12, 2021): A bug fixed. Some ALoFT scores/information are missing in dbNSFP.

Cheers!

**Comment by pcingola** [comment]
The are not, but I'll try to update them soon and add some comments in the documentation.
Thank you for pointing this out!

**Comment by valleema** [comment]
Thanks @pcingola ! If you could wait a little, I have just found a problem in dbNSFP hg19 columns. I am going to report to the creators, and I will update this issue ASAP.

**Comment by valleema** [comment]
Alright, no worries, this was nothing. I was worried about a chromosome jump that is actually correct.

**Comment by pcingola** [comment]
Updated dbNSFP uploaded to

**GRCh38 / hg38:**

- https://snpeff.blob.core.windows.net/databases/dbs/GRCh38/dbNSFP_4.1a/dbNSFP4.1a.txt.gz
- https://snpeff.blob.core.windows.net/databases/dbs/GRCh38/dbNSFP_4.1a/dbNSFP4.1a.txt.gz.tbi

**GRCh37 / hg19:**

- https://snpeff.blob.core.windows.net/databases/dbs/GRCh37/dbNSFP_4.1a/dbNSFP4.1a.txt.gz
- https://snpeff.blob.core.windows.net/databases/dbs/GRCh37/dbNSFP_4.1a/dbNSFP4.1a.txt.gz.tbi

**Comment by pcingola** [comment]
Closing.
Feel free to reopen if there is an issue with the the dbNSFP files in the previous message.

**Comment by valleema** [comment]
Hello @pcingola,

I am sorry, bad timing, but the database just got updated to 4.2 😄 
https://sites.google.com/site/jpopgen/dbNSFP
> dbNSFP v4.2 is released.

Do you think you will be able to provide them as well?

**Comment by pcingola** [comment]
Ok, I'll try to update soon.

**Comment by shangyf-stu** [comment]
Hello, pcingola
Is there any way to get dbNSFP v2.4?
Any help is appreciate.

sincerely
Shang
