### ISSUE TITLE
Proposal of a manpage for snpeff

### ISSUE THREAD

**Issue by pgrt** [pcingola/SnpEff#312]
Hi,

For the Debian packaging, I wrote the enclosed manpage. Feel free to use it if you wish, or not.
Feedback would also be appreciated from my side.

Best,
Pierre

[snpEff.1.zip](https://github.com/pcingola/SnpEff/files/6229780/snpEff.1.zip)

**Comment by pcingola** [comment]
Looks great! Thank you for creating a man page.
I'll add it to the repository (I'll also try to do the same SnpSift)
