### ISSUE TITLE
annotate -dbsnp command not working

### ISSUE THREAD

**Issue by akshayzawar** [pcingola/SnpEff#313]
Hi,

The dbsnp annotate option in SnpSift is not working for me. The tutorial suggests 
"Annotate ID field using dbSnp Note: SnpSift will automatically download and uncompress dbSnp database if not locally available. java -jar SnpSift.jar annotate -dbsnp file.vcf > file.dbSnp.vcf"

However, it won't download the dbsnp database. 

Error below (even on their example file):
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: File not found '/mnt/g/Projects/Data/snpEff/./db/GRCh37/dbSnp/dbSnp.vcf.gz'

Also, not sure why it is searching in GRCh37 folder.

Any help would be appreciated!

**Comment by huysampled** [comment]
it is not working for me too. The workaround is to download the dbsnp database directly from NCBI and remap the chromosome.
