### ISSUE TITLE
Missing 'ANN' field for some insertions

### ISSUE THREAD

**Issue by kmegq** [pcingola/SnpEff#318]
Hello,

We are annotating structural variants in the canine genome called with Manta using the following SnpEff version and command.
```
##SnpEffVersion="4.3t (build 2017-11-24 10:18), by Pablo Cingolani"
##SnpEffCmd="SnpEff  CanFam3.1.75 sample.vcf "

```

We found that a subset of insertions are missing the 'ANN' field after annotation (~5000/62,000 variants), while all other variants have the 'ANN' field. 

For example, this insertion is missing the 'ANN' field:
`chr1    1033410 MantaINS:22087:7:7:0:2:0        T       <INS>   .       PASS    END=1033410;SVTYPE=INS;CIPOS=0,19;CIEND=0,19;HOMLEN=19;HOMSEQ=CAATAGTCGGGTAGTTCTT;LEFT_SVINSSEQ=CAATAGTCGGGTAGTTCTTTTATTTTTTTTTTTATTTATTTATGATAGTCACACAGAGAGAGAGAGAGAGGCAGAGACATAGGCAGAGGGAGAAGCAGGCTCCATGTACCGGGAGCCCGACGTGGGATTCGATCCTGGG;RIGHT_SVINSSEQ=GGAGAAGCAGGCGCCATGTACCGGGAGCCCGACGTGGGATTCGATCCTGGGTCTCCAGGATCACGCCCTAGGCCAAAGGCAGGCGCTAAACCGCTGCGCCACCCAGGGATCC     PR:SR   8,2:14,34
`

It appears that the variants being skipped may be those with incomplete insertion assembly, such that the ALT allele is listed as '`<INS>`'. Is there a way to annotate these using SnpEff?

Thank you for your help!

Best,
Kate

**Comment by robertzeibich** [comment]
Hi, has a solution been found for ALT <INS>? I also noticed that these are the only structural variants that are not being annotated. Help would be much appreciated. 

I am using snpEff version SnpEff 5.1f (build 2023-07-21 13:58), by Pablo Cingolani.
