### ISSUE TITLE
failed HIV database build 

### ISSUE THREAD

**Issue by Lei-GitHub** [pcingola/SnpEff#322]
Hi Pablo,
Sorry to input my question in closed questions (https://github.com/pcingola/SnpEff/issues/163#issuecomment-844399940).
I tried build the database for HIV (NC_001802.1 ) and its gtf file with same name. 
Added the information in config file: 

# HIV genome, version HXB2
hxb2.genome : HIV
hxb2.chromosomes : NC_001802.1
hxb2.NC_001802.1.codonTable : Standard

But I got error when build the database 
like this 

![image](https://user-images.githubusercontent.com/26446235/118890956-99054d00-b8cd-11eb-8d93-50c953d05948.png)
May I ask what is the problem and hot to solve it? Thank you very much.
Best,
Lei

**Comment by pcingola** [comment]
There is a simple script that builds the database from NCBI's GenBank file instead (which is always prefered for viral genomes):
Try running this (Unix / Mac):
```
./scripts/buildDbNcbi.sh NC_001802.1
```

**Comment by Lei-GitHub** [comment]
Hi Pcingola,
Thank you very much for the nice help.
