### ISSUE TITLE
The difference between snpEff output file gene names and phytozome gene names

### ISSUE THREAD

**Issue by anilineblue** [pcingola/SnpEff#324]
Hi, 
I'm trying to extract specific genes from resequencing file and then add annotations to the extracted gene files using snpEff. 
When I extracted gene from resequencing data (using Tabix), I used genomic coordinates which I got from Phytozome, and for this, I just searched for the gene name (ex. Phytochrome B) in Phytozome and got the coordinates. 
When I got the annotation output file of snpEff, I realized that Alias gene name that I got from Phytozome is different from the gene name of snpEff output file.

To summarize, 
From Phytozome, I got below information.

![phytozome - PHYTOCHROME B](https://user-images.githubusercontent.com/84106138/119442452-1b827800-bce5-11eb-914b-081d0290226e.png)

Using above "location" information, I extracted gene, and after that, I annotated this gene using snpEff, and got the below gene file.

![snpEff_genes_phytochrome b](https://user-images.githubusercontent.com/84106138/119442589-5dabb980-bce5-11eb-8c6c-e33036655e32.png)

As you can see, Phytozome Alias gene name (Sb01g037340) and snpEff output gene names (Sb01g044870 / Sb01g044880 / Sb01g044890 / Sb01g044900) differ.

I'm wondering why this happens.
I hope you can help me with this problem.
Thank you.

**Comment by pcingola** [comment]
Typically this is because there might be a discrepancy on the genome version (online vs. SnpEff's database).
Here are some comments: http://pcingola.github.io/SnpEff/se_faq/#genome-reference

Make sure you are using the exact same version to compare, otherwise there will be some discrepancies.
