### ISSUE TITLE
effect ontology

### ISSUE THREAD

**Issue by zsanli** [pcingola/SnpEff#325]
Dear Author,
I am using  SnpEff version SnpEff 5.0. What is the exact ANN term expression for "3_prime_UTR_truncation + exon_loss" as I want to extract this type of variants in the downstream analysis. e.g. "T|3_prime_UTR_truncation[space]+[space]exon_loss|MODIFIER|" or"T|3_prime_UTR_truncation+exon_loss|MODIFIER|" or "T|3_prime_UTR_truncation_exon_loss|MODIFIER|"

Many thanks 

zhi

**Comment by pcingola** [comment]
Spaces are not allowed in VCF files, so the right one is without spaces.
