### ISSUE TITLE
Can't Find which Brachypodium_Distachyon Genome Version was provided

### ISSUE THREAD

**Issue by deggoq** [pcingola/SnpEff#328]
Hi,

We are trying to use the pre-installed Brachypodium_distachyon genome database from SnpEff for annotations, but cannot find info about which version is being used. We searched through the SnpEff.config file and the SnpEff.jar databases, but neither show genome version used. Can you provide further information about which version is provided or further information about where else to find it?

Thanks in advance!

**Comment by pcingola** [comment]
Form the config file:
```
$ grep Brachypodium_distachyon snpEff.config
Brachypodium_distachyon.genome : Brachypodium_distachyon
Brachypodium_distachyon.reference : ftp.ensemblgenomes.org/pub/release-46
Brachypodium_distachyon.retrieval_date : 2020-01-26
```
