### ISSUE TITLE
snpEff runtime longer than expected

### ISSUE THREAD

**Issue by humzalikhan** [pcingola/SnpEff#329]
I'm running snpEff on an HPC cluster (computing on a node with 16G RAM), but it takes around two hours to complete annotating one file (4.5 million variants, human genome). Is this expected? I read that snpEff could do around one million per minute (on our HPC it is going at closer to 80k/min). I have ~1500 genomes to annotate, so this makes it slightly computationally untenable to pursue, if this is the case. Code below:

java -Xmx8g -jar snpEff.jar -v GRCh37.75 /u/home/X/BA1001.vcf > /u/home/X/BA1001_ANNOTATED.vcf -noStats 

When I tried to run -t, it said this was no longer supported.

Thanks so much--appreciate any help!

**Comment by pcingola** [comment]
Some tips:
- The best practices are to have ALL the 1,500 genomes in one VCF file.
- If you have a cluster, obviously you can submit multiple snpeff processes in parallel

These links may also help:
- http://pcingola.github.io/SnpEff/se_faq/#how-much-memory-should-i-use
- http://pcingola.github.io/SnpEff/se_faq/#snpeff-taking-too-long

I hope this helps.

**Comment by pcingola** [comment]
Closing, feel free to re-open.
