### ISSUE TITLE
Generate just html report

### ISSUE THREAD

**Issue by KDRichar** [pcingola/SnpEff#330]
I have the annotated vcf as generated by snpeff, is there a simple way to just -regenerate the html?

**Comment by pcingola** [comment]
Unfortunately, the report is a side-effect of annotating the VCF, so the only way to create it is by running the annotaion again.

**Comment by KDRichar** [comment]
Thank you.

All the best,
Keri Richards

Kerianne Richards, MS
Bioinformatics and Computational Biology
Doctoral Student
SSBGSO, President
George Mason University
***@***.***
(240)672-6475 (c)

________________________________
