### ISSUE TITLE
Problems building a new database

### ISSUE THREAD

**Issue by benjamin-battistoni** [pcingola/SnpEff#333]
Hello,

my team is working with variants from Japanese plum (_Prunus salicina_ Lindl.) and we want to build the database for this species, but we have not had favorable results (this species is not included in the pre-built databases). For this species its reference genome has recently been published (https://www.rosaceae.org/Analysis/9450778).
Is it possible for you to build the database for this species?

Thanks in advance,
Benjamín Battistoni Hernández

**Comment by pcingola** [comment]
Apologies for the late reply.
Could you please send me the specific links for the following files?

- Genome FASTA
- Gene definition files (GTF / GFF / other)
- CDS or Protein FASTA files

**Comment by benjamin-battistoni** [comment]
Thanks for the reply, below are the links.

The link to the page containing the files is: https://www.rosaceae.org/Analysis/9450778

The links containing the files are:

* Genome FASTA: https://www.rosaceae.org/rosaceae_downloads/Prunus_salicina/ps_sanyueli_v2.0.a1/assembly/psalicina_v2.0.fasta.gz 

* Gene definition files (GFF3): https://www.rosaceae.org/rosaceae_downloads/Prunus_salicina/ps_sanyueli_v2.0.a1/genes/psalicina_v2.0.genes.gff3.gz

* Protein FASTA file: https://www.rosaceae.org/rosaceae_downloads/Prunus_salicina/ps_sanyueli_v2.0.a1/genes/psalicina_v2.0.protein.fasta.gz


Regards,
Benjamín Battistoni Hernández
