### ISSUE TITLE
stop_lost annotation confusion

### ISSUE THREAD

**Issue by najoshi** [pcingola/SnpEff#335]
So I am trying to figure out why this particular complex variant was annotated with an effect of "start_lost" when I don't see any evidence of the start codon being changed. Here is the full vcf line:

`chr1	20717668	.	ACGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAA	GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC	566.598	.	AB=0.347826;ABP=12.2627;AC=5;AF=0.5;AN=10;AO=16;CIGAR=1X57M1X;DP=46;DPB=46.1525;DPRA=0;EPP=5.18177;EPPR=4.16842;GTI=0;LEN=59;MEANALT=1;MQM=60;MQMR=60;NS=5;NUMALT=1;ODDS=5.38955;PAIRED=0.5625;PAIREDR=0.466667;PAO=9;PQA=333;PQR=0;PRO=0;QA=586;QR=1103;RO=30;RPL=13;RPP=16.582;RPPR=31.9633;RPR=3;RUN=1;SAF=7;SAP=3.55317;SAR=9;SRF=8;SRP=17.1973;SRR=22;TYPE=complex;ANN=GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|start_lost|HIGH|KIF17|KIF17|transcript|NM_020816.4|protein_coding|1/15|c.-20_39delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|p.MetAlaSerGluAlaValLysValValValArgCysArg1?|340/3961|1/3090|1/1029||,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|start_lost|HIGH|KIF17|KIF17|transcript|NM_001122819.3|protein_coding|1/15|c.-20_39delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|p.MetAlaSerGluAlaValLysValValValArgCysArg1?|340/3958|1/3087|1/1028||,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|5_prime_UTR_variant|MODIFIER|KIF17|KIF17|transcript|NM_020816.4|protein_coding|1/15|c.-20_39delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC||||||,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|5_prime_UTR_variant|MODIFIER|KIF17|KIF17|transcript|NM_001122819.3|protein_coding|1/15|c.-20_39delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC||||||,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|5_prime_UTR_variant|MODIFIER|KIF17|KIF17|transcript|NM_001287212.2|protein_coding|1/15|c.-447_-389delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|||||2098|,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|downstream_gene_variant|MODIFIER|SH2D5|SH2D5|transcript|NM_001103161.2|protein_coding||c.*4066_*4124delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|||||2063|,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|downstream_gene_variant|MODIFIER|SH2D5|SH2D5|transcript|XM_011541459.2|protein_coding||c.*4066_*4124delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|||||2063|,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|downstream_gene_variant|MODIFIER|SH2D5|SH2D5|transcript|XM_011541460.2|protein_coding||c.*4066_*4124delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|||||2063|,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|downstream_gene_variant|MODIFIER|SH2D5|SH2D5|transcript|XM_011541462.2|protein_coding||c.*4066_*4124delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|||||2063|,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|downstream_gene_variant|MODIFIER|SH2D5|SH2D5|transcript|XM_011541461.2|protein_coding||c.*4066_*4124delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|||||2063|,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|downstream_gene_variant|MODIFIER|SH2D5|SH2D5|transcript|NM_001103160.2|protein_coding||c.*4066_*4124delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|||||2063|,GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|intron_variant|MODIFIER|LOC107985528|LOC107985528|transcript|unknown_transcript_1|protein_coding|987/1510|c.167449+904178_167449+904236delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC||||||WARNING_TRANSCRIPT_MULTIPLE_STOP_CODONS;LOF=(KIF17|KIF17|3|0.67)	GT:DP:AD:RO:QR:AO:QA:GL	0/1:4:3,1:3:111:1:37:-2.49371,0,-9.14896	0/1:9:6,3:6:221:3:109:-13.5154,0,-16.9355	0/1:11:6,5:6:223:5:182:-16.4518,0,-16.8162	0/1:12:8,4:8:294:4:149:-22.2684,0,-21.995	0/1:10:7,3:7:254:3:109:-13.2144,0,-19.5986
`

The first annotation looks like this:

`GCGGCAGCGCACGACAACCTTCACCGCCTCGGAGGCCATGGCGCCGCGCCCAGGACCAC|start_lost|HIGH|KIF17|KIF17|transcript|NM_020816.4|protein_coding|1/15|c.-20_39delTTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGTinsGTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC|p.MetAlaSerGluAlaValLysValValValArgCysArg1?|340/3961|1/3090|1/1029||
`

For some reason it is calling it a deletion & insertion instead of just two separate SNPs. Looking at the two sequences (I should add that this gene is on the reverse strand):

`TTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGT`
`GTGGTCCTGGGCGCGGCGCCATGGCCTCCGAGGCGGTGAAGGTTGTCGTGCGCTGCCGC`

you can see that all of the bases are the same except for the first and last bases. The start codon is in the middle, i.e. this variant crosses the 5'UTR to exon 1 boundary. However, the start codon does not change, so why is it being annotated as a "start_lost"?

**Comment by pcingola** [comment]
From SnpEff's perspective, complex variants are annotated as a deletion + an insertion, which in this case is not correct.
I definitely should try to improve this behavior.

But also contributing to this issue is that the variant caller should have called these as two (phased) SNPs instead of this long/complex variant.
