### ISSUE TITLE
Output of snpsift is not clear

### ISSUE THREAD

**Issue by dhwani2410** [pcingola/SnpEff#339]
Considering that we are comparing two vcf files using snpsift concordance ((https://pcingola.github.io/SnpEff/ss_concordance/)).https://pcingola.github.io/SnpEff/ss_concordance/ The out should be 1/1 which tells the information of how many variants are present in both files. However, the output is very weird. Can you please explain it clearly?

index:  MT  460030998
        index:  1   19705
                1 / 2   45170805 / 45174315
                2 / 3   77052081 / 77055591
                3 / 4   104065531 / 104069041
                4 / 5   124098372 / 124101881
                5 / 6   146535292 / 146538802
                6 / 7   184793526 / 184797035
                7 / 8   206156508 / 206160018
                8 / 9   223072816 / 223076326
                9 / 10  242315995 / 242319505
                10 / 11 261053789 / 261057299
                11 / 12 290190553 / 290194063
                12 / 13 312869636 / 312873146
                13 / 14 321966539 / 321970049
                14 / 15 336131317 / 336134827
                15 / 16 350871669 / 350875179
                16 / 17 368900523 / 368904032
                17 / 18 391305860 / 391309369
                18 / 19 398932237 / 398935747
                19 / 20 425219198 / 425222708
                20 / 21 437022008 / 437025517
                21 / 22 442563678 / 442567188
                22 / X  451783418 / 451786927
                X / Y   459553691 / 459557200
                Y / MT  459588787 / 459592296

**Comment by sara-wennersten** [comment]
I, too, would like a better explanation of the concordance output files. Thanks!

**Comment by pcingola** [comment]
Can you please let me know which part of the documentation is unclear / you don't understand?
https://pcingola.github.io/SnpEff/ss_concordance/

The output you are showing are messages referring to the indexing of the VCF files (you can ignore that part).

Are you having trouble understanding the "Concordance by variant" section, the "Concordance by sample", or the overall summary?
