### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by Akazhiel** [pcingola/SnpEff#340]
Hello!

Is there a way of avoiding having the escape characters such as `%3B` which should be a semicolon in the output file?

Cheers!

**Comment by pcingola** [comment]
The VCF specification clearly states that this is the correct way to write those characters.
See VCF spec 4.3 section 1.2 (https://samtools.github.io/hts-specs/VCFv4.3.pdf)
So, as far as I understand, the only way to avoid '%3B', would be by having a corrupted VCF file.
