### ISSUE TITLE
quality column shows 500 value

### ISSUE THREAD

**Issue by Pratibhakadam** [pcingola/SnpEff#341]
Hello,
I am working on sars cov-2 genome and in my vcf file it has shown 500 value for quality of mutation what does that mean and also can anyone tell me the cutoff for quality.
As I have searched but not getting specific cutoff value...so how can i decide the quality is good or bad!

Please let me know the answer.

thanks,
pratibha

**Comment by pcingola** [comment]
This is a "variant calling" question, thus not related to SnpEff or variant annotation.
