### ISSUE TITLE
Problem for building a database

### ISSUE THREAD

**Issue by chenqing-1996** [pcingola/SnpEff#343]
Hello pcingola,
I have some questions for building a database, I still can't solve it despite my efforts.

**Describe the bug**
Building the database failed, but there were no errors in the log file.

**To Reproduce**
1. SnpEff version: 5.0e
2. SnpEff full command line: java -Xmx80g -jar /home/cq/biosoft/snpEff/snpEff.jar build -gff3 -v SC
3. log : 
00:00:00	SnpEff version SnpEff 5.0e (build 2021-03-09 06:01), by Pablo Cingolani
00:00:00	Command: 'build'
00:00:00	Building database for 'SC'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'SC'
00:00:00	Reading config file: /home/cq/biosoft/snpEff/snpEff.config
00:00:00	done
Reading GFF3 data file  : '/home/cq/biosoft/snpEff/data/SC/genes.gff'
....................................................................................................
		10000	...............................................................
	Total: 16383 markers added.

	Create exons from CDS (if needed): ..........................................................................................................................................................................................................................
	Exons created for 16383 transcripts.

	Deleting redundant exons (if needed): 
		Total transcripts with deleted exons: 0

	Collapsing zero length introns (if needed): 
		Total collapsed transcripts: 0
	Reading sequences   :
	Reading FASTA file: '/home/cq/biosoft/snpEff/data/genomes/SC.fa'
		Reading sequence 'Contig0000001', length: 116694
		Adding genomic sequences to exons: 	Done (0 sequences added, 0 ignored).
		Reading sequence 'Contig0000002', length: 103836945
..........................
Adjusting transcripts: 
	Adjusting genes: 
	Adjusting chromosomes lengths: 
	Ranking exons: 
	Create UTRs from CDS (if needed): 
	Correcting exons based on frame information.
	
	Remove empty chromosomes: 

	Marking as 'coding' from CDS information: 
	Done: 0 transcripts marked
#-----------------------------------------------
# Genome name                : 'SC'
# Genome version             : 'SC'
# Genome ID                  : 'SC[0]'
# Has protein coding info    : true
# Has Tr. Support Level info : true
# Genes                      : 1
# Protein coding genes       : 1
#-----------------------------------------------
# Transcripts                : 16383
# Avg. transcripts per gene  : 16383.00
# TSL transcripts            : 0
#-----------------------------------------------
# Checked transcripts        : 
#               AA sequences :      0 ( 0.00% )
#              DNA sequences :      0 ( 0.00% )
#-----------------------------------------------
# Protein coding transcripts : 16383
#              Length errors :      0 ( 0.00% )
#  STOP codons in CDS errors :  15186 ( 92.69% )
#         START codon errors :  15119 ( 92.28% )
#        STOP codon warnings :  15378 ( 93.87% )
#              UTR sequences :      0 ( 0.00% )
#               Total Errors :  16012 ( 97.74% )
# WARNING                    : No protein coding transcript has UTR
#-----------------------------------------------
# Cds                        : 133751
# Exons                      : 133751
# Exons with sequence        : 133751
# Exons without sequence     : 0
# Avg. exons per transcript  : 8.16
# WARNING                    : No mitochondrion chromosome found
#-----------------------------------------------
......................

00:00:12	Caracterizing exons by splicing (stage 1) : 
	....................................................................................................
	100000	.................................
01:12:12	Caracterizing exons by splicing (stage 2) : 

**Data**
my gff file like:
Contig0000002	maker	mRNA	101150074	101162537	100	-	.	ID=Maker00001;
Contig0000002	maker	CDS	101150074	101150267	.	-	2	Parent=Maker00001;
Contig0000002	maker	CDS	101150571	101150747	.	-	2	Parent=Maker00001;
Contig0000002	maker	CDS	101151311	101151404	.	-	0	Parent=Maker00001;
Contig0000002	maker	CDS	101151497	101151596	.	-	1	Parent=Maker00001;
Contig0000002	maker	CDS	101152336	101152477	.	-	2	Parent=Maker00001;
Contig0000002	maker	CDS	101153214	101153370	.	-	0	Parent=Maker00001;
Contig0000002	maker	CDS	101153762	101153836	.	-	0	Parent=Maker00001;
Contig0000002	maker	CDS	101154848	101154958	.	-	0	Parent=Maker00001;

I have tried to build the database several times, but I don't know why it hasn't worked out. Looking forward to your reply.
Thank you.

**Comment by SuPrSh** [comment]
I am also getting building a custom database. The process ends abruptly below the given error. I am unable to figure it out. Any help in this regard is appreciated.

. File '/mnt/sdb/P6260/snpeff/data/ggan/genes.gtf' line 313837
	'C16845300	AUGUSTUS	CDS	5101	5113	.	-	0	transcript_id "g46955.t1"; gene_id "g46955";'

	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:357)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:370)
	at org.snpeff.SnpEff.run(SnpEff.java:1188)
	at org.snpeff.SnpEff.main(SnpEff.java:168)
00:01:06	Logging
00:01:07	Checking for updates...
00:01:09	Done.

regards,

**Comment by chenqing-1996** [comment]
> I am also getting building a custom database. The process ends abruptly below the given error. I am unable to figure it out. Any help in this regard is appreciated.
> 
> . File '/mnt/sdb/P6260/snpeff/data/ggan/genes.gtf' line 313837 'C16845300 AUGUSTUS CDS 5101 5113 . - 0 transcript_id "g46955.t1"; gene_id "g46955";'
> 
> ```
> at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:357)
> at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:370)
> at org.snpeff.SnpEff.run(SnpEff.java:1188)
> at org.snpeff.SnpEff.main(SnpEff.java:168)
> ```
> 
> 00:01:06 Logging 00:01:07 Checking for updates... 00:01:09 Done.
> 
> regards,
I'm really sorry that I can't help you, because I haven't solved my problem yet. You can see if there's something wrong with your gtf file.

**Comment by Abieskawa** [comment]
I followed what @arif.ashraf.opu said on https://www.biostars.org/p/359661/ 
AND IT WORK FINE WITH THE INSTRUCTION !!!
