### ISSUE TITLE
Adding PDB annotations 

### ISSUE THREAD

**Issue by kasia-te** [pcingola/SnpEff#346]
### Question about PDB annotations

I use SnpEff to annotate human variants (hg38 genome version). 
I update the SnpEff database quite frequently (with new Ensembl versions), so I usually build the SnpEff database on my own.
The annotations works fine (I think), but I am not able to add the protein interaction predictions (which were present in the  "ready to use" versions of the human database).
Could you please describe how to build the PDB based part of the database? 
I cannot find it in the documentation.

Best,
Katarzyna

**Comment by pcingola** [comment]
I'll try to update the documentation. The process is rather involved, but I'll do my best to simplify it.
