### ISSUE TITLE
Question: appropriate reference genome

### ISSUE THREAD

**Issue by Talo07** [pcingola/SnpEff#348]
Hi

My project is focused on the analysis of human genetic variants from WGS and WES.
The reference I used for the mapping is: GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna
For snpeff, I am using version 5.0. Unless I am mistaken, in the config file I did not find a genome that corresponds to this version.
In order to correctly annotate the variants that I obtained I would like to know if there is a genome ready to download in the config file which corresponds to the genome that I used for the mapping ??

Thanks,
Talo,

**Comment by Abieskawa** [comment]
Hi, 
I run into similar problem as u did, did u solved it? 
Tried this: 
https://pcingola.github.io/SnpEff/examples/
