### ISSUE TITLE
Database Issues/Request

### ISSUE THREAD

**Issue by fordla10** [pcingola/SnpEff#353]
### Database requests

1. Organism name: felis catus (cat)
2. Link gene definition file (e.g. GTF / GFF / GenBank): http://ftp.ensembl.org/pub/rapid-release/species/Felis_catus_x_Leopardis_geoffroyi/GCA_018350175.1/geneset/2021_08/Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-2021_08-genes.gtf.gz
3. Link to Genome FASTA file/s: http://ftp.ensembl.org/pub/rapid-release/species/Felis_catus_x_Leopardis_geoffroyi/GCA_018350175.1/genome/Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-unmasked.fa.gz
4. Link to CDS FASTA file: http://ftp.ensembl.org/pub/rapid-release/species/Felis_catus_x_Leopardis_geoffroyi/GCA_018350175.1/geneset/2021_08/Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-2021_08-cds.fa.gz
5. Link to Protein FASTA file: http://ftp.ensembl.org/pub/rapid-release/species/Felis_catus_x_Leopardis_geoffroyi/GCA_018350175.1/geneset/2021_08/Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-2021_08-pep.fa.gz

Note: Genome FASTA file might not be needed in some cases (e.g. GenBank files usually have genome sequence information)

Note: Either CDS or Protein FASTA files should be used to ensure correctness (sometimes these sequences are provided in the GenBank files).

### Feature requests

**Is your feature request related to a problem? Please describe.**
I have tried using the instructions posted to create an bin, but I keep running into issues (i.e. program runs but does not create a bin). I will attach screenshots below.

**Describe the solution you'd like**
I would like to have a new reference genome added, so I can use snpeff to analyze my data.

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot of snpeff.contig file: (Added felcat_2021_hybrid)
![screenshot1](https://user-images.githubusercontent.com/92888312/138161216-4c91028d-4869-4f7b-beaa-87092e9eb8c1.png)

Screenshot of errors when I run the program:
![screenshot2](https://user-images.githubusercontent.com/92888312/138161230-30f6d78b-9ef6-4345-9d5b-1228abb4ef78.png)

**Comment by gubrins** [comment]
Heys @fordla10 did you manage to create it? I am also having issues creating a database for the cat...

**Comment by fordla10** [comment]
Hi @gubrins, I recently tried doing this again and it worked. I will attach the script I used (not sure why it worked this time and not last time)

Hope this helps!

`#!/bin/bash --verbose

### CREATING CUSTOM SNPEFF DATABASE ###
# Navigate to the folder where you want to download the snpeff folder
# download snpeff
wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip

# decompress snpeff
unzip snpEff_latest_core.zip

# download sequence
wget http://ftp.ensembl.org/pub/rapid-release/species/Felis_catus_x_Leopardis_geoffroyi/GCA_018350175.1/genome/Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-unmasked.fa.gz

# download annotation
wget http://ftp.ensembl.org/pub/rapid-release/species/Felis_catus_x_Leopardis_geoffroyi/GCA_018350175.1/geneset/2021_08/Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-2021_08-genes.gtf.gz

# decompress genome files, sometimes gzip compression causes issues when using ensembl files with snpeff
gunzip Felis*

# add folder for cat genome
# fcxlg short for Felis catus x Leopardis geoffroyi
mkdir -p ./snpEff/data/fcxlg

# rename assembly and annotation files to what snpeff expects
mv Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-2021_08-genes.gtf genes.gtf
mv Felis_catus_x_Leopardis_geoffroyi-GCA_018350175.1-unmasked.fa sequences.fa

# move assembly and annotation to new cat genome folder
mv genes.gtf ./snpEff/data/fcxlg
mv sequences.fa ./snpEff/data/fcxlg

# add lines to config file for cat genome
echo "# updated cat assembly" >> ./snpEff/snpEff.config
echo "fcxlg.genome : Cat" >> ./snpEff/snpEff.config

# load java on hpcc
ml -* Java/15.0.2

# build database
java -jar ./snpEff/snpEff.jar build -gtf22 -v fcxlg`

**Comment by gubrins** [comment]
Heys @fordla10 thank you very much for your quick answer!!
Unluckily, It did not work... At first it did not work because it was asking me the protein.fa and the cds.fa, I added them and now is telling me this:

`Protein sequences comparison failed!`

Did you had a similar issue?
 I also have few other questions. Why did you use this genome that seems to be from an hybrid?
Did you try it with the cat's genome from ensembl (https://www.ensembl.org/Felis_catus/Info/Index)? 
I would like to try with that one, but when I try to download the genome, I don't see an specific file, I see files for each of the chromosomes (http://ftp.ensembl.org/pub/release-105/fasta/felis_catus/dna/). Do you know which file should I download?

I would really appreciate your help, as it seems that the creator of the program is quite busy right now.

Thanks!!

**Comment by gubrins** [comment]
Heys again,
I already solved it. I changed the snpEff version and it worked!

**Comment by zhiliangfu** [comment]
> Heys again, I already solved it. I changed the snpEff version and it worked!

this successes for me, thanks!
