### ISSUE TITLE
a question about warning information

### ISSUE THREAD

**Issue by ChenDepp** [pcingola/SnpEff#354]
hi, everyone! 
   when i buliding database  by commmand "java -jar /opt/snpEff/snpEff.jar build -v purdomii" 
   it report warning information:
     WARNING: Cannot find last exonic position before 1237583 for transcript 'Popu0001410.1'
WARNING: Cannot find last exonic position before 2405626 for transcript 'Popu0002640.1'
WARNING: Cannot find last exonic position before 13193704 for transcript 'Popu0013450.1'
WARNING: Cannot find first exonic position after 7100333 for transcript 'Popu0007400.1'
 i look the source code but i not good at java, so i can't found the reason, can you tell me why it report the
warnning ,  looking forward to your reply! thank you

**Comment by LHXqwq** [comment]
Hi ChenDepp,
I just encountered the same problem as you, I guess it was the gff3 file that was not recognized correctly, so I converted it to gtf format with "gffread name.gff3 -T -o name.gtf" and renamed genes.gff to genes. gtf, when building the library, use java -jar /home/snpEff/snpEff.jar build -gtf22 Gmax_508_v4 to complete the library building, and the warning disappears.
