### ISSUE TITLE
"-no-intergenic" option does not work

### ISSUE THREAD

**Issue by uceleste** [pcingola/SnpEff#361]
Hi All,

I'm using SnpEff with my reference genome as a database. I can get all the outputs, however the "-no-intergenic" option doesn't seem to work. I report my command line and the graph with the plotted intergenic regions that I'd like to remove. I'm using SnpEff version 5.0d.

`java -jar /opt/snpEff/snpEff.jar -fi intervals.bed -ud 1000 -no-intergenic -lof -fastaProt prot_snpeff.fasta my_genome variations.vcf > snpeff.vcf`

![Untitled](https://user-images.githubusercontent.com/30322535/145880040-985c7e73-342e-4f7f-8f27-a5ee0a9db71a.png)

Am I doing something wrong?
I am not attaching data as I think the problem is due to something else, but in case I can provide.

Thank you

**Comment by Kathatinka** [comment]
Hey, 
could you solve this problem? I am also having trouble with the filter options "-no-upstream" and "-no-downstream" on SnpEff version 5.1.

**Comment by Kathatinka** [comment]
Hello everyone,

I made the same observation and figured out, that the filter option is only applied to the Annotation.vcf and not to the .genes.txt and stats.html (as the later ones are connected to each other). This also leads to genes in the genes.txt, which should be filtered out and therefore do not occur in the vcf.
