### ISSUE TITLE
SnpEff does not create htmlStats

### ISSUE THREAD

**Issue by mictadlo** [pcingola/SnpEff#363]
SnpEff does not create htmlStats with the below command:

    $ snpEff eff -Xmx20G LAB330 LabUsa16cWild01-20_L-Q.vcf | head
    ##fileformat=VCFv4.0
    ##filedate=20210414
    ##source=SGSautoSNP
    ##reference=NbLab330.genome.softmasked.fasta
    ##phasing=allhomozygote
    ##INFO=<ID=DP,Number=1,Type=Integer,Description="Read depth over all samples">
    ##INFO=<ID=PL,Number=0,Type=String,Description="Panel">
    ##SnpEffVersion="5.0e (build 2021-03-09 06:01), by Pablo Cingolani"
    ##SnpEffCmd="SnpEff  LAB330 LabUsa16cWild01-20_L-Q.vcf "
    ##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">
    ...
    NbLab330C06 30727797 NbLab3300177406 ? C,T 102.0 . DP=239;ANN=C|intergenic_region|MODIFIER|gene.49723.0-gene.49722.4|gene.49723.0-gene.49722.4|intergenic_region|gene.49723.0-gene.49722.4|||n.30727797?>C||||||,T|intergenic_region|MODIFIER|gene.49723.0-gene.49722.4|gene.49723.0-gene.49722.4|intergenic_region|gene.49723.0-gene.49722.4|||n.30727797?>T|||||| GT:DP 1/1:7 1/1:25 2/2:31 2/2:311/1:46 2/2:27 1/1:24 2/2:48
    NbLab330C06 30728018 NbLab3300177408 ? C,T 45.0 . DP=100;ANN=C|intergenic_region|MODIFIER|gene.49723.0-gene.49722.4|gene.49723.0-gene.49722.4|intergenic_region|gene.49723.0-gene.49722.4|||n.30728018?>C||||||,T|intergenic_region|MODIFIER|gene.49723.0-gene.49722.4|gene.49723.0-gene.49722.4|intergenic_region|gene.49723.0-gene.49722.4|||n.30728018?>T|||||| GT:DP 2/2:1 2/2:21 1/1:9 1/1:42/2:14 1/1:15 2/2:19 1/1:17

What did I miss?

Thank you in advance,

**Comment by pcingola** [comment]
I think that you are forcing the SnpEff command to finish prematurely by adding the "| head". So the command is finished before the stats file is created. 

The solution would be to remove the trailing "| head".
You can feed a few lines from the VCF file via STDIN (just make sure all the header section is included in the lines). e.g.:
```
head -n 1000 LabUsa16cWild01-20_L-Q.vcf | snpEff eff -Xmx20G LAB330 > out.eff.vcf
```

**Comment by mictadlo** [comment]
I tried again but still not luck with the below command:
```
> snpEff eff -Xmx20G LAB330 LabUsa16cWild01-20_L-Q.vcf
...
685?>T||||||	GT:DP	2/2:11	2/2:38	1/1:1	1/1:8	2/2:44	./.:0	2/2:67	1/1:5
> ls -hlatr
-rw-rw----  1 lorencm  default         499M Dec  6 10:25 LabUsa16cWild01-20_L-Q.snpEff.vcf
-rw-rw----  1 lorencm  default         1.0G Dec 13 10:22 LabUsa16cWild01-20_L-Q.annotated.vcf
> 
```

**Comment by mictadlo** [comment]
P.S. Would you like to recive all input files?
