### ISSUE TITLE
SnpEff does not follow HGVS guidelines for multi-AA substitution events

### ISSUE THREAD

**Issue by m-crown** [pcingola/SnpEff#371]
**Describe the bug**
SnpEff does not follow HGVS guidelines for multi-AA substitution events.

**To Reproduce**
1. SnpEff version: 5.0e 
2. Genome version: NC_045512.2
3. SnpEff full command line: java -Xmx2g -jar snpEff.jar -noShiftHgvs -hgvs1LetterAa -download -no SPLICE_SITE_ACCEPTOR -no SPLICE_SITE_DONOR -no SPLICE_SITE_REGION -no SPLICE_SITE_BRANCH -no SPLICE_SITE_BRANCH_U12 -noLog -noLof -no-intron -noMotif -noStats -no-downstream -no-upstream -no-utr NC_045512.2 input.vcf > input.ann.vcf

**Expected behavior**

From [HGVS site](http://varnomen.hgvs.org/recommendations/protein/variant/substitution/) : 

Can I describe a TrpVal to CysArg variant as a amino acid substitution (p.TrpVal24CysArg)?
No, this is not allowed. By definition a substitution changes one amino acid into one other amino acid. The change TrpVal to CysArg should be described as NP_003997.1:p.Trp24_Val25delinsCysArg, i.e. a deletion/insertion (indel) (see Deletion-Insertion).

SnpEff outputs: RG203KR for such events rather than R203_G204delinsKR

[problem.txt](https://github.com/pcingola/SnpEff/files/7855582/problem.txt)
[problem.ann.txt](https://github.com/pcingola/SnpEff/files/7855581/problem.ann.txt)

**Comment by schorlton** [comment]
Thanks for the great tool. Could I suggest prioritizing/revisiting this? It is a major issue for parsing variant changes with external tools, and following HGVS standard would greatly help.

There are at least 3 independent tickets filed for this same issue:
- https://github.com/pcingola/SnpEff/issues/435
- https://github.com/pcingola/SnpEff/issues/234
- https://github.com/pcingola/SnpEff/issues/371

Thanks for your consideration!

**Comment by m-crown** [comment]
@pcingola this got closed as completed yesterday, can you let me know the commit where it was updated? Thanks
