### ISSUE TITLE
Unable to download databases: "The specified blob does not exist"

### ISSUE THREAD

**Issue by jamigo** [pcingola/SnpEff#374]
**Describe the bug**
Unable to download GRCh37.p13 and GRCh38.p13

**To Reproduce**
1. SnpEff version: 5.1
2. Genome version: both GRCh37 and GRCh38
3. SnpEff full command line:
`for genome in GRCh37.p13 GRCh38.p13; do java -Xmx4g -jar snpEff.jar $genome examples/test.vcf; done`
4. Output / Error message: Please include a full VCF line output
```
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.p13.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.p13.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.p13.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.p13.zip]
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.p13.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.p13.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.p13.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.p13.zip]
```

**Expected behavior**
GRCh37.p13 and GRCh38.p13 datasets should be downloaded into "data" folder and example test.vcf file should be annotated.

**Data**
Distribution's examples/test.vcf

**Additional**
wgetting directly the files provides the "specified blob does not exist" message:
```
$ wget https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.p13.zip
--2022-01-25 17:05:23--  https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.p13.zip
Resolving snpeff.blob.core.windows.net... 52.239.234.228
Connecting to snpeff.blob.core.windows.net|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2022-01-25 17:05:23 ERROR 404: The specified blob does not exist..
```

**Comment by LGLGLTM** [comment]
Reporting the same issue with https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.75.zip

**Comment by RamRS** [comment]
I'm having the same issue myself. Please help, @pcingola !

**Comment by RamRS** [comment]
I commented the Primary Azure blob storage URL and un-commented the Secondary Azure blob storage using SAS-Token URL + key lines, and it still did not work. Here is the error with the primary URLs:

```
$ java -jar ./snpEff.jar download GRCh38.p13
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.p13.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.p13.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.p13.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.p13.zip]
```

And here's the error with secondary URLs:

```
$ java -jar ./snpEff.jar download GRCh38.p13
00:00:00 ERROR while connecting to https://datasetsnpeff.blob.core.windows.net/dataset/v5_1/snpEff_v5_1_GRCh38.p13.zip?sv=2019-10-10&st=2020-09-01T00%3A00%3A00Z&se=2050-09-01T00%3A00%3A00Z&si=prod&sr=c&sig=isafOa9tGnYBAvsXFUMDGMTbsG2z%2FShaihzp7JE5dHw%3D
00:00:00 ERROR while connecting to https://datasetsnpeff.blob.core.windows.net/dataset/v5_0/snpEff_v5_0_GRCh38.p13.zip?sv=2019-10-10&st=2020-09-01T00%3A00%3A00Z&se=2050-09-01T00%3A00%3A00Z&si=prod&sr=c&sig=isafOa9tGnYBAvsXFUMDGMTbsG2z%2FShaihzp7JE5dHw%3D
FATAL ERROR: Failed to download database from [https://datasetsnpeff.blob.core.windows.net/dataset/v5_1/snpEff_v5_1_GRCh38.p13.zip?sv=2019-10-10&st=2020-09-01T00%3A00%3A00Z&se=2050-09-01T00%3A00%3A00Z&si=prod&sr=c&sig=isafOa9tGnYBAvsXFUMDGMTbsG2z%2FShaihzp7JE5dHw%3D, https://datasetsnpeff.blob.core.windows.net/dataset/v5_0/snpEff_v5_0_GRCh38.p13.zip?sv=2019-10-10&st=2020-09-01T00%3A00%3A00Z&se=2050-09-01T00%3A00%3A00Z&si=prod&sr=c&sig=isafOa9tGnYBAvsXFUMDGMTbsG2z%2FShaihzp7JE5dHw%3D]
```

On checking with the URL directly, I see the "blob does not exist" error.

**Comment by mjhipp** [comment]
Also missing:
- snpEff_v5_1_hg38.zip
- snpEff_v5_1_mm10.zip
- snpEff_v5_0_NC001416.zip
- snpEff_v5_1_NC001416.zip

**Comment by sami-amer** [comment]
Similar issue when attempting to download genome data through bcbio, which uses the same snpEff links above as far as I can tell.

```
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'mm9', 'name': 'Mouse (mm9)', 'annotations': []}], 'genome_indexes': ['bwa', 'rtg', 'hisat2'], 'install_liftover': False, 'install_uniref': False}'): Mouse (mm9)
Installing snpEff database GRCm38.99 in /mnt/array/bcbio/genomes/Mmusculus/mm10/snpeff
--2022-02-24 20:11:18--  https://snpeff.blob.core.windows.net/databases/v4_3/snpEff_v4_3_GRCm38.99.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2022-02-24 20:11:18 ERROR 404: The specified blob does not exist..

Traceback (most recent call last):
  File "/mnt/array/bcbio/tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/array/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/array/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 363, in upgrade_bcbio_data
    _upgrade_snpeff_data(galaxy_home, args, remotes)
  File "/mnt/array/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 440, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "--no-check-certificate", "-c", "-O", dl_file, dl_url])
  File "/mnt/array/bcbio/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v4_3_GRCm38.99.zip', 'https://snpeff.blob.core.windows.net/databases/v4_3/snpEff_v4_3_GRCm38.99.zip']' returned non-zero exit status 8.
```

**Comment by splaisan** [comment]
I also fail to get the yeast database using snpEff v5.0

```
snpEff -download Saccharomyces_cerevisiae
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Saccharomyces_cerevisiae.zip
```

trying wget gives no blob

```
wget https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Saccharomyces_cerevisiae.zip
--2022-02-28 09:36:33--  https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Saccharomyces_cerevisiae.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2022-02-28 09:36:34 ERROR 404: The specified blob does not exist..
```

**Comment by MikeWLloyd** [comment]
```
singularity run snpeff_5.1--hdfd78af_1.sif snpEff download GRCh38.99 -dataDir .
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.99.zip
```

**Comment by RamRS** [comment]
You’re not doing anything wrong, the storage space is inaccessible.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by srs365** [comment]
> 

is this issue going to be resolved? or i won't ever be able to use snpeff?

**Comment by RamRS** [comment]
We're yet to hear from the developer.

**Comment by splaisan** [comment]
when you succeed to create your own local database from scratch (genome fasta and GTF files)
=> do not forget to add `-nodownload` to your command so that snpEff does not try to download it first.
This is working for me now for my home-made chicken genome.

**Comment by srs365** [comment]
> when you succeed to create your own local database from scratch (genome fasta and GTF files)
> => do not forget to add `-nodownload` to your command so that snpEff does not try to download it first.
> This is working for me now for my home-made chicken genome.


at what point in the command do you add -nodownload? when building the database? or when running snpeff?

**Comment by pcingola** [comment]
I'm not sure what's going on but I'm investigating.
I'll be fixing these databases issues soon. Apologies for the long delay (things have been quite a bit hectic lately)

**Comment by RamRS** [comment]
No problem, glad you’re aware of the problem now!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by splaisan** [comment]
> > when you succeed to create your own local database from scratch (genome fasta and GTF files)
> > => do not forget to add `-nodownload` to your command so that snpEff does not try to download it first.
> > This is working for me now for my home-made chicken genome.
> 
> at what point in the command do you add -nodownload? when building the database? or when running snpeff?

when running snpeff, my example command is as follows:

```
build="GRCg6a.105"
java ${javaopts} -jar $SNPEFF/snpEff.jar \
 	-htmlStats ${outfolder}/freebayes_snpEff_summary.html \
 	-nodownload \
 	${build} \
 	${outfolder}/freebayes_merged_ID_cnt.vcf.gz | \
 	bgzip -c > ${outfolder}/freebayes_combined_7_snpeff.vcf.gz && \
 	tabix -p vcf ${outfolder}/freebayes_combined_7_snpeff.vcf.gz
```

**Comment by fallmake** [comment]
@pcingola - Appears to be down still or again. Is there a technical issue/question regarding Azure (might be able to assist) or is it organizational?

**Comment by pcingola** [comment]
Most databases have been (re)built/uploaded.

**Comment by srs365** [comment]
I am still having trouble running snpeff. 
i cannot create my own database with NC_012312.1 (Fundulus heteroclitus genome). I have tried the -nodownload command and still cannot get it to work. 
ive edited the snpeff.config file to have 
#Fundulus heteroclitus Mitochondrial genome
NC_012312.1.genome : Fundulus heteroclitus
NC_012312.1.codonTable : Vertebrate_Mitochondrial

Input- 
build="NC_012312.1" java -jar snpEff.jar -htmlStats summary.html -nodownload $build Users/ssierramartinez/Desktop/allpops/allbcftools.vcf 
Output- java.lang.RuntimeException: 	ERROR: Cannot read file '/Users/ssierramartinez/Desktop/software/snpEff/./data/NC_012312.1/snpEffectPredictor.bin'.

i have also tried 

Input -java -jar snpEff.jar -stats summary.html NC_012312.1 /Users/ssierramartinez/Desktop/allpops/allbcftools.vcf 
output- 00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_NC_012312.1.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_NC_012312.1.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_NC_012312.1.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_NC_012312.1.zip]

i am very confused. can someone please explain how to carry this out.

**Comment by pcingola** [comment]
@jamigo , @LGLGLTM , @RamRS , @sami-amer , @splaisan : The following genomes should be working OK by now:

    - [x] GRCh37.p13
    - [x] GRCh38.p13
    - [x] hg19
    - [x] hg38
    - [x] GRCh38.105
    - [x] GRCh38.99
    - [x] GRCm39.105
    - [x] GRCg6a.105
    - [x] GRCh38.mane.0.95.ensembl
    - [x] GRCh38.mane.1.0.ensembl
    - [x] mm9
    - [x] mm10
    - [x] Saccharomyces_cerevisiae

I've also added 33,000+ genomes from Ensembl / NCBI, so most of the requests should be there

**Comment by pcingola** [comment]
@mjhipp : To build NC_001416 you should use the utility script `buildDbNcbi.sh` in SnpEff's distro

```
./scripts/buildDbNcbi.sh NC_001416
```

**Comment by pcingola** [comment]
@srs365 : It looks like you did not build that database.

Maybe you can use `Fundulus_heteroclitus-3.0.2.105` from ENSEMBL, which is already pre-built

If that database is not good for your case, you can try following the steps on how to build a custom database from the documentation: http://pcingola.github.io/SnpEff/se_buildingdb/

**Comment by pcingola** [comment]
I'm closing this issue, since it should be all back to normal now.

**Comment by srs365** [comment]
@pcingola  I've been trying to build a custom data base and get errors. it will not let me create one, i have tried every command for building. please help. 
input: java -jar snpEff.jar build -gtf22 -v NC_012312.1
output: 00:00:00 SnpEff version SnpEff 5.1 (build 2022-01-21 06:23), by Pablo Cingolani
00:00:00 Command: 'build'
00:00:00 Building database for 'NC_012312.1'
00:00:00 Reading configuration file 'snpEff.config'. Genome: 'NC_012312.1'
00:00:00 Reading config file: /Users/ssierramartinez/Desktop/software/snpEff/snpEff.config
00:00:00 done
00:00:00 Reading GTF22 data file  : '/Users/ssierramartinez/Desktop/software/snpEff/./data/NC_012312.1/genes.gtf'
00:00:00 Reading file '/Users/ssierramartinez/Desktop/software/snpEff/./data/NC_012312.1/genes.gtf'
FATAL ERROR: Offending line (lineNum: 6): 'KN805525.1	ensembl	transcript	5114	76710	.	+	.	'
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
	at org.snpeff.interval.GffMarker.parse(GffMarker.java:268)
	at org.snpeff.interval.GffMarker.<init>(GffMarker.java:54)
	at org.snpeff.interval.Gtf2Marker.<init>(Gtf2Marker.java:26)
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGtf22.parse(SnpEffPredictorFactoryGtf22.java:23)
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.readGff(SnpEffPredictorFactoryGff.java:526)
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:342)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:404)
	at org.snpeff.SnpEff.run(SnpEff.java:1141)
	at org.snpeff.SnpEff.main(SnpEff.java:160)

input: java -jar snpEff.jar build -genbank -v NC_012312.1
output:
00:00:01 Create UTRs from CDS (if needed): 
00:00:01 Remove empty chromosomes: 
00:00:01 Marking as 'coding' from CDS information: 
00:00:01 Done: 0 transcripts marked
00:00:01 
00:00:01 Caracterizing exons by splicing (stage 1) : 
	00:00:01 Caracterizing exons by splicing (stage 2) : 
	00:00:01 done.
00:00:01 [Optional] Rare amino acid annotations
WARNING_FILE_NOT_FOUND: Rare Amino Acid analysis: Cannot read protein sequence file '/Users/ssierramartinez/Desktop/snpEff/./data/NC_012312.1/protein.fa', nothing done.
00:00:01 CDS check: GenBank file format, skipping
00:00:01 Protein check file: '/Users/ssierramartinez/Desktop/snpEff/./data/NC_012312.1/genes.gbk'
00:00:01 Checking database using protein sequences
00:00:01 Comparing Proteins...
	Labels:
		'+' : OK
		'.' : Missing
		'*' : Error
	*************00:00:01 
Protein check:	NC_012312.1	OK: 0	Not found: 0	Errors: 13	Error percentage: 100.0%
00:00:01 	Protein sequences comparison failed!
ERROR: Database check failed.
00:00:01 Logging
00:00:02 Checking for updates...
00:00:03 Done.

input: java -jar snpEff.jar build -gff3 -v NC_012312.1
00:00:00 [Optional] Rare amino acid annotations
WARNING_FILE_NOT_FOUND: Rare Amino Acid analysis: Cannot read protein sequence file '/Users/ssierramartinez/Desktop/software/snpEff/./data/NC_012312.1/protein.fa', nothing done.
ERROR: CDS check file '/Users/ssierramartinez/Desktop/software/snpEff/./data/NC_012312.1/cds.fa' not found.
ERROR: Protein check file '/Users/ssierramartinez/Desktop/software/snpEff/./data/NC_012312.1/protein.fa' not found.
ERROR: Database check failed.
00:00:00 Logging
00:00:01 Checking for updates...
00:00:02 Done.

(there is more warning or errors with this build command)


input: java -jar snpEff.jar -stats all_summary.html NC_012312.1  /Users/ssierramartinez/Desktop/allpops/allbcftools.vcf 
output: 00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_NC_012312.1.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_NC_012312.1.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_NC_012312.1.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_NC_012312.1.zip]

**Comment by RamRS** [comment]
@srs365 Your issue is only tangentially related to this thread - please see if you can open a new issue for this.

**Comment by srs365** [comment]
> @srs365 Your issue is only tangentially related to this thread - please see if you can open a new issue for this.

I've been a part of this thread, but okay. i added a new issue.

**Comment by RamRS** [comment]
Your first post was directly on point, but this custom database issue is not. That second issue has hijacked this thread from its main purpose - the absence of Azure blobs.

**Comment by pcingola** [comment]
@RamRS : Thank you. All the blobs should have been re-established by now. Please let re-open the issue if you don't see some of them.

**Comment by MikeWLloyd** [comment]
I was looking for a smaller genome to do some testing with. 
I get the missing blobs for all Bartonella quintana:
https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Bartonella_quintana_rm_11.zip

**Comment by pcingola** [comment]
It does work OK when I try to download:

```
$ snpeff download -v Bartonella_quintana_rm_11

00:00:00 SnpEff version SnpEff 5.1d (build 2022-04-19 15:49), by Pablo Cingolani
00:00:00 Command: 'download'
00:00:00 Reading configuration file 'snpEff.config'. Genome: 'Bartonella_quintana_rm_11'
00:00:00 Reading config file: /Users/pcingola/snpEff/snpEff.config
00:00:00 done
00:00:00 Downloading database for 'Bartonella_quintana_rm_11'
00:00:00 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Bartonella_quintana_rm_11.zip' to local file '/var/folders/s9/y0bgs3l55rj_jkkkxr2drz4157r1dz/T//snpEff_v5_1_Bartonella_quintana_rm_11.zip'
00:00:01 Connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Bartonella_quintana_rm_11.zip
00:00:01 Connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Bartonella_quintana_rm_11.zip, using proxy: false
00:00:02 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Bartonella_quintana_rm_11.zip
00:00:02 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Bartonella_quintana_rm_11.zip' to local file '/var/folders/s9/y0bgs3l55rj_jkkkxr2drz4157r1dz/T//snpEff_v5_0_Bartonella_quintana_rm_11.zip'
00:00:02 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Bartonella_quintana_rm_11.zip
00:00:02 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Bartonella_quintana_rm_11.zip, using proxy: false
00:00:02 Local file name: '/var/folders/s9/y0bgs3l55rj_jkkkxr2drz4157r1dz/T//snpEff_v5_0_Bartonella_quintana_rm_11.zip'
00:00:03
00:00:03 Download finished. Total 471992 bytes.
00:00:03 Extracting file 'data/Bartonella_quintana_rm_11/snpEffectPredictor.bin'
00:00:03 Unzip: OK
00:00:03 Deleted local file '/var/folders/s9/y0bgs3l55rj_jkkkxr2drz4157r1dz/T//snpEff_v5_0_Bartonella_quintana_rm_11.zip'
00:00:03 Done
00:00:03 Logging
00:00:04 Done.
```

Maybe it's a local issue in your setting?

**Comment by ynjane** [comment]
I'm having the same problem.

After custom building a new database  according to [http://pcingola.github.io/SnpEff/se_buildingdb/#step-2-option-3-building-a-database-from-gff-files](url) , when I want to annotate using `snpEFF.jar` , it return to me a `FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_roan.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_roan.zip]` . 

![image](https://user-images.githubusercontent.com/108174908/175768012-26905c57-58fb-49e0-9e53-7604fbcd355e.png)

My command is as follows:
`#build a new database
java -jar snpEff.jar build -gff3 -v roan

#run snpEFF
java -Xmx4G -jar snpEff.jar roan roan5.snp.filteragain.vcf.gz.recode.vcf > roan.eff.vcf`

I have also checked
`java -Xmx8g -jar snpEff.jar download -c snpEff.config -v roan` but still got the same error:
![image](https://user-images.githubusercontent.com/108174908/175768109-470b768d-9e13-42aa-98a1-2ecf0db3b571.png)

It looks like something going wrong with the blob core when connecting to customized databases. Could you please help?
@pcingola

**Comment by splaisan** [comment]
Hi @ynjane, please see my post on April 8th, you need to add **-nodownload** to your command to deactivate auto download.
Good luck!

**Comment by ynjane** [comment]
> Hi @ynjane, please see my post on April 8th, you need to add **-nodownload** to your command to deactivate auto download. Good luck!

thank you @splaisan ! 
 I have tried `-nodownload` just now, but it still can not work. 
My command line is `java -Xmx4G -jar /test/nyang/software/snpEff/snpEff.jar roan -nodownload roan5.snp.filteragain.vcf.gz.recode.vcf > roan.eff.vcf`
and the output returns:
![image](https://user-images.githubusercontent.com/108174908/175893584-734816e3-df8b-4074-99b6-3313edb8428a.png)

I'm not quite sure what's going wrong /(ㄒoㄒ)/~~

**Comment by splaisan** [comment]
I think you need to add your new database to the snpeff database conig file if I remember well, it is now crated but not yet addressed there (read the doc for that step and do not forget to select the correct codon usage).

**Comment by pcingola** [comment]
@ynjane The error message is saying that your custom database is not built (i.e. the "*.bin" file does not exist).
Most likely your built process failed for some reason (try to run the `build` command it with `-v` command-line option and pay attention to the error messages.

Note: By default, if the database doesn't exist locally, SnpEff will attempt to download it. In this case, since it is your own custom database, it obviously doesn't exist in the public databases repository, so it fails to download it.

**Comment by ynjane** [comment]
> @ynjane The error message is saying that your custom database is not built (i.e. the "*.bin" file does not exist). Most likely your built process failed for some reason (try to run the `build` command it with `-v` command-line option and pay attention to the error messages.
> 
> Note: By default, if the database doesn't exist locally, SnpEff will attempt to download it. In this case, since it is your own custom database, it obviously doesn't exist in the public databases repository, so it fails to download it.

@pcingola Thank you. I have tried `java -jar snpEff.jar build -gff3 -v roan` and there was no error messages. However, there is no "*.bin" file created. It was supposed to create a "snpEffectPredictor.bin" file in the /data fold, right?

And I tried this command line ` java -jar snpEff.jar build -gff3 -v roan > roan.log` , but instead of generating a separate log file, a bunch of running results were printed directly on the screen. Could you please help?
![image](https://user-images.githubusercontent.com/108174908/175978180-59a28a0a-c4c8-4585-852f-a0116dafc2b6.png)
