### ISSUE TITLE
Need some help to build custom genome

### ISSUE THREAD

**Issue by Abieskawa** [pcingola/SnpEff#378]
**Describe the issue**
Need some help to build custom genome

**To Reproduce**
1. SnpEff version: 5.1
2. Genome version: download from https://www.ncbi.nlm.nih.gov/genome/?term=sorghum+bicolor
3. SnpEff full command line: java -Xmx1G -jar snpEff.jar build -gff3 SorBic
4. Output / Error message: 
WARNING_GENE_NOT_FOUND: Gene 'null' (NC_012870.2:1683-2713) does not include 'rna-XM_002466004.2'    (NC_012870.2:11175-14887). Created new gene 'null.2' (NC_012870.2:11175-14887). File '/Users/kenhsu/snpEff/./data/SorBic/genes.gff' line 7	'NC_012870.2	Gnomon	transcript	11175	14887	.	-	.	ID=rna-XM_002466004.2;geneID=gene-LOC8059226;gene_name=LOC8059226'
WARNING_GENE_NOT_FOUND: Gene 'null' (NC_012870.2:1683-2713) does not include 'rna-XR_002452024.1' (NC_012870.2:22451-24160). Created new gene 'null.3' (NC_012870.2:22451-24160). File '/Users/kenhsu/snpEff/./data/SorBic/genes.gff' line 30	'NC_012870.2	Gnomon	transcript	22451	24160	.	-	.	ID=rna-XR_002452024.1;geneID=gene-LOC110434520;gene_name=LOC110434520'
...
java.lang.RuntimeException: Error reading file '/Users/kenhsu/snpEff/./data/SorBic/genes.gff'
java.lang.RuntimeException: Cannot find reference sequence.
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:359)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:404)
	at org.snpeff.SnpEff.run(SnpEff.java:1141)
	at org.snpeff.SnpEff.main(SnpEff.java:160)

**Expected behavior**
As posted on http://pcingola.github.io/SnpEff/examples/

**Data**
download from https://www.ncbi.nlm.nih.gov/genome/?term=sorghum+bicolor

**Additional context**
After downloaded from NCBI. I converted the file from .gtf to .gff, than moved to ~/snpEff/data/Sorbic
I did this conversion in Conda environment.
`Conda activate alignment_bo`
`gffread -E genes.gtf -o- > genes.gff`
then moved to the directory as the website tell me:
`java -Xmx1G -jar snpEff.jar build -gff3 SorBic`
In the beginning, it printed as follows:
`WARNING_GENE_NOT_FOUND: Gene 'null' (NC_012870.2:1683-2713) does not include 'rna-XM_002466004.2' (NC_012870.2:11175-14887). Created new gene 'null.2' (NC_012870.2:11175-14887). File '/Users/kenhsu/snpEff/./data/SorBic/genes.gff' line 7	'NC_012870.2	Gnomon	transcript	11175	14887	.	-	.	ID=rna-XM_002466004.2;geneID=gene-LOC8059226;gene_name=LOC8059226'
WARNING_GENE_NOT_FOUND: Gene 'null' (NC_012870.2:1683-2713) does not include 'rna-XR_002452024.1' (NC_012870.2:22451-24160). Created new gene 'null.3' (NC_012870.2:22451-24160). File '/Users/kenhsu/snpEff/./data/SorBic/genes.gff' line 30	'NC_012870.2	Gnomon	transcript	22451	24160	.	-	.	ID=rna-XR_002452024.1;geneID=gene-LOC110434520;gene_name=LOC110434520'
...
java.lang.RuntimeException: Error reading file '/Users/kenhsu/snpEff/./data/SorBic/genes.gff'
java.lang.RuntimeException: Cannot find reference sequence.
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:359)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:404)
	at org.snpeff.SnpEff.run(SnpEff.java:1141)
	at org.snpeff.SnpEff.main(SnpEff.java:160)
`
I hope someone can help me QQ.

**Comment by Abieskawa** [comment]
I followed what @arif.ashraf.opu said on https://www.biostars.org/p/359661/
After adding cds.fa and protein.fa in the SorBic directory, I still get 
FATAL ERROR: No CDS checked. This is might be caused by differences in FASTA file transcript IDs respect to database's transcript's IDs. 
I am not sure where to find correct transcript's IDs. I downloaded cds and protein file in .fna and .faa file (I renamed it as .fa)

Then I ran this:
java -Xmx4G -jar snpEff.jar SorBic ~/snpeff/vcfs/v9.call.vcf > /Volumes/MAC_WINDOWS/kenhsu/v9.snpeff.vcf
in the end, it still cannot run.

`ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_SorBic.zip
  00:00:01 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_SorBic.zip`

**Comment by LaraFuhrmann** [comment]
Dear Abieskawa, 
I am running into the exact same problem. Have you been able to solve the issue by now?
