### ISSUE TITLE
Error whilst trying to connect to database using version 5.1

### ISSUE THREAD

**Issue by antaralabiba97** [pcingola/SnpEff#379]
**Describe the issue**
I have an error that comes up when trying to annotate my vcf file. The error is: 
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.99.zip

**To Reproduce**
1. SnpEff version: 5.1
2. Genome version: GRCh38
3. SnpEff full command line: java -Xmx8g -jar snpEff.jar GRCh38.99 /Users/antaralabiba/Downloads/variants.vcf > variants.ann.vcf
4. Output / Error message: Please include detailed information, such as transcript ID, VCF line output, etc: 00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.99.zip

If you try to open 'https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.99.zip' this an error appears which explains why an error comes up when I try to run the above.  The same error appears whilst trying to run the example on this link http://pcingola.github.io/SnpEff/se_running/ when using version 5.1.

**Comment by RamRS** [comment]
There are a couple of issues that address this already. Please look through existing issues before opening new ones. See: #374 #377

**Comment by splaisan** [comment]
@pcingola please help your user base, we cannot download any genome since quite some time now due to the Azure storage being down.
Or at least let us know why this is broken.
thanks

**Comment by bcantarel** [comment]
Any update on this -- when I try it looks like some of the dbs ie GRCh38.99, GRCm38.99, loxAfr3.99 it gives an error for v5_1, but downloads from v5_0. 
`00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_$db.zip`
 
But for those dbs only in v5_1 ie mm39, you get a fatal error 
`00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_mm39.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_mm39.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_mm39.zip, https://snpeff.blob.core.windows.net`

I was able to build my own mm39, have not yet implementing the code put that into my snpEff docker container

**Comment by antaralabiba97** [comment]
Hello, is there any update on this error as this still has not been resolved when I try and access the GRCh38.99 database?

**Comment by pcingola** [comment]
Both GRCh38.99 and GRCh38.105 are working OK now.
Closing
