### ISSUE TITLE
Frame-shift stop is marked one AA earlier than it should by HGVS

### ISSUE THREAD

**Issue by yaarau** [pcingola/SnpEff#385]
SnpEff version: V5.0

Description:
The HGVS annotation for frame-shift stop is marked one AA earlier than it should.
See the following variants for example:
16	29825015	.	GCCCCCCCCC	GCCCCCCCCCC    (marked as p.Arg217fs*7 while it should be p.Arg217fs*8)
17	7660452	.	C	CT    (marked as p.Leu651fs*2 while it should be p.Leu651fs*3)
16	2158985	.	G	GT    (marked as p.Gln2062fs*18 while it should be p.Gln2062fs*19)

These are HGVS instructions:
the position of the translation termination (stop) codon in the new reading frame is calculated starting at the first amino acid changed by the frame shift (codon 1), and ending at the first stop codon encountered (Ter# or *#)
Taken from Varnomen: http://varnomen.hgvs.org/recommendations/protein/variant/frameshift/

Can you please fix the annotation?

**Comment by yaarau** [comment]
Sorry, irrelevant

**Comment by vyx-nir-neerman** [comment]
Would you mind elaborating how you were able to get snpEff to output the termination codon ? I'm only able to get the short-format https://github.com/pcingola/SnpEff/issues/409
