### ISSUE TITLE
ERROR: Database check failed

### ISSUE THREAD

**Issue by WenboLVCong** [pcingola/SnpEff#389]
**Describe the issue**
Dear SnpEff developers, 

I am using SnpEff version 5.1. I'd like to build my species' genome database, here is my cmd:
$java -jar snpEff.jar build -gff3 -v mp_Jap -c snpEff.config

I came with several errors:
![image](https://user-images.githubusercontent.com/102585136/160573676-fc0e3250-5290-4ffe-8405-031cd590a43e.png)
![image](https://user-images.githubusercontent.com/102585136/160573807-cd114ca0-c4f6-4671-a529-92d91bc1007a.png)

the cds.fa, protein.fa, genome sequences and gff3 files were all the original files downloaded from the public database website.
I guess that the cds.fa and protein.fa may be wrong. So I extracted the cds sequences from the gff3 file using my script, and re-run the cmd "java -jar snpEff.jar build -gff3 -v mp_Jap -c snpEff.config"

however, I still have the same error, i.e. "ERROR: Database check failed"

then I used the switch " -noCheckCds" and "-noCheckProtein". there is no errors when building the genome database.

so I run snpeff as follow:
$java -jar -Xmx100g -jar /mypath/snpEff.jar ann -nodownload -c /mypath/snpEff.config my.vcf > ann
no error reported. but when I check the annotation, I found something is wrong.
![image](https://user-images.githubusercontent.com/102585136/160576206-26064ff3-60af-4c0e-bfb0-09a02b3ccab7.png)

In the output of snpEff, snpEff said the snp located at 2261, G>A, Arg > Gln. 
acturally, the snp is at position 2263 of the CDS sequences, and the mutation should be Ala > Val. 
here is the gff3 of this genes
![image](https://user-images.githubusercontent.com/102585136/160576313-da83ff86-ecb5-49d2-aca6-b5840e1a4b59.png)

I was wondering why the coordinate of this snp was shifted by 2 base?

thank you very much!

Best regards,
Wenbo

**To Reproduce**
1. SnpEff version:
2. Genome version:
3. SnpEff full command line: 
4. Output / Error message: Please include detailed infomration, such as transcript ID, VCF line output, etc.

**Expected behavior**
A clear and concise description of what you expected to happen (show program's output for comparisson)

**Data**
Sample data. No need to add the full genomic dataset, but a few input lines enough to reproduce the conditions.
WARNING: Always attach the data files such as VCF lines.

**Additional context**

**Comment by pcingola** [comment]
SnpEff checks that the databases match the CDS and protein sequences whenever possible.

In this case, you are showing an error rate over 50%, which indicates that half the times the proteins and CDS sequences do NOT match the ones inferred from the GTF/FFF file (plus the reference genome).
This basically means that there are SEVERE errors in the files you are using, and SnpEff refuses to save the database to protect you from getting bad results when using the database to analyze variants.

In this case, running with the " -noCheckCds" and "-noCheckProtein" options will force SnpEff to ignore these errors, which is usually an extremely bad idea. You should fix your data sources instead.

Obviously, the annotations will be wrong if you use bad genomic data to build the database.
