### ISSUE TITLE
Inconsistency between amino acid information and alleles (reference/alternative) information

### ISSUE THREAD

**Issue by anilineblue** [pcingola/SnpEff#391]
I did SnpEff analysis with my vcf file, and I found some unexpected inconsistency between amino acid modification information and alleles (ref/alt).

For example, I have a variant with Met174Leu modification, and in this case, the expected nucleotide modification is A->C,
but the reference allele of this variant is T and the alternative allele here is G.

Do you know why this happens and how to interpret this situation?
I'm wondering if I misunderstood the result.

I look forward to hearing from you.
Thanks in advance!

**Comment by Kathatinka** [comment]
Hey, 
I would think the nucleotide modification is as expected, as the only difference of the sequence is the DNA strand you are looking at. The Adenine (A) matches with the Thymine (T) on the other DNA strand and the Cytosine (C) matches with the Guanine (G).
