### ISSUE TITLE
Choose snpEff release to download (especially release 5.0e)

### ISSUE THREAD

**Issue by antonylebechec** [pcingola/SnpEff#392]
Hi!

First, thanks for your software snpEff!

Is there a way to download a specific release of snpEff?

As I need to clearly trace the release I use, and sometimes I'm re-creating Docker image, if I use "snpEff_latest_core.zip" I don't know the release I'm downloading. Especially, I want to use "5.0e" release.

Thanks for your help!

**Comment by kapsakcj** [comment]
+1 

I too would love to pin a specific version of SnpEff in a docker image and I think the only way to download the latest release is via https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip

**Comment by bpow** [comment]
I couldn't find it documented anywhere, but based on how the filenames ended up back in the sourceforge days, I tried https://snpeff.blob.core.windows.net/versions/snpEff_v5_0e_core.zip and it worked for that particular version. Replacing `.` with `_` in the version name will hopefully allow for other versions to be downloaded as well.
