### ISSUE TITLE
Request of Database of the king penguin genome (Aptenodytes patagonicus)

### ISSUE THREAD

**Issue by fernandes-flavia** [pcingola/SnpEff#393]
### Database requests

1. Organism name: Aptenodytes patagonicus (King penguin)
2. Link gene definition file (e.g. GTF / GFF / GenBank): https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/087/175/GCA_010087175.1_BGI_Apat.V1/[GCA_010087175.1_BGI_Apat.V1_genomic.gff.gz
3. Link to Genome FASTA file/s: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/087/175/GCA_010087175.1_BGI_Apat.V1/GCA_010087175.1_BGI_Apat.V1_genomic.fna.gz
4. Link to CDS FASTA file: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/087/175/GCA_010087175.1_BGI_Apat.V1/GCA_010087175.1_BGI_Apat.V1_cds_from_genomic.fna.gz
5. Link to Protein FASTA file: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/087/175/GCA_010087175.1_BGI_Apat.V1/GCA_010087175.1_BGI_Apat.V1_protein.faa.gz

### Feature requests

Hello,
I am trying to build a database of the king penguin genome myself in the lastest version of SnpEff (5.1) installed in our lab cluster (Centos7) by following the guidelines in the SnpEff website, but with no success. I have downloaded the reference files of the annotation, cds, and protein (indicated above), renamed them (e.g., genes.gff, protein.fa), decompressed, and moved to the directory /data/BGI_Apat.V1, which I created for this database. The decompressed reference genome fasta was also moved to /data/genomes and renamed as BGI_Apat.V1.fa. I also added the following lines to the snpEff.config file:

\# King penguin genome, version BGI_Apat.V1
BGI_Apat.V1.genome : Aptenodyes_patagonicus

and ran the command to build the database as follows:

$ java -jar path/to/snpEff/snpEff.jar build -dataDir path/to/data -gff3 -v BGI_Apat.V1

The command runs with no problem (no error), but no database is built, no snpEffectPredictor.bin is created, so when I try running the snpEff.jar to annotate one of my vcf files, it gives an error saying that there is nothing in this database.  
I have already tried with both the .gtf and the .gff annotation files, with and without the protein.fa and cds.fa files (with the -noCheckCds flag in the later), but the result is always the same. 

I would like if the developing team could build this database or give me a better description of what I could be doing wrong.

Thank you!

**Comment by pcingola** [comment]
OK, I've fixed those genomics files, created the database, and uploaded it.

You can add the following line to your `snpEff.config`
```
BGI_Apat.V1.genome: Aptenodytes patagonicus
```

Then you can download the genome:
```
java -jar snpEff.jar download -v BGI_Apat.V1
```
IMPORTANT: Make sure you are using the latest SnpEff version (5.1 c or higher)


What was happening? The genomic files have several issues that need to be fixed, but the main ones were:

1) transcript ids do not match the headers from the cds file
2) same issue for the proteins file

Enjoy
