### ISSUE TITLE
Effects by regions

### ISSUE THREAD

**Issue by weihongqi** [pcingola/SnpEff#395]
**Describe the issue**
Transcripts in Effects by regions

<img width="435" alt="image" src="https://user-images.githubusercontent.com/8567021/163974247-ad897491-39f4-4a67-857e-8acf38519907.png">

What's the meaning of "Transcripts" here?

**Comment by pcingola** [comment]
This refers to effects such as:
```
TRANSCRIPT_DELETED
TRANSCRIPT_DUPLICATION
TRANSCRIPT_INVERSION
INTRAGENIC
NEXT_PROT
TRANSCRIPT
CDS
```
More details on each effect type can be found here: http://pcingola.github.io/SnpEff/se_inputoutput/#effect-prediction-details

I hope this clarifies a bit.
