### ISSUE TITLE
Request of Database of Brassica napus 

### ISSUE THREAD

**Issue by Warceline** [pcingola/SnpEff#399]
Thank you for your time in maintaining Snpeff,
Snpeff is very friendly to people who only have biological background .However, it is difficult for me to build a new  database.
Hope to get your help to establish a database of Brassica napus. 
The relevant information required is as follows:

Name of the species： Brassica napus [Taxonomy ID: 3708]
Reference genome version：Darmor_v8 
Reference ：Bayer PE, Hurgobin B, Golicz AA, et al. Assembly and comparison of two closely related Brassica napus genomes. Plant Biotechnol J. 2017;15(12):1602-1610. doi:10.1111/pbi.12742  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5698052/

A link to the reference genome sequence (i.e. a link to the FASTA file)： http://appliedbioinformatics.com.au/download/DarmorTapidor/Darmor_v81_assembly.fasta.gz

A link to a gene and transcript definition file (either GTF, GFF, GenBank, etc.) ：http://appliedbioinformatics.com.au/download/DarmorTapidor/Darmor_v81_assembly.augustus_masked.propermodels.sorted.renamed.gff.gz

At least one of the following (preferably, both):
A link to the CDS sequences (FASTA file) ：http://appliedbioinformatics.com.au/download/DarmorTapidor/Darmor_v81_assembly.all.maker.augustus_masked.transcripts.renamed.fasta.gz
A link to the protein sequences (FASTA files) ：http://appliedbioinformatics.com.au/download/DarmorTapidor/Darmor_v81_assembly.all.maker.augustus_masked.proteins.renamed.fasta.gz

Codon table information (take a look a the codon tables in snpEff.config file):
Which codon table does the organism use? (e.g. codon.Standard or codon.Mycoplasma)  codon.Standard
Specific codon tables used by some chromosomes (e.g. chromosome 'MT' uses codon.Vertebrate_Mitochondrial table) All chromosomes use  codon.Standard

Looking forward to your reply.

**Comment by SquashMeister** [comment]
I solved the same problem with this helpful post:
https://www.biostars.org/p/359661/
It walks you through a Zea_mays_B73 example towards the end

**Comment by pcingola** [comment]
Closing solved issue. Thank you!
