### ISSUE TITLE
Request the most recent documentation for mapping "Effects by type" to "Effects by region"

### ISSUE THREAD

**Issue by yuweibao15** [pcingola/SnpEff#403]
Under the most recent version's output html file, I would like to find out what effects correspond to genomic region EXON. I tried to follow the documentation https://pcingola.github.io/SnpEff/se_outputsummary/

But I found the Effect Type - Region table doesn't match the current version entires. Could you point out where can I find the most current documentation? 

Thank you very much!

**Comment by pcingola** [comment]
Here is the detailed mapping:

https://github.com/pcingola/SnpEff/blob/157a5d2ef06fb2a052b7a76201f5e7cffb35f7f0/src/main/java/org/snpeff/snpEffect/EffectType.java#L171
