### ISSUE TITLE
inconsistent number of intron and variants

### ISSUE THREAD

**Issue by MarineBergot** [pcingola/SnpEff#406]
Hi! Maybe it's not a bug and more a question but i can't see that in the description of the summary. I was trying multiQC then i asked a CSV summary, i can't understand how it's possible to get Number_of_variants_before_filter, 63807 but 84018 introns? 

how are you counting the number of intron? Transcript are counted several times? thanks for your answer :) 

snpEff version SnpEff 4.3t 
genome version : hg38
/soft/java/jdk_x64/bin/java -XX:ParallelGCThreads=1 -Xmx4g -jar /work/gad/shared/bin/snpEff/snpEff.jar -csvStats dijex7547_snpeff_rapport.csv -c /work/gad/shared/bin/snpEff/snpEff.config -no-downstream -no-upstream -no-intergenic -noMotif -noNextProt -noInteraction hg38 /work/gad/shared/analyse/PJ2203094/dijex7547/dijex7547.filter.vcf

# Summary table 

Name , Value
Genome , hg38 
Date , 2022-05-17 10:17
SnpEff_version , SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
Command_line_arguments , SnpEff  -csvStats dijex7547_snpeff_rapport.csv -no-downstream -no-upstream -no-intergenic hg38 /work/gad/shared/analyse/PJ2203094/dijex7547/dijex7547.filter.vcf 
Warnings , 17333 
Number_of_lines_in_input_file, 56786
Number_of_variants_before_filter, 63807
Number_of_not_variants , 0
Number_of_variants_processed , 63807
Number_of_known_variants (i.e. non-empty ID) , 63137, 98.949958% 
Number_of_effects , 185792 
Genome_total_length ,3209286106 
Genome_effective_length ,3031042417 
Change_rate , 47503

# Count by genomic region

Type , Count , Percent 
DOWNSTREAM , 14540 , 7.825956% 
EXON , 56869 , 30.608961% 
INTERGENIC , 529 , 0.284727% 
INTRON , 84018 , 45.221538% 
SPLICE_SITE_ACCEPTOR , 366 , 0.196994% 
SPLICE_SITE_DONOR , 163 , 0.087733% 
SPLICE_SITE_REGION , 10287 , 5.536837% 
TRANSCRIPT , 11 , 0.005921% 
UPSTREAM , 10613 , 5.712302% 
UTR_3_PRIME , 4563 , 2.455972% 
UTR_5_PRIME , 3833 , 2.06306%

**Comment by pcingola** [comment]
The short answer is that it "may be depending on the number of transcripts per gene in your organism".
hopefully this link to the documentation's FAQ is helpful:

https://pcingola.github.io/SnpEff/se_faq/#number-of-variants-in-vcf-and-html-summary-do-not-match
