### ISSUE TITLE
Could you please clarify the SnpEff and SnpSift license

### ISSUE THREAD

**Issue by Fred2023** [pcingola/SnpEff#407]
Github lists the MIT license for both packages. However, this page https://pcingola.github.io/SnpEff/download/  states the license for both is LGPLv3.  Could you please confirm the MIT license and make both web pages the same so there is no confusion or doubt?  Thanks very much.

**Comment by Fred2023** [comment]
@pcingola Could you please address this issue?  Thank you.

**Comment by pcingola** [comment]
Fixed. The page was updated.
Thank you for the heads-up
