### ISSUE TITLE
Long HGVS frameshift nomenclature

### ISSUE THREAD

**Issue by vyx-nir-neerman** [pcingola/SnpEff#409]
SnpEff version: 5.1
Genome version: hg38
I am only able to get the HGVS.p field to populate with the short frameshift format, for example
```
chr10	71646593	.	G	GG	30	PASS	AC=1;AF=0.500;AN=2	GT:AD:DP:GQ:PL	0/1:38,10:48:99:303,0,1608
```

returns "p.Thr477fs":
```
GG|frameshift_variant|HIGH|CDH23|CDH23|transcript|NM_022124.6|protein_coding|13/68|c.1428dupG|p.Thr477fs|1833/11138|1429/10065|477/3354||
```

Is there a way to change the output to the long description, i.e. Thr477Aspfs*10 or Thr477AspfsTer10??

**Comment by DavidStreid** [comment]
I do not see any way a terminal position could be added in the [HgvsProtein::toString()](https://github.com/pcingola/SnpEff/blob/ea4d5033d09a457760b3ac8e90eb3ca5edbcdcd2/src/main/java/org/snpeff/snpEffect/HgvsProtein.java#L524) method. 
It looks a suffix with this information might have been part of this commit, but was left always blank
[HGVSProtein commit, v4.3a](https://github.com/pcingola/SnpEff/commit/25bd38e5d2f80ce6e53d3854b09dab6126683679#diff-e673f14b221418d3eeef0b47642f749c9ec454a0b5f9827619ca3db8623ad24e) 

I am also very interested in getting terminal position of a frameshift mutation in the output. Please let me know if this is possible or there are plans to include this in future releases. Thank you.”

**Comment by DavidStreid** [comment]
I do not see any way a terminal position could be added in the [HgvsProtein::toString()](https://github.com/pcingola/SnpEff/blob/ea4d5033d09a457760b3ac8e90eb3ca5edbcdcd2/src/main/java/org/snpeff/snpEffect/HgvsProtein.java#L524) method. 
It looks a suffix with this information might have been part of this commit, but was left always blank
[HGVSProtein commit, v4.3a](https://github.com/pcingola/SnpEff/commit/25bd38e5d2f80ce6e53d3854b09dab6126683679#diff-e673f14b221418d3eeef0b47642f749c9ec454a0b5f9827619ca3db8623ad24e) 

I am also very interested in getting terminal position of a frameshift mutation in the output. Please let me know if this is possible or there are plans to include this in future releases. Thank you.

**Comment by pstawinski** [comment]
Hi @pcingola,

I noticed this issue was marked as "completed" on Dec 5, 2023, but I couldn't find evidence of the terminal position for a frameshift mutation being implemented in the code. Could you clarify if this was marked as completed because:

1. It has been implemented, and I might have missed the changes or documentation explaining how to use it.
2. It was decided not to implement this feature, and "completed" reflects closure without implementation.

Thank you for your time and for clarifying!

**Comment by pstawinski** [comment]
Hi @pcingola  just a kind reminder about this question. Any updates or thoughts? Thanks!
