### ISSUE TITLE
build databse error 

### ISSUE THREAD

**Issue by kdyoung100** [pcingola/SnpEff#412]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. SnpEff version: 5.1
2. Genome version: 
3. SnpEff full command line:  snpEff build -gff3 -v Mycobacterium 
Exons created for 3906 transcripts.
00:00:00 Deleting redundant exons (if needed): 
00:00:00 	Total transcripts with deleted exons: 0
00:00:00 Collapsing zero length introns (if needed): 
00:00:00 	Total collapsed transcripts: 0
00:00:00 	Reading sequences   :
00:00:00 	FASTA file: '/home/tools/anaconda3/share/snpeff-5.1-0/./data/genomes/Mycobacterium.fa' not found.
00:00:00 	Reading FASTA file: '/home/tools/anaconda3/share/snpeff-5.1-0/./data/Mycobacterium/sequences.fa'
00:00:00 		Reading sequence 'NC_000962.3', length: 4411532
00:00:00 		Adding genomic sequences to genes: 
00:00:01 	Done (3090 sequences added).
00:00:01 		Adding genomic sequences to exons: 
00:00:01 	Done (3976 sequences added, 0 ignored).
00:00:01 	Total: 3976 sequences added, 0 sequences ignored.
00:00:01 Finishing up genome
00:00:01 Adjusting transcripts: 
00:00:01 Adjusting genes: 
WARNING_GENE_COORDINATES: Gene 'gene-Rv0614' (name:'Rv0614'), adjusting start coordinate from 709355 to 709598
WARNING_GENE_COORDINATES: Gene 'gene-Rv0863' (name:'Rv0863'), adjusting start coordinate from 962598 to 962679
WARNING_GENE_COORDINATES: Gene 'gene-Rv0229c' (name:'Rv0229c'), adjusting end coordinate from 274985 to 274718
00:00:01 Adjusting chromosomes lengths: 
00:00:01 Ranking exons: 
00:00:01 Create UTRs from CDS (if needed): 
00:00:01 Correcting exons based on frame information.
	
WARNING_FRAMES_ZERO: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.
00:00:01 
00:00:01 Remove empty chromosomes: 
00:00:01 Marking as 'coding' from CDS information: 
00:00:01 Done: 0 transcripts marked
00:00:01 
00:00:01 #-----------------------------------------------
# Genome name                : 'Mycobacterium'
# Genome version             : 'Mycobacterium'
# Genome ID                  : 'Mycobacterium[0]'
# Has protein coding info    : true
# Has Tr. Support Level info : true
# Genes                      : 4008
# Protein coding genes       : 3951
#-----------------------------------------------
# Transcripts                : 4006
# Avg. transcripts per gene  : 1.00
# TSL transcripts            : 0
#-----------------------------------------------
# Checked transcripts        : 
#               AA sequences :      0 ( 0.00% )
#              DNA sequences :      0 ( 0.00% )
#-----------------------------------------------
# Protein coding transcripts : 3951
#              Length errors :     35 ( 0.89% )
#  STOP codons in CDS errors :      8 ( 0.20% )
#         START codon errors :   1368 ( 34.62% )
#        STOP codon warnings :     10 ( 0.25% )
#              UTR sequences :      0 ( 0.00% )
#               Total Errors :   1368 ( 34.62% )
# WARNING                    : No protein coding transcript has UTR
#-----------------------------------------------
# Cds                        : 3906
# Exons                      : 3976
# Exons with sequence        : 3976
# Exons without sequence     : 0
# Avg. exons per transcript  : 0.99
#-----------------------------------------------
# Number of chromosomes      : 1
# Chromosomes                : Format 'chromo_name size codon_table'
#		'NC_000962.3'	4411532	Standard
#-----------------------------------------------

00:00:01 Caracterizing exons by splicing (stage 1) : 
	...
00:00:01 Caracterizing exons by splicing (stage 2) : 
	...00:00:01 done.
00:00:01 [Optional] Rare amino acid annotations
WARNING_FILE_NOT_FOUND: Rare Amino Acid analysis: Cannot read protein sequence file '/home/tools/anaconda3/share/snpeff-5.1-0/./data/Mycobacterium/protein.fa', nothing done.
ERROR: CDS check file '/home/tools/anaconda3/share/snpeff-5.1-0/./data/Mycobacterium/cds.fa' not found.
ERROR: Protein check file '/home/tools/anaconda3/share/snpeff-5.1-0/./data/Mycobacterium/protein.fa' not found.
ERROR: Database check failed.
why failed?

**Comment by pcingola** [comment]
For NCBI GeneBan files, you can just use the simple `buildDbNcbi.sh` script

Here is the documentation: http://pcingola.github.io/SnpEff/se_faq/#how-to-building-an-ncbi-genome-genbank-file

Example for your genome `NC_000962.3`, you can build the database by running this one line:

```
$ ./scripts/buildDbNcbi.sh NC_000962.3 2>&1

Downloading genome NC_000962.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

00:00:00 SnpEff version SnpEff 5.1d (build 2022-04-19 15:49), by Pablo Cingolani
00:00:00 Command: 'build'
00:00:00 Building database for 'NC_000962.3'
00:00:00 Reading configuration file 'snpEff.config'. Genome: 'NC_000962.3'
00:00:00 Reading config file: /Users/pcingola/snpEff/snpEff.config
00:00:01 done
00:00:02 Chromosome: 'NC_000962.3'  length: 4411532
00:00:02 Create exons from CDS (if needed):
............................................
00:00:02 Deleting redundant exons (if needed):
00:00:02    Total transcripts with deleted exons: 0
00:00:02 Collapsing zero length introns (if needed):
00:00:02    Total collapsed transcripts: 0
00:00:02        Adding genomic sequences to genes:
00:00:02    Done (3090 sequences added).
00:00:02        Adding genomic sequences to exons:
00:00:02    Done (3906 sequences added, 0 ignored).
00:00:02 Finishing up genome
00:00:02 Adjusting transcripts:
00:00:02 Adjusting genes:
WARNING_GENE_COORDINATES: Gene 'Rv0229c' (name:'Rv0229c'), adjusting end coordinate from 274985 to 274718
WARNING_GENE_COORDINATES: Gene 'Rv0614' (name:'Rv0614'), adjusting start coordinate from 709355 to 709598
WARNING_GENE_COORDINATES: Gene 'Rv0863' (name:'Rv0863'), adjusting start coordinate from 962598 to 962679
00:00:02 Adjusting chromosomes lengths:
00:00:02 Ranking exons:
00:00:02 Create UTRs from CDS (if needed):
00:00:02 Remove empty chromosomes:
00:00:02 Marking as 'coding' from CDS information:
00:00:02 Done: 0 transcripts marked
00:00:02
00:00:02 Caracterizing exons by splicing (stage 1) :
    ...
00:00:02 Caracterizing exons by splicing (stage 2) :
    ...00:00:02 done.
00:00:02 [Optional] Rare amino acid annotations
WARNING_FILE_NOT_FOUND: Rare Amino Acid analysis: Cannot read protein sequence file '/Users/pcingola/snpEff/./data/NC_000962.3/protein.fa', nothing done.
00:00:02 CDS check: GenBank file format, skipping

00:00:02 Protein check file: '/Users/pcingola/snpEff/./data/NC_000962.3/genes.gbk'

00:00:02 Checking database using protein sequences
00:00:02 Comparing Proteins...
    Labels:
        '+' : OK
        '.' : Missing
        '*' : Error
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    +++++++00:00:02

    Protein check:  NC_000962.3 OK: 3906    Not found: 0    Errors: 0   Error percentage: 0.0%
00:00:02 Saving database
00:00:04 Saving sequences for chromosome 'NC_000962.3' to file '/Users/pcingola/snpEff/./data/NC_000962.3/sequence.NC_000962.3.bin'
00:00:05 [Optional] Reading regulation elements: GFF
WARNING_FILE_NOT_FOUND: Cannot read optional regulation file '/Users/pcingola/snpEff/./data/NC_000962.3/regulation.gff', nothing done.
00:00:05 [Optional] Reading regulation elements: BED
00:00:05 Cannot find optional regulation dir '/Users/pcingola/snpEff/./data/NC_000962.3/regulation.bed/', nothing done.
00:00:05 [Optional] Reading motifs: GFF
WARNING_FILE_NOT_FOUND: Cannot open PWMs file /Users/pcingola/snpEff/./data/NC_000962.3/pwms.bin. Nothing done
00:00:05 Done
00:00:05 Logging
00:00:06 Checking for updates...
00:00:07 Done.

```
