### ISSUE TITLE
What's the relationship between "Functional_Classes" and "effects_type"?

### ISSUE THREAD

**Issue by fengzhuo17** [pcingola/SnpEff#416]
### requests

1. Organism name: Institute of modern physics, Chinese Academy of Sciences
2. Link gene definition file (e.g. GTF / GFF / GenBank): None
3. Link to Genome FASTA file/s: None
4. Link to CDS FASTA file: None
5. Link to Protein FASTA file: None

I want to known the effects_type which the functional_class contained.

e.g. ["stop_retained_variant","synonymous_variant"] might belong to "SILENT".
["splice_donor_variant","missense_variant"] might belong to "MISSENSE".

but I can't find a file or table to get the information in the official net.

**Comment by pcingola** [comment]
Added a small section to the documentataion.

http://pcingola.github.io/SnpEff/se_inputoutput/#functional-class

I hope this clarifies.
Thank you!
