### ISSUE TITLE
SNPeff job terminated randomly

### ISSUE THREAD

**Issue by manburst** [pcingola/SnpEff#424]
Dear Sir
I have used snpeff to annotate VCF file from whole exome sequencing with recommended command 
`java -jar -Xmx16g snpEff.jar -v -stats myvcf_summary.html GRCh37.75 myvcf.Filtered.Variants.vcf > myvcf.ann.Filtered.Variants.vcf`
snpeff run normally until they loaded sequence 22
Job is terminated

![image](https://user-images.githubusercontent.com/68594551/184564972-7a415dff-12e3-418c-93f9-3c75da1418b7.png)

I assume it might be running out of memory so increase them into `-Xmx32g` 
but this time they terminated at sequence 6 and sometimes terminated at sequence 3

![image](https://user-images.githubusercontent.com/68594551/184565395-1b322584-4763-4bf5-8ea1-243842b5dfc3.png)

Could you please suggest the soulution?

PS.I run snpeff in virtualbox ubuntu with 32gb of RAM
PS2. I have check `history` and it not show I snpeff command that I type in terminal

Thanks in advance
JK

**Comment by pcingola** [comment]
SnpEff runs ok on my laptop using -Xmx8G (i.e. only 8Gb of RAM). You seem to be using only 16G, that should be more than enough.

In any case, if this was a SnpEff issue or a "running out of memory" problem, the process would fail with the corresponding error (your SSH connection would not drop).

In my opinion, you are experiencing network / SSH connectivity issues that are completely unrelated to SnpEff.

**Comment by manburst** [comment]
Update
I have switch to run the same command directly on Ubuntu virutal box (not SSH or any remote connection) but it still gave me similar result.
The job terminated at sequence 18 and terminal is shutdown.

**Comment by pcingola** [comment]
Does it also terminate abruptly by disconnecting?
If so, I think this is a network issue, because Unix commands don't disconnect on failure, they exit and report the error.

Try running on your own laptop or using `nohup` to make sure the command continues if your ssh connection disconnects.

Could this be an SSH keep-alaive issue?

**Comment by pcingola** [comment]
Maybe you can share the VCF file so I can try to reproduce the error condition?

**Comment by manburst** [comment]
Dear Sir
Thanks for your quick reply.
I have change PC to run snpEff and it work perfectly without any job termination during run (with same command and vcf file).
I think it might not be error of snpEff but could be other which relate to that PC or something else.

JK.

**Comment by pcingola** [comment]
I'm glad to heat that it works.

**Comment by manburst** [comment]
Dear Sir

I have another question for snpsift
I am using snpsift for annotate vcf file by using clinvar, 1000 genome, dbnsfp and dbsnp as database for annotation.

Annotation with clincar 1000 genome and dbnsfp is work fine but it seem that SnpSift could not annotate the rsnumber from dbsnp154.
`java -jar SnpSift.jar annotate -id -v path/to/dbsnp path/to.vcf > out.vcf`
Here is output
`00:00:01 Annotating method: TABIX
10000   ....................................................................................................
20000   ....................................................................................................
30000   ....................................................................................................
40000   ....................................................................................................
50000   ....................................................................................................
60000   ....................................................................................................
70000   ....................................................................................................
80000   ....................................................................................................
90000   ....................................................................................................
100000  ....................................................................................................
110000  ....................................................................................................
120000  ..00:00:04 Done.
        Total annotated entries : 0
        Total entries           : 120264
        Percent                 : 0.00%
        Errors (bad references) : 0`

Ps. I have follow this protocol to rename chromosome number of dbsnp file
https://www.biostars.org/p/396813/
Here is the header of dbsnp154 (renamed chromosome)

![image](https://user-images.githubusercontent.com/68594551/190087053-0754bcd3-c6e0-4aa7-9d91-aa50f28cb0b5.png)



Thanks
JK
