### ISSUE TITLE
Frameshift mutations resulting in stop codons are not named as nonsense mutations, as recommended by HGVS

### ISSUE THREAD

**Issue by DavidStreid** [pcingola/SnpEff#426]
**Describe the issue**
--

**To Reproduce**
1. SnpEff version: 5.1
2. Genome version: GRCh38.104
3. SnpEff full command line: 

```
INPUT=...
OUTPUT=...

/opt/jdk-12.0.1/bin/java -jar snpEff_5.1/snpEff.jar \
  -v GRCh38.104 \
  -ss 3 \
  -no-downstream -quiet  \
  -fastaProt \
  -ud 2000 \
  ${INPUT} \
  > ${OUTPUT}
```

4. Output / Error message: Please include detailed infomration, such as transcript ID, VCF line output, etc.

`-fastaProt` output
```
>NM_001318484.1 Ref
MLEMRRGNISPAFWFLWLLLFGLLGPSSENTTAFTKGSDTTTASITGSETTMASTMASTSALTTGSKITTDSTTGSETTSASTMASTAAFTTGSETNTASTTDSGTTIASTRTFTTGSDTTTGSTAGSETIVASTTVSGTTTTFTIASTTVPETTMASSTTSTAGSEKTMASSIISETTMASTTGSETATVSTTGSETTTTSTASSEATKVSTTGSETTTASTAGSETTTTSTSMAGSEATTTSTADSKVITASSM
SSETTVAPAAGSNTTTASTTGSETTTILIKASETTTASTAGSETTTPSPTGSQTTIVSISGSEITTTSTAGSENTTVSSAGSGTTTASMAGSETTVSTAGSETTTVSITGTETTMVSAMGSETTTNSTTSSETTVTSTAGSETTTVSTVGSETTTAYTADSETTAASTTGSEMTTVFTAGSETITPSTAGSETTTVSTAGSETTTVSTTGSETTTASTAHSETTAASTMGSETTKVSTAGSETTVSTAGSETTAAS
TEDSETNTAFTEDSKTTTASTTGFETTAASTTGSEPTMASTMGSETTMASTIGPETTKVSTASSEVTTVFAAGSETIRASTVGSETTTVSTTGSETTTASIMGSETSTDSTTGSETTTASTEGSETTTASTEGSEATTVSTTGSETTTVSITDSETTTTCTEGSEMTAVSTTVFETTTASTEGSEITIASTSDSETTTASTEGSETTTVTTAGSETKTAYTTGSETTTASNTGLETTTVFTIGSDTTTASTEGSET
TAVSATGSEMTTVSTEGSENTTVSTTGSETTTVSTTGLETTTTSTEGSEMTTVSTTGAETTTDSTEGSGTTAASTAGSETTTVSTADSENTTASTADSETTSASTTGSETTTASTTSSETTTASTEGSETTTVSTTDSETTMVSTTGSERTITSTEGSETTTVSATGSETTVSTEGSGTTTVSITGSETTKVSTTGSETTTTSTEGSEITTASITGSETTTASTEGSETTTASTEGSETTSASTTGSETTTASTTS
SETTMASIMGSETTMASTIGSETTKVSTASSKMTTVFTENSETTIASTTASETTTVSTAGSETIPASTAGSETTTTTSTEGSETTTASTEGSETTTASTESSETTTATTIGSETTTASTEGSETTTTSTEGSETTTASTEGSEITTVSTTGSETTTASTEGSETTTASTEGSELTTVSTTGSETITVSAEGSETTTVTTMGSETTTASTAGSETTTVSTAGSETTTASIEGSETTTVSSTGSETTTVSTTGTETTI
TSTEGSETTTVTTAGSETTAVYTTGSETTTTSTEGSETTTVSTTGSETTTASTADLETTTVSTSGSGTTTASTAGSETTTVYITGSKTTTASTEGSEATTVSTTSSETTTASTTGSEMTTVFTTVSETTTVSTIGSEATTSSAAGSEATTTSTEGSETTTASTAGSETTTASTAGSETTTASTSGSETNTACTTGSETSTPSSAGSETNTAFIIGSESTIASTASLEPTATSLTGSETTTVSITASGATAASTTVS
STTFVLTKATDVSIQPITNTPMSGTRTTGTRLTASSSVTMAPGMDFTASAASHTVPGIVLNTSGLGTSTMGASSTTSAHGVRTTTGSTREPTSSTFQETGPVSMGTNTVSMSHTPTNVIKPSGYLQPWAIILISLAAVVAAVGLSVGLSFCLRNLFFPLRYCGIYYPHGHSHSLGLDLNLGLGSGTFHSLGNALVHGGELEMGHGGTHGFGYGVGHGLSHIHGDGYGVNHGGHYGHGGGH*...
>NM_001318484.1 Variant 6:31029210-31029213 Ref:CCAC Alt: HGVS.p:p.Ser1263fs
MLEMRRGNISPAFWFLWLLLFGLLGPSSENTTAFTKGSDTTTASITGSETTMASTMASTSALTTGSKITTDSTTGSETTSASTMASTAAFTTGSETNTASTTDSGTTIASTRTFTTGSDTTTGSTAGSETIVASTTVSGTTTTFTIASTTVPETTMASSTTSTAGSEKTMASSIISETTMASTTGSETATVSTTGSETTTTSTASSEATKVSTTGSETTTASTAGSETTTTSTSMAGSEATTTSTADSKVITASSMSSETTVAPAAGSNTTTASTTGSETTTILIKASETTTASTAGSETTTPSPTGSQTTIVSISGSEITTTSTAGSENTTVSSAGSGTTTASMAGSETTVSTAGSETTTVSITGTETTMVSAMGSETTTNSTTSSETTVTSTAGSETTTVSTVGSETTTAYTADSETTAASTTGSEMTTVFTAGSETITPSTAGSETTTVSTAGSETTTVSTTGSETTTASTAHSETTAASTMGSETTKVSTAGSETTVSTAGSETTAASTEDSETNTAFTEDSKTTTASTTGFETTAASTTGSEPTMASTMGSETTMASTIGPETTKVSTASSEVTTVFAAGSETIRASTVGSETTTVSTTGSETTTASIMGSETSTDSTTGSETTTASTEGSETTTASTEGSEATTVSTTGSETTTVSITDSETTTTCTEGSEMTAVSTTVFETTTASTEGSEITIASTSDSETTTASTEGSETTTVTTAGSETKTAYTTGSETTTASNTGLETTTVFTIGSDTTTASTEGSETTAVSATGSEMTTVSTEGSENTTVSTTGSETTTVSTTGLETTTTSTEGSEMTTVSTTGAETTTDSTEGSGTTAASTAGSETTTVSTADSENTTASTADSETTSASTTGSETTTASTTSSETTTASTEGSETTTVSTTDSETTMVSTTGSERTITSTEGSETTTVSATGSETTVSTEGSGTTTVSITGSETTKVSTTGSETTTTSTEGSEITTASITGSETTTASTEGSETTTASTEGSETTSASTTGSETTTASTTSSETTMASIMGSETTMASTIGSETTKVSTASSKMTTVFTENSETTIASTTASETTTVSTAGSETIPASTAGSETTTTTSTEGSETTTASTEGSETTTASTESSETTTATTIGSETTTASTEGSETTTTSTEGSETTTASTEGSEITTVSTTGSETTTASTEGSETTTASTEGSELTTVSTTGSETITVSAEGSETTTVTTMGSETTTASTAGSETTTVSTAGSETTTASIEGSETTTVS*...
```
Relevant VCF Line
```
chr6	31029209	.	TCCAC	T	...	PASS ...ANN=T|frameshift_variant|...`
```

**Expected behavior**
According to HGVS, it looks like FS mutations resulting in an termination codon should be named as nonsense. In this case, I believe the HGVS name should be `HGVS.p:p.Ser1263Ter` and not what was output above in the variant line of the `-fastaProt` output, `HGVS.p:p.Ser1263fs`
* "variants which introduce an immediate translation termination (stop) codon are described as nonsense variant" - [HGVS](https://varnomen.hgvs.org/recommendations/protein/variant/substitution/)

**Comment by DavidStreid** [comment]
With version 5.2 I'm still noticing the above mutation being annotated as `frameshift` instead of `nonsense`
```
$ cat input.txt
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr6	31029209	.	TCCAC	T	.	.	.
$ java -jar snpEff.jar -v hg38 input.txt > annotated.txt 2> log_cmd.txt
$ grep -oP 'p\.\w+(?=\|)' annotated.txt
p.Ser1263fs # was expecting p.Ser1263Ter
$ grep stop_gained annotated.txt
$ 
```

i.e. 
CURRENT: "ANN=T|**_frameshift_variant_**|HIGH|MUC22|MUC22.6|transcript|NM_001318484.1|protein_coding|3/5|c.3788_3791delCCAC|_**p.Ser1263fs**_"

EXPECTED: "ANN=T|**_stop_gained_**|HIGH|MUC22|MUC22.6|transcript|NM_001318484.1|protein_coding|3/5|c.3788_3791delCCAC|**_p.Ser1263Ter_**"
* Like what is annotated w/ [Mutalyzer](https://mutalyzer.nl/normalizer/NM_001318484.1:c.3788_3791delCCAC)

[input.txt](https://github.com/pcingola/SnpEff/files/13573853/input.txt)
[annotated.txt](https://github.com/pcingola/SnpEff/files/13573854/annotated.txt)
[log_cmd.txt](https://github.com/pcingola/SnpEff/files/13573852/log_cmd.txt)

**Comment by RaquelRomeroF** [comment]
Hi,

Did you managed to solve it? I am experiencing the same issue:

chr7    152247986       .       G       GT      1923.64 .     ANN=GT|frameshift_variant&stop_gained|HIGH|KMT2C|ENSG00000055609|transcript|ENST00000262189.11|protein_coding|14/59|c.2447dupA|**p.Tyr816fs**|2664/16860|2447/14736|816/4911||

where I would expect:

chr7    152247986       .       G       GT      1923.64 .     ANN=GT|frameshift_variant&stop_gained|HIGH|KMT2C|ENSG00000055609|transcript|ENST00000262189.11|protein_coding|14/59|c.2447dupA|**p.Tyr816Ter**|2664/16860|2447/14736|816/4911||

As it is recommended by the guides for frameshift variants:

"The shortest frameshift variant possible contains fsTer2; variants which introduce an immediate translation termination (stop) codon are described as nonsense variant"

Thanks a lot!
