### ISSUE TITLE
multithread function "-t" is not available in SnpEff v5.1 ?

### ISSUE THREAD

**Issue by hengyichina** [pcingola/SnpEff#429]
**Describe the issue**
When I used -t function in SnpEff v5.1, I think this function is not available now. But on the website "_Multithreaded: SnpEff has a multithreaded implementation. This allows to use several cores available in the local machine. It can be activated using the -t command line option." also have the description of how to use this function. I want to confirm that is this "-t" function involved in "-noStats" or it has become the default setting.

**To Reproduce**
1. SnpEff version: SnpEff 5.1d(build 2022-04-19)
2. Genome version: 
3. SnpEff full command line: java -jar snpEff.jar -t
4. Output / Error message: Unknown option "-t"

**Expected behavior**
Change the website document or make it clear.

**Additional context**
I also did not see some description in the update log.

**Comment by pcingola** [comment]
Yes, this functionality has been disabled due to some race conditions.
Unfortunately, I don't have the bandwidth to properly re-code this functionality at the moment.
