### ISSUE TITLE
custom database issue?

### ISSUE THREAD

**Issue by sekhwal** [pcingola/SnpEff#430]
Hi, 
I am trying to make a custom database of my genome(MH043954) using the command (snpEff build -genbank -v BCoVgenome). However, it shows the following error. Please help me to figure out.

-----

snpEff build -genbank -v BCoVgenome
00:00:00 SnpEff version SnpEff 5.1d (build 2022-04-19 15:49), by Pablo Cingolani
00:00:00 Command: 'build'
00:00:00 Building database for 'BCoVgenome'
00:00:00 Reading configuration file 'snpEff.config'. Genome: 'BCoVgenome'
00:00:00 Reading config file: /SnpEff_annotation/snpEff.config
00:00:00 Reading config file: /anaconda3/envs/variant-calling/share/snpeff-5.1-2/snpEff.config
00:00:00 done
00:00:00 Chromosome: 'MH043954.1'	length: 31016
00:00:00 Create exons from CDS (if needed): 
...........00:00:00 Exons created for 10 transcripts.
00:00:00 Deleting redundant exons (if needed): 
00:00:00 	Total transcripts with deleted exons: 0
00:00:00 Collapsing zero length introns (if needed): 
00:00:00 	Total collapsed transcripts: 0
00:00:00 		Adding genomic sequences to genes: 
00:00:00 	Done (8 sequences added).
00:00:00 		Adding genomic sequences to exons: 
00:00:00 	Done (11 sequences added, 0 ignored).
00:00:00 Finishing up genome
00:00:00 Adjusting transcripts: 
00:00:00 Adjusting genes: 
00:00:00 Adjusting chromosomes lengths: 
00:00:00 Ranking exons: 
00:00:00 Create UTRs from CDS (if needed): 
00:00:00 Remove empty chromosomes: 
00:00:00 Marking as 'coding' from CDS information: 
00:00:00 Done: 0 transcripts marked
00:00:00 
00:00:00 Caracterizing exons by splicing (stage 1) : 
	
00:00:00 Caracterizing exons by splicing (stage 2) : 
	00:00:00 done.
00:00:00 [Optional] Rare amino acid annotations
WARNING_FILE_NOT_FOUND: Rare Amino Acid analysis: Cannot read protein sequence file '/anaconda3/envs/variant-calling/share/snpeff-5.1-2/./data/BCoVgenome/protein.fa', nothing done.
00:00:00 CDS check: GenBank file format, skipping

00:00:00 Protein check file: '/anaconda3/envs/variant-calling/share/snpeff-5.1-2/./data/BCoVgenome/genes.gbk'

00:00:00 Checking database using protein sequences
00:00:00 Comparing Proteins...
	Labels:
		'+' : OK
		'.' : Missing
		'*' : Error
	++++++++++00:00:00 

	Protein check:	BCoVgenome	OK: 10	Not found: 0	Errors: 0	Error percentage: 0.0%
00:00:00 Saving database
00:00:00 Saving sequences for small chromosmes to file '/anaconda3/envs/variant-calling/share/snpeff-5.1-2/./data/BCoVgenome/sequence.bin'
00:00:00 [Optional] Reading regulation elements: GFF
WARNING_FILE_NOT_FOUND: Cannot read optional regulation file '/anaconda3/envs/variant-calling/share/snpeff-5.1-2/./data/BCoVgenome/regulation.gff', nothing done.
00:00:00 [Optional] Reading regulation elements: BED 
00:00:00 Cannot find optional regulation dir '/anaconda3/envs/variant-calling/share/snpeff-5.1-2/./data/BCoVgenome/regulation.bed/', nothing done.
00:00:00 [Optional] Reading motifs: GFF
WARNING_FILE_NOT_FOUND: Cannot open PWMs file /anaconda3/envs/variant-calling/share/snpeff-5.1-2/./data/BCoVgenome/pwms.bin. Nothing done
00:00:00 Done
00:00:00 Logging
00:00:01 Checking for updates...
00:00:02 Done.

**Comment by pcingola** [comment]
Sorry, I don't see any error in the messages posted.
It seems that SnpEff finished successfully and saved the database without problems.

Can you clarify what error are you talking about?

**Comment by sekhwal** [comment]
Thank you for reaching out to me. I think I have got the results.
