### ISSUE TITLE
Obviously the hg

### ISSUE THREAD

**Issue by dfc-1931475** [pcingola/SnpEff#431]
WHEN I run the command :
java -jar snpEff.jar download hg19
There is an error : 00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_hg19.zip.

It is obvious the blob resource can no be attached again. May u developers fix this fluent bug? How could the  Primary Azure blob storage always got down?

**Comment by maciejmotyka** [comment]
Same for hg19kg.
