### ISSUE TITLE
Need some help with the final result

### ISSUE THREAD

**Issue by Seanduu** [pcingola/SnpEff#432]
Why is the number of variants processed in my result 0? There is no corresponding comment information in the obtained vcf file.
Just like this:
![1667902800553](https://user-images.githubusercontent.com/103124666/200539228-e2af1d28-ea49-4a3f-9a45-1f7f31151a47.jpg)

**Comment by pcingola** [comment]
It looks like your input VCF file did not contain any variants. Either it was a corrupted VCF file or the lines do not describe variants. You should double-check your VCF file and make sure it follows the VCF format specification.
