### ISSUE TITLE
Filtering for transcripts based on ENSEMBL IDs (ENST...) for GRCh38

### ISSUE THREAD

**Issue by LGLGLTM** [pcingola/SnpEff#434]
Hello,

It's possible to filter variants annotations for impact on specific transcripts while using GRCh37 and ENST ids but not when using the latest genome version. Transcripts IDs need to be RefSeq IDs but the mapping from ENST to RefSeq is incomplete and I lose a lot of isoforms.

Why is that and is support for ENST IDs coming?

Best

**Comment by pcingola** [comment]
Genome versions 'hg39' (or `hg19`) use RefSeq IDs, whereas `GRCh38.NN` uses Ensembl IDs.

So if you want to filter by RefSeq, you can use hg38 and use the `-canonList` command line option to select a specific list of transcript IDs you want to annotate on.

Similarly, using `GRCh38.NN` you can use Ensembl id (`ENST*`).
