### ISSUE TITLE
pb with p.HGVS indel annotation

### ISSUE THREAD

**Issue by tomSimonet** [pcingola/SnpEff#435]
**Describe the issue**
A clear and concise description of what the issue is.
possibly wrong annotation p.HGVS, for indels, according to https://varnomen.hgvs.org/recommendations/protein/variant/delins/
**To Reproduce**
1. SnpEff version: 5.1d (build 2022-04-19 15:49)
2. Genome version: hg19
3. SnpEff full command line: `singularity exec annot.simg java -jar /opt/snpEff5.jar ann -v -c data/snpEff/5.1/snpEff.config hg19 test.vcf > test.ann.vcf`
4. Output / Error message: Please include detailed infomration, such as transcript ID, VCF line output, etc.
ANN=AGCA|missense_variant|MODERATE|AR|AR|transcript|NM_000044.6|protein_coding|1/8|c.167_170delTGCTinsAGCA|p.LeuLeu56GlnGln|1293/10667|167/2763|56/920||,...
**Expected behavior**
A clear and concise description of what you expected to happen (show program's output for comparisson)
something like `p.Leu55_Leu56delinsGlnGln`  ?
**Data**
Sample data. No need to add the full genomic dataset, but a few input lines enough to reproduce the conditions.
WARNING: Always attach the data files such as VCF lines.

**Additional context**
[test.vcf.gz](https://github.com/pcingola/SnpEff/files/10054806/test.vcf.gz)

**Comment by anergictcell** [comment]
Hey, I have the same issue. For the variant (hg19 coordinates)
```text
CHROM         POS           REF      ALT
chrX          23411488      TGA      CGG
```

snpEff returns `p.LeuLys618ProGlu`.  (Missense)
However, according to [HGVS](https://varnomen.hgvs.org/recommendations/protein/variant/delins/) this should be annotated as `p.Leu618_Lys619delinsProGlu`  (DelIns)
