### ISSUE TITLE
SnpEff and SnpSift 5.1d do not seem to support multi-threading

### ISSUE THREAD

**Issue by robertzeibich** [pcingola/SnpEff#438]
Is that correct that SnpEff and SnpSift do not support multi-threading? Is there a newer version, except from version 4.1, that supports multi-threading?

**Comment by slagelwa** [comment]
I'm curious about this too.  I seem to recall a version (5.0e?) that had it as an option, and something about a [Databricks fork/version](https://github.com/databricks/SnpEff).

It looks like the option has been available for quite some time in the code, and this commit removed the warning that it was unsupported and seems to include more multi-threading code:

https://github.com/pcingola/SnpEff/commit/35ef2c4caf5e30681b497c619fe7534c81518a42

which was then commented out in a commit a few days later:

https://github.com/pcingola/SnpEff/commit/be6e02e2991753d4951ae40d6df9bcb3215c5695
