### ISSUE TITLE
Failure to download database

### ISSUE THREAD

**Issue by amandahaponski** [pcingola/SnpEff#440]
Hello. I keep getting a blob error when SnpEff tries to download the GRCh37.87 reference genome database during execution of SnpEff v5.1. As a note it does seem that this error is occurring more and more often for me. It sometimes takes 2-3 tries before I can get the program to proceed.

Here is the command I use when running:
java -jar snpEff.jar -v -csvStats <filename> -s <filename>  -onlyProtein GRCh37.87 <inputfile>

The error also occurs if I just try to download the database with the following command:
java -jar snpEff.jar download GRCh37.87

Here is the log file that appears. Once it hits the end, the execution will not terminate unless I do so manually.
00:00:00 SnpEff version SnpEff 5.1 (build 2022-01-21 06:23), by Pablo Cingolani
00:00:00 Command: 'ann'
00:00:00 Reading configuration file '/snpEff/snpEff.config'. Genome: 'GRCh37.87'
00:00:00 Reading config file: /snpEff/snpEff.config
00:00:01 done
00:00:01 Reading database for genome version 'GRCh37.87' from file '/snpEff/./data/GRCh37.87/snpEffectPredictor.bin' (this might take a while)
00:00:01 Database not installed
	Attempting to download and install database 'GRCh37.87'
00:00:01 Reading configuration file '/snpEff/snpEff.config'. Genome: 'GRCh37.87'
00:00:01 Reading config file: /snpEff/snpEff.config
00:00:02 done
00:00:02 Downloading database for 'GRCh37.87'
00:00:02 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.87.zip' to local file '/tmp/snpEff_v5_1_GRCh37.87.zip'
00:00:02 Connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.87.zip
00:00:03 Connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.87.zip, using proxy: false
00:00:03 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh37.87.zip
00:00:03 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.87.zip' to local file '/tmp/snpEff_v5_0_GRCh37.87.zip'
00:00:03 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.87.zip
00:00:03 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.87.zip, using proxy: false
00:00:04 Local file name: '/tmp/snpEff_v5_0_GRCh37.87.zip'

**Comment by kellrott** [comment]
This seems to continue to be a problem. The command 
```
java -jar util/snpEff/snpEff.jar download GRCh38.86
```
Returns
```
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.86.zip
```

Trying the download link directly, I get 

```
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:755cc97d-101e-0046-1e66-2f26c8000000 Time:2023-01-23T20:08:35.6938533Z</Message>
</Error>
```

**Comment by RPINerd** [comment]
Glad I'm not the only one, still unable to connect to any v5.x databases. Just did a bit of sleuthing (aka google) and found that the datasets are now part of Azure Open Datasets as you can read more about here: https://learn.microsoft.com/en-us/azure/open-datasets/dataset-snpeff

It looks like in theory this is just a clone of sourceforge, but unfortunately sourceforge is missing all v5.x databases as well..

**Comment by RPINerd** [comment]
Checked again today and the 5.x databases are still AWOL on sourceforge..

**Comment by kellrott** [comment]
BTW, I hacked the original URL `https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.86.zip` to be version 5.0 ( `https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.86.zip` ) and was about to manually download the file. It seems to be working.

**Comment by RPINerd** [comment]
#451 just to ping someone else who was having issues, I tried today and while 5.1 are still down, it looks like 5.0 versions are magically available on the azure blobs.. I didn't do your hack to manually download, this was just using the `snpEff download GRCh38.86` command

**Comment by etwatson** [comment]
So, I am running into this issue as well. However I am using the 5.1 F version.

How should I proceed?

----
```
$ java  -jar snpEff.jar download  -v Tcas5.2
00:00:00 SnpEff version SnpEff 5.1f (build 2023-07-21 13:58), by Pablo Cingolani
00:00:00 Command: 'download'
00:00:00 Reading configuration file 'snpEff.config'. Genome: 'Tcas5.2'
00:00:00 Reading config file: /home/eric/repo/snpEff/snpEff.config
00:00:00 done
00:00:00 Downloading database for 'Tcas5.2'
00:00:00 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Tcas5.2.zip' to local file '/tmp/snpEff_v5_1_Tcas5.2.zip'
00:00:00 Connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Tcas5.2.zip
00:00:00 Connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Tcas5.2.zip, using proxy: false
00:00:01 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Tcas5.2.zip
00:00:01 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Tcas5.2.zip' to local file '/tmp/snpEff_v5_0_Tcas5.2.zip'
00:00:01 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Tcas5.2.zip
00:00:01 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Tcas5.2.zip, using proxy: false
00:00:01 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Tcas5.2.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_Tcas5.2.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Tcas5.2.zip]
```
