### ISSUE TITLE
can not find pre built database

### ISSUE THREAD

**Issue by wantingwei** [pcingola/SnpEff#444]
I am using the SnpEff version: Latest version 5.1 (2022-01-21), I could not find the pre build database that built by my lab member. Apparently other people is able to download this database. But I am not able to find on the server. I attache a photo below.  
<img width="486" alt="Screen Shot 2022-12-30 at 4 10 39 PM" src="https://user-images.githubusercontent.com/97980830/210114889-8940ffd3-a113-4781-92f6-67585fc6571d.png">

**Comment by RPINerd** [comment]
A bit late now, but judging by the way that failed, my guess is that something is misspelled or something to that effect..

Try searching for the database first with `java -jar snpEff.jar databases | grep "delta.*parent"` this should give you a nice list of all the database names, hopefully you'll find that the one you're looking for is simply named slightly differently (i.e. delta-parent-stock or delta_parent_latest)

**Comment by wantingwei** [comment]
Thank you so much for the reply! But I am still not able to find the database with the command you provide. Is that possible when my lab mates build the database, it is only stored locally and I would not able to access it?

**Comment by RPINerd** [comment]
I have only just started trying to work with this software so I'm not an expert by any means, but if your lab mates actually built the database themselves, you'll probably need to copy it from wherever they have it stored. When you build a new database following the instructions I don't think there are any mechanics for uploading it to the server where all the rest of them are stored
