### ISSUE TITLE
Building databases error: protein sequences comparison failed

### ISSUE THREAD

**Issue by wcoll010** [pcingola/SnpEff#461]
**Describe the issue**
I am getting a 'database check failed' for the protein sequence comparison when I build a new genome database. To build my new genome database (from GFF3 annotation file), I had to remove the protein sequence check ( -noCheckProtein) because it fails the check. The CDS check passes.

**To Reproduce**
1. SnpEff version: 5.1 
2. Genome version: I'm building a new database for my organism (https://bipaa.genouest.org/sp/daktulosphaira_vitifoliae/) 
3. SnpEff full command line: java -Xmx100G -jar $SNPEFF snpEff.jar build -gff3 -v dv 
4. Output / Error message: Please include detailed infomration, such as transcript ID, VCF line output, etc.: 
Protein check:	dv	OK: 0	Not found: 25825	Errors: 0	Error percentage: NaN%
00:00:53 	Protein sequences comparison failed!
ERROR: Database check failed.

**Expected behavior**
I was able to build a new genome database, but I needed to use -noCheckProtein , because the protein sequence comparison failed. The CDS sequence comparison passed. The genome database was functional (I ran 'java -Xmx100G -jar $SNPEFF snpEff.jar eff dv file.vcf > snpEff.vcf' successfully) but seems there is an underlying issue with protein information.

**Data**
reference genome fasta: https://bipaa.genouest.org/sp/daktulosphaira_vitifoliae/download/genome/v3.1/
protein fasta: https://bipaa.genouest.org/sp/daktulosphaira_vitifoliae/download/annotation/v3.2/OGS3.2_20180216_protein.fasta
GFF3 annotation file: https://bipaa.genouest.org/sp/daktulosphaira_vitifoliae/download/annotation/v3.2/OGS3.2_20180216.gff3

Example data (a few lines of data per file)
reference genome fasta: 
>scaffold1
TGAAACAGTCCCTGTGTCACACAGCCCCCCCTGTGGGTGGTGTCCCACCGCCGTCCTCAGGTGGCGACCGTGCCTTGGTT
CTGCTCTCCACATTTCATTT
TGGATCTGTGGAGAGGTTCCCCTCAGCTGTGGCCGTTATTGAGGGTGGCGGTTTCCTGGGTTCCTTTCCCTTACGTAACA
CACTTCCTCCCTTCCCTTTC

protein fasta: 
>DV3002316-PA gene=DV3002316
MDKNIEKPQNNELVTIRDPTDNLSEQDRELATLRRRIAELEGLNANNGTLGEPSTSKETATSENVDQESQ
DQLGAVADKIEGLKLRPEKLSGSQRRKLKRSRANMEGQKNLPKEGDKGTDDLKKSKGTEAQKPEDKGQEP
PCKKTHWVPTYRDVVTDDKKVALVLAGYPTNKLTTEQGLLIESCVGDLILSGTDGTDVPRFEDTRLTDGA

GFF3 annotation file: 
##gff-version 3
scaffold1       OGS3.2  gene    55870   57726   .       +       .       Alias=snap_masked-scaffold1-processed-gene-0.13;ID=DV3002321;Name=DV3002321;full_name=DV3002321

**Additional context**
I'm using a GFF3 annotation file (no GTF available) and genome/protein/CDS fasta files. I've confirmed standard codon usage should be used from my organism (hemipteran insect); I didn't specify condon usage in my snpEff.config file edit. Ive confirmed the gene CDS match the protien fasta sequences.

**Comment by wcoll010** [comment]
Eventually I found the gene names in the protein fasta file were different from the GFF annotation and CDS files ; I replaced the names to match and was able to pass the protein fasta check.

**Comment by JiaQHo** [comment]
Add '-noCheckProtein' to skip this step.
