### ISSUE TITLE
ann.vcf 'INFO' columns contain true variant then lots of additional information

### ISSUE THREAD

**Issue by CSmith950** [pcingola/SnpEff#474]
Hi all,

I am fairly new to snpEff and computational work in general and some help would be appreciated. 

In brief, I have done the following to produce the final ann.vcf file;

- Aligned paired-end reads to a specific bacterial reference genome (this genome is available in the snpEff database) using SMALT
- Sorted the bam output from SMALT and used bcftools mpileup and call to generate a .vcf.gz file of the variants 
- ran snpEff as follows:
 _`java -Xmx8g -jar /pathto/snpEff.jar /pathto/vcf.gz > outputfilename.ann.vcf`_

My issue is that the 'INFO' column of for each variant has a tonne of data which I do not understand why it is there or what it means. Below is an example of all text from the 'INFO' column for one of my variants, sorry if this is ugly. From checking the mpileup data using IGV, the 'synonymous variant', the first part following the ANN information, is true and this is the case for all other variant rows. I think the the rest of the output is other variants that are within a certain proximity upstream/downstream from the initial 'synonymous variant'. Is it possible to remove this output?

Any advice is greatly appreciated, if further information from me is required please let me know! Thanks in advance for your time. 

**The INFO field descriptor**
`##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">`

**Example INFO field for one of the variant rows**
DP=191;VDB=0.164002;SGB=0.693147;MQSBZ=0.190517;FS=0;MQ0F=0;AC=2;AN=2;DP4=0,0,105,86;MQ=57;ANN=A|synonymous_variant|LOW|M5005_SpyT0028|M5005_SpyT0028|transcript|M5005_SpyT00281.1|protein_coding|1/1|c.51G>A|p.Ser17Ser|51/88|51/88|17/28||WARNING_TRANSCRIPT_INCOMPLETE,
A|upstream_gene_variant|MODIFIER|sibA|M5005_Spy0017|transcript|AAZ50636.1|protein_coding||c.1511G>A|||||1511|,
A|upstream_gene_variant|MODIFIER|prsA.2|M5005_Spy0018|transcript|AAZ50637.1|protein_coding||c.2960G>A|||||2960|,
A|upstream_gene_variant|MODIFIER|recO|M5005_Spy0019|transcript|AAZ50638.1|protein_coding||c.4108G>A|||||4108|,
A|upstream_gene_variant|MODIFIER|plsX|M5005_Spy0020|transcript|AAZ50639.1|protein_coding||c.4966G>A|||||4966|
A|downstream_gene_variant|MODIFIER|M5005_SpyT0011|M5005_SpyT0011|transcript|M5005_SpyT00111.1|protein_coding||c.*4912G>A|||||4912|WARNING_TRANSCRIPT_INCOMPLETE
A|downstream_gene_variant|MODIFIER|M5005_SpyR0005|M5005_SpyR0005|transcript|M5005_SpyR0005-1.1|rRNA||n.*1714G>A|||||1714|,
A|downstream_gene_variant|MODIFIER|M5005_SpyR0006|M5005_SpyR0006|transcript|M5005_SpyR0006-1.1|rRNA||n.*1513G>A|||||1513|,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0012|M5005_SpyT0012|transcript|M5005_SpyT0012-1.1|protein_coding||c.*1423G>A|||||1423|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0013|M5005_SpyT0013|transcript|M5005_SpyT0013-1.1|protein_coding||c.*1333G>A|||||1333|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0014|M5005_SpyT0014|transcript|M5005_SpyT0014-1.1|protein_coding||c.*1229G>A|||||1229|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0015|M5005_SpyT0015|transcript|M5005_SpyT0015-1.1|protein_coding||c.*1142G>A|||||1142|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0016|M5005_SpyT0016|transcript|M5005_SpyT0016-1.1|protein_coding||c.*1059G>A|||||1059|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0017|M5005_SpyT0017|transcript|M5005_SpyT0017-1.1|protein_coding||c.*975G>A|||||975|WARNING_TRANSCRIPT_NO_START_CODON,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0018|M5005_SpyT0018|transcript|M5005_SpyT0018-1.1|protein_coding||c.*882G>A|||||882|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0019|M5005_SpyT0019|transcript|M5005_SpyT0019-1.1|protein_coding||c.*789G>A|||||789|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0020|M5005_SpyT0020|transcript|M5005_SpyT0020-1.1|protein_coding||c.*712G>A|||||712|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0021|M5005_SpyT0021|transcript|M5005_SpyT0021-1.1|protein_coding||c.*633G>A|||||633|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0022|M5005_SpyT0022|transcript|M5005_SpyT0022-1.1|protein_coding||c.*539G>A|||||539|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0023|M5005_SpyT0023|transcript|M5005_SpyT00231.1|pseudogene||n.*431G>A|||||431|,A|downstream_gene_variant|MODIFIER|M5005_SpyT0024|M5005_SpyT0024|transcript|M5005_SpyT0024-1.1|protein_coding||c.*344G>A|||||344|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0025|M5005_SpyT0025|transcript|M5005_SpyT0025-1.1|protein_coding||c.*251G>A|||||251|WARNING_TRANSCRIPT_INCOMPLETE,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0026|M5005_SpyT0026|transcript|M5005_SpyT00261.1|protein_coding||c.*168G>A|||||168|WARNING_TRANSCRIPT_MULTIPLE_STOP_CODONS,
A|downstream_gene_variant|MODIFIER|M5005_SpyT0027|M5005_SpyT0027|transcript|M5005_SpyT00271.1|protein_coding||c.*60G>A|||||60|WARNING_TRANSCRIPT_MULTIPLE_STOP_CODONS

**Comment by pcingola** [comment]
"My issue is that the 'INFO' column of for each variant has a tonne of data which I do not understand "

Yes, this is how the standard VCF specification works
