### ISSUE TITLE
Not available for download

### ISSUE THREAD

**Issue by axz91** [pcingola/SnpEff#475]
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_hs1.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_hs1.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_hs1.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_hs1.zip]   

Not available for download

**Comment by robertwhbaldwin** [comment]
Same here I wanted to download the C. gigas database:

java -jar snpEff.jar download C.gigas_roslin_v1
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_C.gigas_roslin_v1.zip
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_C.gigas_roslin_v1.zip
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_C.gigas_roslin_v1.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_C.gigas_roslin_v1.zip]

**Comment by robertwhbaldwin** [comment]
I was able to use wget to download the db not sure why the download function didn't work. seems to work though

**Comment by pcingola** [comment]
It sounds like this is simply that you are using a genome name that is not in the config file.

**Comment by robertwhbaldwin** [comment]
Yes I figured it out. The reference genome for this species is not the one used by snpEff so I donwloaded to roslin assembly and built a custom db myself
