### ISSUE TITLE
DATABASE BUILD ISSUE

### ISSUE THREAD

**Issue by andreeedna** [pcingola/SnpEff#478]
I am trying to build a database using a genbank annotation but I have this warning:

_WARNING_CHROMOSOME_CIRCULAR: Chromosome 'NC_064473.1' (len=100000020) has exon with end coordinate after chromosome end: Marking as 'circular'. Exon:NC_064473.1:251962284-251962414 'XM_048833681.1_2', rank: 2, frame: ., sequence:_ 

the problem is that it is not a circular genome and goes to reduce the length of the reference genome (a few lines earlier is correct -> 00:00:02 Chromosome: 'NC_064473.1'	length: 345741823)
I don't know how to resolve this problem, if I'm missing a flag or i have to modify the gb file (i also tried to use the buildDbNcbi.sh but i have the same problem)

1. SnpEff version: SnpEff 5.1d
2. Genome version: NC_064473.1
3. SnpEff full command line: java -Xmx20g -jar snpEff.jar build -v -genbank CHR1caretta

**Comment by ymcki** [comment]
I too had this problem while building db from genbank format. What's going on?

**Comment by andreeedna** [comment]
I tried every way but gave up
