### ISSUE TITLE
FATAL ERROR: No CDS checked.

### ISSUE THREAD

**Issue by selasphoruskershaw** [pcingola/SnpEff#482]
Hello,

I am trying to manually add an annotated reference genome to the snpEff database, but I am running into the following error, and it appears that the process won't run to completion:

"FATAL ERROR: No CDS checked. This is might be caused by differences in FASTA file transcript IDs respect to database's transcript's IDs."

I've come across several identical error messages others have run into and haven't been able to resolve. Any help would be much appreciated.

**Comment by barbarian1803** [comment]
You should check transcript ID in your GTF file and in the FASTA file. It should match.
