### ISSUE TITLE
Potential LOF mutation being annotated as intergenic variant

### ISSUE THREAD

**Issue by bvaditi** [pcingola/SnpEff#483]
From a previous study on whole genome data two mutations in exonic region are putatively LOF. I tried to confirm with snpEff but it is being annotated as intergenic variant.  SnpEff version is 4.3 and database is built with a gff file.

Since the vcf has only exonic variants this result is unexpected. The mutation is identified as LOF from Ensembl-VEP

Input file:

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  AMU_DU1 AMU_DU2 AMU_DU3 AMU_DU4 AMU_DU5 AMU_SJ1 AMU_SJ2 AMU_SJ3 AMU_SJ4 AMU_SJ5 AMU_SJ6 AMU11   AMU1    AMU24   AM
E1      22424652        .       G       A       999     .       .       GT:PL:GQ        0/0:0,78,255:74 0/1:151,0,255:99        0/0:0,114,255:99        0/1:255,0,190:99        0/1:255,0,
E2      3583725 .       C       T       188     .       .       GT:PL:GQ        0/0:0,75,255:94 0/0:0,102,255:99        0/0:0,96,255:99 0/0:0,72,255:91 0/0:0,81,255:99 0/0:0,27,248:46 0/
E2      3583725 .       C       T       188     .       .       GT:PL:GQ        0/0:0,75,255:94 0/0:0,102,255:99        0/0:0,96,255:99 0/0:0,72,255:91 0/0:0,81,255:99 0/0:0,27,248:46 0/
E2      3583725 .       C       T       188     .       .       GT:PL:GQ        0/0:0,75,255:94 0/0:0,102,255:99        0/0:0,96,255:99 0/0:0,72,255:91 0/0:0,81,255:99 0/0:0,27,248:46 0/

Output:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  AMU_DU1 AMU_DU2 AMU_DU3 AMU_DU4 AMU_DU5 AMU_SJ1 AMU_SJ2 AMU_SJ3 AMU_SJ4 AMU_SJ5 AMU_SJ6 AMU11   AMU1    AMU24   AM
E1      22424652        .       G       A       999.0   .       ANN=A|intergenic_region|MODIFIER|||||||||||||   GT:PL:GQ        0/0:0,78,255:74 0/1:151,0,255:99        0/0:0,114,255:99
E2      3583725 .       C       T       188.0   .       ANN=T|intergenic_region|MODIFIER|||||||||||||   GT:PL:GQ        0/0:0,75,255:94 0/0:0,102,255:99        0/0:0,96,255:99 0/0:0,72,2
E2      3583725 .       C       T       188.0   .       ANN=T|intergenic_region|MODIFIER|||||||||||||   GT:PL:GQ        0/0:0,75,255:94 0/0:0,102,255:99        0/0:0,96,255:99 0/0:0,72,2
E2      3583725 .       C       T       188.0   .       ANN=T|intergenic_region|MODIFIER|||||||||||||   GT:PL:GQ        0/0:0,75,255:94 0/0:0,102,255:99        0/0:0,96,255:99 0/0:0,72,2

**Comment by pcingola** [comment]
Closing old issues.

I assume this was solved, but just in case, here are some tips:

According to your statement

>   ...database is built with a gff file.

I understand you've built the database yourself from a GFF file.
So the problem seems to be that you GFF does not have a gene in that region.

**Comment by bvaditi** [comment]
Thank for your response. The SNP is not in the intergenic region. It is
within a gene and this was confirmed by using Blast for the region around
the SNP. In the gff file too it is a listed as a genic SNP. Previously it
was annotated as LOF using Ensembl VEP using the same gff, reference and
VCF

Please let me know your thoughts. I am just wondering why there would be
such a drastic difference in results between the two tools.

Best regards,
Aditi

**Comment by pcingola** [comment]
Can you share the GFF file? Without that information I cannot replicate the problem.
If you can also send the source VCF file and the full command line you've used, it would be better.

**Comment by bvaditi** [comment]
Hello,

Sorry for the late reply. The files are here:

VCF:
https://drive.google.com/file/d/1fnkl3AwQWwtj62E1GPiNkl3dtkT8WFQp/view?usp=sharing
gff:
https://docs.google.com/spreadsheets/d/1hY0k4dK47U5mXKPoyuZAHxj7pbmTu5js/edit?usp=sharing&ouid=111084923768176450529&rtpof=true&sd=true

The command line is as follows:
java -jar /home/uramakri/vinays/softs/snpEff/snpEff/snpEff.jar -c
/home/uramakri/vinays/softs/snpEff/snpEff/snpEff.config machliGenome
Pan_tig_bcftools_All_Immune_Exons_Removelowdepth_sort_filtered_LOF.recode.vcf
 >
Pan_tig_bcftools_All_Immune_Exons_Removelowdepth_sort_filtered_LOF_Ann.recode.vcf


Best regards,
B.V.Aditi Prasad,
Research Fellow,
National Center for Biological Sciences,
Tata Institute of Fundamental Research, India
She/Her.

**Comment by bvaditi** [comment]
Hello,

Wanted to follow up on this, if you were able to check?

Looking forward to hearing from you.

Best,
Aditi

**Comment by bvaditi** [comment]
Dear Cingolani,

Hope this email finds you well. I am still interested in sorting this out.
Would it be possible to have a look at the files?

Best regards,
Aditi

B.V.Aditi Prasad,
Research Fellow,
National Center for Biological Sciences,
Tata Institute of Fundamental Research, India
She/Her.
