### ISSUE TITLE
RUN snpEff-unable to access jarfile snpEff.jar

### ISSUE THREAD

**Issue by Ligerd5** [pcingola/SnpEff#486]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. SnpEff version: 4.2 and 5.0
2. Genome version:
3. SnpEff full command line: java -jar snpEff.jar
4. Output / Error message: error message unable to access jarfile snpEff.jar. 
I am used the command in my terminal (MobaXterm) and SnpEff and java file are in the same location. I created a conda environment in which I put the SnpEff and the java. So I do not know what I am doing wrong. 
Please can anyone help with this issue?

**Comment by pcingola** [comment]
It sound like you need to run the comment in SnpEff's directory.
