### ISSUE TITLE
Change Log?

### ISSUE THREAD

**Issue by schorlton** [pcingola/SnpEff#488]
**Describe the issue**

Thanks for your continued work on SnpEff. In order to keep track of updates, is there a change log available? I could not easily find one.

I see 325 files were changed between 5.1f and 5.1d (https://github.com/pcingola/SnpEff/compare/v5.1d...v5.1f) but I can't make sense of all of the changes/commits. Thanks!

**Comment by pcingola** [comment]
Apologies, documentation is hard and have very limited time.
Your are more than welcome to contribute to the project.

**Comment by schorlton** [comment]
Hi @pcingola , thanks for the reply - I appreciate that documentation is hard and the amount of effort you put into snpEff. I would be happy to contribute; probably documentation (and specifically a change log) is one of the hardest items to contribute as an external contributor. Having documentation (eg. a template change log) would then enable external contributors to PR and add their contributions to the change log. Without this foundation, you face issues like https://github.com/pcingola/SnpEff/issues/371#issuecomment-1842616371 where it is not at all clear for an external contributor what work is remaining to address support for HGVS. Worse, it is not clear for your users what the limitations of the software are and how to go about updating.

Again, thank you for your work on this project and would be happy to help where possible.

**Comment by pcingola** [comment]
Hi @schorlton ,
  Great to hear that you'd like to contribute!
Let me know how you'd like to start helping the project.
