### ISSUE TITLE
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_CDC.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_CDC.zip]

### ISSUE THREAD

**Issue by Shubhashish006** [pcingola/SnpEff#493]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. SnpEff version: Latest
2. Genome version: chickpea CDC frontier v3
3. SnpEff full command line: Yes
4. Output / Error message: Please include detailed infomration, such as transcript ID, VCF line output, etc.
FATAL ERROR: Failed to download database from [https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_CDC.zip, https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_CDC.zip]
**Expected behavior**
A clear and concise description of what you expected to happen (show program's output for comparisson)
I want to annotate vcf files but after completing the database and i tried annotating and I stuck with the above error. 
**Data**
Sample data. No need to add the full genomic dataset, but a few input lines enough to reproduce the conditions.
WARNING: Always attach the data files such as VCF lines.

**Additional context**

**Comment by pcingola** [comment]
I don't know a genome called CDC (chickpea), and could not find it in the config file
