### ISSUE TITLE
Release notes for snpEff5.1

### ISSUE THREAD

**Issue by niuliliscience** [pcingola/SnpEff#494]
Dear Pablo, 
Our team has been using snpEff 5.0 for our commercial software. Recently we observed some vulnerability of snpEff 5.0. 
We see snpEff 5.1 is available. and we are planning to test it. For software regulation, it is needed to document the changes between versions of software. 
We wonder if you have the release notes for snpEff5.1 which states the changes/updates comparing to previous version (such as snpEff 5.0). 
Also we are using Human annotation databases for Ensembl GRCh38.99 and Refseq GRCh38.p13. However, the Ensembl GRCh38.99 is not available for the links below:                                              	          	                              	https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.99.zip.

5.1 for ensembl errors out and 5.0 for refseq errors out. 
### Database requests

1. Organism name: Human
2. Link gene definition file (e.g. GTF / GFF / GenBank): https://ftp.ensembl.org/pub/release-99/gtf/homo_sapiens/Homo_sapiens.GRCh38.99.gtf.gz
3. Link to Genome FASTA file/s: https://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/dna/
4. Link to CDS FASTA file: https://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/cds/Homo_sapiens.GRCh38.cds.all.fa.gz
5. Link to Protein FASTA file: https://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/pep/Homo_sapiens.GRCh38.pep.all.fa.gz

### Feature requests
We wonder if you have the release notes for snpEff5.1 which states the changes/updates comparing to previous version (such as snpEff 5.0). 

**Describe the solution you'd like**
The release notes for snpEff5.1 which states the changes/updates comparing to previous version

**Comment by pcingola** [comment]
Sorry, keeping release notes and documentation can be challenging.

GRCh38.99 is available for download

```
$ snpeff download -v GRCh38.99
00:00:00 SnpEff version SnpEff 5.2b (build 2023-11-21 11:36), by Pablo Cingolani
00:00:00 Command: 'download'
00:00:00 Reading configuration file 'snpEff.config'. Genome: 'GRCh38.99'
...
00:00:00 Downloading database for 'GRCh38.99'
00:00:00 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_2/snpEff_v5_2_GRCh38.99.zip' to local file '/var/folders/jb/45jcdj5d1r9bhbdyvg93qz3h0000gq/T//snpEff_v5_2_GRCh38.99.zip'
00:00:00 Connecting to https://snpeff.blob.core.windows.net/databases/v5_2/snpEff_v5_2_GRCh38.99.zip
00:00:00 Connecting to https://snpeff.blob.core.windows.net/databases/v5_2/snpEff_v5_2_GRCh38.99.zip, using proxy: false
00:00:00 ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_2/snpEff_v5_2_GRCh38.99.zip
00:00:00 Downloading from 'https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.99.zip' to local file '/var/folders/jb/45jcdj5d1r9bhbdyvg93qz3h0000gq/T//snpEff_v5_0_GRCh38.99.zip'
00:00:00 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.99.zip
00:00:00 Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.99.zip, using proxy: false
00:00:01 Local file name: '/tmp/snpEff_v5_0_GRCh38.99.zip'
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................00:03:28
00:03:28 Download finished. Total 610699657 bytes.
...
00:03:29 Unzip: OK
00:03:29 Deleted local file '/tmp/snpEff_v5_0_GRCh38.99.zip'
00:03:29 Done
00:03:29 Logging
00:03:30 Done.
```
