### ISSUE TITLE
Which version of the annotations should I use for GRCh38DH?

### ISSUE THREAD

**Issue by zj-jennie** [pcingola/SnpEff#496]
I am using the reference genome version provided by UKbiobank as GRCh38DH（GRCh38_full_analysis_set_plus_decoy_hla）, and the version number of the gene used is GCA_000001405.15, which is the initial version of GRCh38 at the end of 2013. And now I want to know which version of the annotation database should I use? Thank you!

GRCh38.mane.0.95.ensembl
GRCh38 .mane.0.95.refseq
GRCh38 .mane.0.93.refseq
GRCh38.mane.1.0.ensembl
GRCh38.mane.1.0.refseq
GRCh38.p13
GRCh38.p14

**Comment by pcingola** [comment]
Sorry I cannot fully understand your question.
Generally speaking, you should use the reference genome that is more appropriate for your research / clinical question.

**Comment by zj-jennie** [comment]
I would like to ask how the annotation database should be selected for different versions of the reference genome. Such the version number of the gene used is GCA_000001405.15, which is the initial version of GRCh38 at the end of 2013. How should I select the appropriate annotation database for it？

**Comment by pcingola** [comment]
It depends on what you are trying to do.

For example, when I'm doing research, I tend to use ENSEMBL's version (e.g. GRCh38.99), but other other prefer RefSeq (GRCh38.p14). But when I need something targeted towards clinical applications, I tend to use MANE (GRCh38.mane.1.2.ensembl) and in this case the use of ENSEMBL/REFSEQ depends on your other applications and compliance environment.

If you don't know, a good choice would be the latest ENSEMBL (GRCh38.99).

**Comment by zj-jennie** [comment]
What if I want to annotate the vcf after calling, and my goal is to look for clonal hematopoiesis？

**Comment by pcingola** [comment]
I'd use the latest available ENSEMBL (e.g. GRCh38.99)
