### ISSUE TITLE
ERROR 409 : Public access is not permitted for downloading binary or databases

### ISSUE THREAD

**Issue by DanielKwon** [pcingola/SnpEff#503]
**Describe the issue**
ERROR occurred when downloading binary or databases

**To Reproduce**
1. SnpEff version: 5.2
2. Genome version: GRCh38
3. SnpEff full command line: - 
4. Output / Error message: -

**Expected behavior**
I need the GRCh38 database to run snpeff command.

**Data**
-

**Additional context**

(base) kkwon@workstation:~/snpeff/SnpEff$ wget https://snpeff.blob.core.windows.net/databases/v5_2/snpEff_v5_2_GRCh38.p14.zip

--2023-10-24 18:20:02--  https://snpeff.blob.core.windows.net/databases/v5_2/snpEff_v5_2_GRCh38.p14.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-10-24 18:20:03 ERROR 409: Public access is not permitted on this storage account..

(base) kkwon@workstation:~/snpeff/SnpEff$ wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip

--2023-10-24 18:20:11--  https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-10-24 18:20:12 ****ERROR 409: Public access is not permitted on this storage account****..

**Comment by mhjiang97** [comment]
I got the same issue. Downloading still worked well just a week ago. Hope this gets solved soon.

**Comment by mhjiang97** [comment]
Hi.
You can manually download desired database using torrent.

**Comment by mhjiang97** [comment]
Hi. You can download desired dataset manually. I just downloaded GRCh38.105 at `https://snpeff.blob.core.windows.net/databases/v5_1/snpEff_v5_1_GRCh38.105.zip` using `Xunlei Thunder`. But I can only find the Chinese website of Xunlei: https://www.xunlei.com

**Comment by lorepaga1996** [comment]
Hi, I have the same issue. @mhjiang97 can you explain how it works the download using Xunlei Thunder? Does anyone have other solutions?

**Comment by mhjiang97** [comment]
<img width="869" alt="1" src="https://github.com/pcingola/SnpEff/assets/53030037/ba09b1d6-ff19-4fa1-b76e-c122a06dc95c">
1. After registration or log in, you can press the `+` button to start a job.
<img width="855" alt="2" src="https://github.com/pcingola/SnpEff/assets/53030037/e4b71ec6-e1a0-4f2b-990f-48c016772b27">
2. Then select this one to download from a link.
<img width="843" alt="3" src="https://github.com/pcingola/SnpEff/assets/53030037/70dba227-1828-49c2-a1dc-54eaddc80c79">
3. paste the link from snpEff, then start the job.

Hope this is helpful.

**Comment by lorepaga1996** [comment]
Unfortunately the download doesn't work

**Comment by slagelwa** [comment]
Yep broken

**Comment by wwolfsberger** [comment]
Experiencing the same issue.

**Comment by mjhipp** [comment]
Same issue with 5.1

**Comment by TKMarkCheng** [comment]
Experiencing the same issue with downloading snpEff as well. Tried removing snpEff and re-installing and now can't even get `snpEff_latest_core.zip` by  `wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip`
Error:
```
--2023-10-24 17:52:15--  https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-10-24 17:52:16 ERROR 409: Public access is not permitted on this storage account..
```

**Comment by bcantarel** [comment]
seems as though this bucket is no longer public, which is where all of the data is stored https://snpeff.blob.core.windows.net
<img width="1151" alt="image" src="https://github.com/pcingola/SnpEff/assets/7647927/3fd07508-baa1-4523-a194-6975de47dfe3">

**Comment by pcingola** [comment]
Hi everyone,
  Thank you for the heads up. I'm trying to get this fixed. Hopefully it will be resolved shrtly.
All the best

   Pablo

**Comment by pcingola** [comment]
The issue is now solved. Thank you Erdal!
