### ISSUE TITLE
 ERROR 409: Public access is not permitted on this storage account..

### ISSUE THREAD

**Issue by RohitKapila** [pcingola/SnpEff#505]
Hi,
I am getting the following error.
ERROR 409: Public access is not permitted on this storage account.

Trying to download it and run it,  but HPC engineers are getting the same error of no access to run it on my PC or on nstitute's HPC.

**Comment by mjhipp** [comment]
#503

**Comment by pcingola** [comment]
I think this was fixed some time ago by Microsoft.
