### ISSUE TITLE
"N" in ALT being changed to A,C,G,T - undesirable

### ISSUE THREAD

**Issue by dandanxu** [pcingola/SnpEff#54]
I'm having a problem where some of the records in my VCF files have a single N in the ALT field. SnpEff/SnpSift keeps changing these to A,C,G,Ts. Is there any way to turn this feature off in the future? Or for that matter, a feature that makes it so that SnpEff doesn't change _anything_ in the original VCF record besides adding a INFO field.

Example: original VCF record, VCF record after SnpEff

```
1 123456    rs123  NTGTATT  N

1 123456    rs123  NTGTATT  A,C,G,T
```

**Comment by pcingola** [comment]
Closing old issues.
