### ISSUE TITLE
Extract disulphide bond feature

### ISSUE THREAD

**Issue by gpcr** [pcingola/SnpEff#69]
Great tool. thanks for your efforts

I am not sure or  am i missing how to extract sequence_feature[disulfide_bond] from the SNPeff annotated vcf. It will be great if you can add this in the documentation

**Comment by pcingola** [comment]
That's a NextProt annotation. 
You can read about NextProt's here: http://www.nextprot.org/
I hope this helps.

**Comment by gpcr** [comment]
Sorry, not really, how can we extract nextprot feature like disulfide using SnpSift? similar to if it is missense or not

**Comment by pcingola** [comment]
Sorry, I'm not sue I understand what you mean by "similar to if it is missense or not"
Can you clarify? May be you can add an example...

**Comment by gpcr** [comment]
java -jar SnpSift.jar filter "ANN[*].EFFECT = 'missense_variant'" input.ann.vcf

for example: 
java -jar SnpSift.jar filter "ANN[*].EFFECT = 'disulfide_bond'" input.ann.vcf

**Comment by pcingola** [comment]
Sorry for the long delay answering your question.
The way to do it would be something like:

    cat examples/test.chr22.ann.vcf | java -jar SnpSift.jar filter "ANN[*].FEATURE = 'disulfide_bond'" 

It works using 'ANN' field though (it is not possible with 'EFF'' field) so you might have to re-annotate your VCF file.

**Comment by gpcr** [comment]
Thanks
