### ISSUE TITLE
Add config option for '/tmp' dir

### ISSUE THREAD

**Issue by pcingola** [pcingola/SnpEff#72]
From a user:
   How come it writes to /tmp/? It is a good habit applications write to /var/tmp or /usr/tmp, especially huge files. Is this configurable?

**Comment by isbslagelwa** [comment]
2nd this

**Comment by pcingola** [comment]
This has been fixed quite some time ago and it uses

     System.getProperty("java.io.tmpdir")

So you should be able to set it using Java's "-D" command line option.
