### ISSUE TITLE
 Interval has negative coordinates.

### ISSUE THREAD

**Issue by ghost** [pcingola/SnpEff#75]
I write this on the command line:
snpEff hg19 Rem_Dia_12_keep.vcf -stats >snpeff12
The Rem_Dia is my File in the direction,
some things inside work, but i get some error for 10 from 50 lines:

Error: Error while processing VCF entry (line 31) :
	11	0	CTGxCAT	G	A	.	.	.
java.lang.RuntimeException: Interval has negative coordinates.
	Class        : Variant
	Start        : -1
	End          : -1
	ID           : CTGxCAT
	Parent class : Chromosome
	Parent       : 11	0-135006515 CHROMOSOME '11'

The lines aren't other that the other lines. 
in my file there isn't a zero it looks like this:
11      5602213         CTGxCAT G       A . . .
so why does they set 0 instead of 5602213.
And why doens't they do this for only a few lines ...

I don't know whats wrong. 
Can someone help me?

**Comment by pcingola** [comment]
Sorry, I really tried, but I cannot understand what you are trying 
to say. Could you give a simple explanation with a trivial example 
that shows to issue? Perhaps should also take a quick look at these 
guidelines on how to ask for help http://snpeff.sourceforge.net/about.html#help

**Comment by pcingola** [comment]
Closing due to lack of feedback.
