### ISSUE TITLE
Interval has negative coordinates.

### ISSUE THREAD

**Issue by coolucy** [pcingola/SnpEff#83]
Hi, 

i want to build a database from gff file, but i got the follow error. 
##########################################################################
Caused by: java.lang.RuntimeException: Interval has negative coordinates.
 Class        : Exon
 Start        : -1
 End          : 240485
 ID           : exon:tetur03g00850.5
 Parent class : Transcript
 Parent       : scaffold_3:239958-244319, strand: -, id:mRNA:tetur03g00850
   Exons:
   scaffold_3:239958-240111 'exon:tetur03g00850.6', rank: 0, frame: 1, sequence:
##########################################################################

However, when i looked up the line, I couldn't find any nevative corrdinates.
##########################################################################
scaffold_3      EGN exon   240343 240486  .       -       1 ID=exon:tetur03g00850.5;Parent=mRNA:tetur03g00850;Ontology_term=SO:0000004
##########################################################################

SNPEFF version :  "4.1d"
command line : 
java -Xmx4g -jar $SNPEFF build -gff3 -v Tetur_build

To build database i created a folder at /snpEff/data/Tetur/build
and also genes.gff.gz, sequences.fa.gz
and added a genome to the configuration file(http://snpeff.sourceforge.net/SnpEff_manual.html#databases).

Could you please help me to fix it?

**Comment by pcingola** [comment]
I assume there is a problem in you GTF file. It might be somehow corrupted or not 
following the GTF specification).
You should try to send the data files (in your case the GTF and FASTA) like 
recommended in the guidelines (http://snpeff.sourceforge.net/about.html#help). 
Unfortunately without that data, there is not much I can do.

**Comment by coolucy** [comment]
Thank you for your reply. 
i sent email to you(pcingola@users.sourceforge.net). I attached GFF and FASTA files.

**Comment by coolucy** [comment]
I think I found the error.
the GFF file had an extra space in front of the start coordinate.

**Comment by pcingola** [comment]
Sorry for the long delay answering your email, I was on vacation.
I'm glad to hear it works OK.

**Comment by pcingola** [comment]
This seems to be solved. Closing
