### ISSUE TITLE
snpEFF always uses all available cores

### ISSUE THREAD

**Issue by jasper1918** [pcingola/SnpEff#86]
No matter how the command is run, with -t or not, snpEFF always uses all available cores. The program does recognize the -t flag but does not use this to change the number of workers.

**Comment by pcingola** [comment]
The program always run in single threaded mode by default (i.e. if not "-t" is provided).

I'm not sure why you think SnpEff runs "on all cores", but may be you are seeing by Java's garbage collection threads (which can be controlled by java's "-XX:ParallelGCThreads" command line option).

**Comment by jasper1918** [comment]
Pablo,

Thanks for your insight. I found the defaults on our server to be -XX:ParallelGCThreads=33 and when I set to a low number at  command line the cpu usage was dramatically decreased to something more reasonable. No problems with snpEFF.

Thanks!

**Comment by pcingola** [comment]
OK, closing then.
