### ISSUE TITLE
dbSNFP download broken

### ISSUE THREAD

**Issue by holtgrewe** [pcingola/SnpEff#88]
The sourceforge download site says:

> Unable to find any mirror information for the "/databases/dbNSFP/dbNSFP2.9.txt.gz" file. Please select another file.

**Comment by pcingola** [comment]
SnpEff's files are hosted on SourceForge and unfortunately they've been
refusing to serve large files (over 5GB). I'm looking for alternatives, but I
haven't been able to find another reliable, free service (suggestions are
welcome).
   One solution is to download the original dbNSFP ZIP file and create the
TXT files (and index) as explained in the documentation.
    http://snpeff.sourceforge.net/SnpSift.html#dbNSFP
In the latest SnpEff release there is a script called "make_dbNSFP.sh" to
help with the process.
