### ISSUE TITLE
EML4-ALK fusion / inversion annotation

### ISSUE THREAD

**Issue by mjafin** [pcingola/SnpEff#97]
Hi Pablo,
I'm looking at the output of both Manta and Lumpy for a reference standard sample that harbours the EML4-ALK fusion. It is represented by both tools as an inversion rather than a breakend. SnpEff annotates ALK correctly but there is no mention of EML4. 

I'm not sure what the correct path forward would be, but would it be possibly to also mention what's at the other end of the inversion? `END` gives the end coordinate, which in this case points to an intron of EML4.

Any ideas?

**Comment by pcingola** [comment]
Hi,
  Can you send me the VCF entries and the command line 
you are using so I can take a deeper look at this issue?

**Comment by mjafin** [comment]
Certainly, thanks for looking into the issue so promptly.

**Comment by pcingola** [comment]
I'm out of town right now, but I'll try to take a 
look at it next week when I'm back home.

**Comment by mjafin** [comment]
Excellent, thanks so much

**Comment by mjafin** [comment]
Hi Pablo,
Have you had a chance to look at this? My idea would be to add the names of genes that are hit by the `END` coordinate in INV/DUP/DEL. This would help tag events that can lead to fusion transcripts.

**Comment by pcingola** [comment]
Done. Fussion are also calculated and annotated.
